### ISSUE TITLE
Feature Request: OPDS-support

### ISSUE THREAD

**Issue by b3nd1k** [advplyr/audiobookshelf-app#1069] opened 2024-02-07 14:41 UTC
If I had a seperate eBook-library in ABS. It would be great if I could enable ODPS-support. With it enabled, it would automatically sync book and the read status of the book between the app I use for reading and ABS as the library.

There are reader apps both for iPad and Android that supports ODPS, so it would be great to see an implemntation of this. 

Other containers such as Ubooquity and Kavita supports ODPS, but it would be nice to have all eBooks and Audiobooks in the same app.

**Comment by nichwall** [comment] 2024-02-07 14:57
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1953

**Comment by advplyr** [comment] 2024-02-07 14:57
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1953

**Comment by advplyr** [comment] 2024-02-07 14:58
I'm seeing a bunch of new issues getting opened by you and I haven't looked through them all yet but I would guess a lot are duplicates from the main repo. Please do a search before opening new issues

**Closed by advplyr** 2024-02-07 14:57 UTC
Labels: enhancement
