### ISSUE TITLE
Downloaded item and server item have different book details page

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#842] opened 2023-08-14 14:22 UTC
### Steps to reproduce

1. Open book details when connected to server and when disconnected from server
2. Or click on book details from local books shelf and open it from continue series shelf
3. Can't remember for sure, but I think it's #2

### Expected behaviour
- shouldn't the details page be the same?

### Actual behaviour
See images

![Screenshot_2023-08-14-19-37-10-72_e9782661401ed6f222682e1e02b74bd4.jpg](https://github.com/advplyr/audiobookshelf-app/assets/42061703/12e01954-da8b-443b-bf9e-832f99191cd5)

![Screenshot_2023-08-14-19-37-00-82_e9782661401ed6f222682e1e02b74bd4.jpg](https://github.com/advplyr/audiobookshelf-app/assets/42061703/291cda1f-4c03-4d2f-996f-358b580bbd1b)

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.65-beta

Device model: OnePlus Nord 3e

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment] 2023-08-14 14:55
The only thing that gets synced after you download a book is the progress. If you change anything on the server after a download it won't be reflected. There are 2 other issues open related to keeping local metadata in sync but I don't have time to find them at the moment. I think we can basically merge all of these into one github issue since they would all be tackled at the same time.

**Comment by raviwarrier** [comment] 2023-08-15 00:23
The book data wasn't updated after it was downloaded.

**Comment by advplyr** [comment] 2023-12-11 20:29
Duplicate of #642

**Closed as not planned by advplyr** 2023-12-11 20:29 UTC

**Comment by advplyr** [comment] 2023-12-11 20:31
Thanks, the series will only not be shown now when not connected to the server since it now redirects to the server page.

I'm leaning towards not implementing all of the navigation for series, authors, collections, playlists, etc. when offline since that is a major task when usually you just have a few books downloaded at a time. In that case the offline view will look a bit different and not show the authors, series, etc. navigation buttons at the top.

**Comment by sharinganthief** [comment] 2024-01-02 18:52
at a minimum i would like the series and position, preferably also sorted.
is this related to the downloaded books not showing in the "main" areas, Library, Series, etc?
i had downloaded many books for a trip recently and a new series i wasn't 100% on the order of so it was annoying to google which book cam next when i knew that info was already in abs.
