### ISSUE TITLE
More Playback Speed variations

### ISSUE THREAD

**Issue by realtobman** [advplyr/audiobookshelf-app#1066] opened 2024-02-06 23:10 UTC
### Is your feature request related to a problem? Please describe.

Sometimes, when I listen to a fast Reader, I want to slow down the Reading a bit. But when I choose 0.9 as a Playback Speed, it is already to slow for my taste.

### Describe the solution you'd like

I personally dont use the Speed variations greater than 0.9 - 1.2, because slower or faster than this speed makes the voices sound anojing. Because of that I think this area should be controlled in 0.01 steps.

The plus and minus Buttons should increase or decrease the tempo by 0.01% or 0.05%. With that Feature, the Audiobook Playback Speed could be much more adjusted.

### Describe alternatives you've considered
If that ist not possible, it would be great if you could implement a 0.95x step in reading Speed variation.
 

### Additional context
I use currently the Android App Version 0.9.71 beta. And as Server 2.72.

**Comment by nichwall** [comment] 2024-02-06 23:17
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/461

**Comment by realtobman** [comment] 2024-02-06 23:22
Sorry, I overlooked that. Now that the question was already asked in 2022, can the coders reconsider that?

**Comment by nichwall** [comment] 2024-02-06 23:24
The best way to show support for a feature request is to leave a thumbs up reaction on the feature.

**Comment by realtobman** [comment] 2024-02-06 23:30
It's Not much what one user can do , but I left a thumpsup there @issue 461.

**Comment by advplyr** [comment] 2024-02-06 23:56
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/461

**Closed by advplyr** 2024-02-06 23:56 UTC
Labels: enhancement
