### ISSUE TITLE
iOS ebook download

### ISSUE THREAD

**Issue by Jmanko16** [advplyr/audiobookshelf-app#753] opened 2023-06-22 00:06 UTC
### Is your feature request related to a problem? Please describe.
On iOS app would like ability to download epub or pdf file to local device to open in another reading app that supports highlighting, etc.

### Describe the solution you'd like
Allow app to download the epub/pdf to device (similar to how web login on phone will allow download of native file)

### Describe alternatives you've considered
I use the web log in to get epub and pdf to device, but family members who I share with want to use the app as they are not tech savvy enough to use mobile app and the web login.

**Comment by Jmanko16** [comment] 2023-06-22 00:21
Sorry double post

**Comment by advplyr** [comment] 2023-06-24 20:20
Duplicate of #496

**Closed by advplyr** 2023-06-24 20:20 UTC
Labels: enhancement, awaiting release
