### ISSUE TITLE
Unable to connect to server from App

### ISSUE THREAD

**Issue by CunningSquirrel** [advplyr/audiobookshelf-app#585] opened 2023-02-15 18:32 UTC
Unable to connect to app using duckdns for remote play after latest update. Can still connect using duckdns link through web browser however.

App still works if I use I.P address instead of duckdns.

Definitely not a firewall issue as duckdns still works via Safari web browser.

**Comment by advplyr** [comment] 2023-02-15 18:36
Duplicate of #538

**Closed by advplyr** 2023-02-15 18:36 UTC
