### ISSUE TITLE
Enhancement: Android; When casting the volume controls should change the cast volume not the phone's volume. 

### ISSUE THREAD

**Issue by lerndmina** [advplyr/audiobookshelf-app#763] opened 2023-06-27 20:20 UTC
### Is your feature request related to a problem? Please describe.
When casting audio from the app, it would be great if the system volume controls would change the casting volume, not my phone's volume. 

### Describe the solution you'd like
While casting system volume controls should change cast volume. 

### Describe alternatives you've considered
Other than opening the Google home app or interacting directly with the cast device, there is no other way to change the volume. 

### Additional context
![Screenshot_20230627-211603.png](https://github.com/advplyr/audiobookshelf-app/assets/10632157/564a5a66-b355-4d80-be74-555ca1084f4d)

**Comment by advplyr** [comment] 2023-06-27 20:22
Duplicate of #584

**Closed by advplyr** 2023-06-27 20:22 UTC
