### ISSUE TITLE
Incorrect placement of toast on the webapp

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#275] opened 2022-07-08 06:21 UTC
Can't get to the buttons behind this toast and can't close it without canceling the scan.
![image](https://user-images.githubusercontent.com/42061703/177929418-74c523c2-d429-445b-92a8-ace5bb49fc42.png)

Please fix this.

### Steps to reproduce

1. NA
2.
3.

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [ ] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment] 2022-07-08 10:11
Duplicate of https://github.com/advplyr/audiobookshelf/issues/819

**Closed by advplyr** 2022-07-08 10:11 UTC
Labels: bug
