### ISSUE TITLE
[Bug]: Downloaded books do not display cover art in Android Auto

### ISSUE THREAD

**Issue by xcsdm** [advplyr/audiobookshelf-app#1330] opened 2024-09-25 13:43 UTC
### What was the Problem?

When streaming a title from the ABS server, cover art is shown in the dashboard view, full screen view, and widget in the bottom tool bar.

When playing a downloaded title, cover art is missing in dashboard and full screen view.

In case it is relevant, nearly my entire collection is m4b files.

### Steps to Reproduce the Issue

Download a title and listen while using Android Auto.

### What was Expected?

Cover art should display the same for downloaded and streamed titles.

### Phone Model

Samsung Galaxy Z Fold 5

### Phone OS

Android 14, OneUI 6.1.1

### Audiobookshelf App Version

Android App - 0.9.76

### Installation Source

Google Play Store

**Comment by advplyr** [comment] 2024-09-25 13:50
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/141

**Closed by advplyr** 2024-09-25 13:50 UTC
Labels: bug
