### ISSUE TITLE
[Bug]: App Crashing

### ISSUE THREAD

**Issue by arrakis8bm** [advplyr/audiobookshelf-app#1211] opened 2024-05-25 18:04 UTC
### What was the Problem?

App will play for a while before crashing unexpectedly. Issue started occurring since the last update

### Steps to Reproduce the Issue

Play an audiobook from local storage

### What was Expected?

Continue to play audiobook with out crashing. 

### Phone Model

Pixel 4

### Phone OS

android 13

### Audiobookshelf App Version

Android App - 0.9.63

### Installation Source

Google Play Store

### Additional Notes

version 0.9.74-beta

**Comment by advplyr** [comment] 2024-05-25 18:32
You have to remove the local folder which removes all the downloads. Then add the local folder again so it can ask you for permission. This crash is a permission issue that I don't know how to replicate and so don't know how to resolve at this time.

It is yet to happen to me on Android 13 Pixel 6. There is already a bug report open for this #773.
These permission issues are the main reason that Internal Storage was added and set to default.

**Comment by advplyr** [comment] 2024-05-25 18:33
Duplicate of #773

**Closed by advplyr** 2024-05-25 18:33 UTC
Labels: bug
