### ISSUE TITLE
local server address for local access remote url for remote access

### ISSUE THREAD

**Issue by Tsamsiyu1** [advplyr/audiobookshelf-app#1118] opened 2024-03-06 09:25 UTC
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
i would like to access my audiobookshelf server via the local ip adress when i am home and not go over internet. but when i leave my wifi i what to access it back via my remote url.

### Additional context
Home Assistant does this very well. you can add local wifi's and saywithin the local wifi use the local ip address and when exiting the wifi's change to the remote url.

**Comment by nichwall** [comment] 2024-03-06 13:48
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/209

**Comment by advplyr** [comment] 2024-03-06 21:04
Duplicate of #209

**Closed by advplyr** 2024-03-06 21:04 UTC
Labels: enhancement

**Comment by sbadger** [comment] 2024-12-12 00:16
Use the DNS override in you local home router/firewall to do this without needing to change the app at all.
