### ISSUE TITLE
[Enhancement]: Ability to auto delete audiobooks when finished

### ISSUE THREAD

**Issue by Doppelgangsta** [advplyr/audiobookshelf-app#1300] opened 2024-08-27 19:36 UTC
### Describe the Feature/Enhancement

Have a toggle in the settings to have the ability to auto delete the files of an audiobook when you have finished the book. 

### Why would this be helpful?

Sometimes I forget to purge my phone of unneeded files. This would help people who are forgetful and do not have large phone space. If this is a toggle it would also be good for people who do not want it to be auto deleted leaving the manual task still there. 

### Future Implementation (Screenshot)

In other apps, you can have this toggled in settings. 
![Screenshot_20240827-133204](https://github.com/user-attachments/assets/85a10c09-6337-4aa7-91ba-5596ba9e87fc)

### Audiobookshelf App Version

Android App - 0.9.76

### Current Implementation (Screenshot)

New user and I have another app that has this feature. So while setting up settings, I noticed this feature wasn't available.

**Comment by advplyr** [comment] 2024-08-27 19:43
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/293

**Closed by advplyr** 2024-08-27 19:43 UTC
Labels: enhancement
