### ISSUE TITLE
no possibility to remove item from a playlist

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf-app#1025] opened 2024-01-03 15:44 UTC
### Steps to reproduce

1. select a item (audiobook) 
2. add to playlist XYZ
3. open playlist XYZ
4. no way to remove item from playlist XYZ . MUST switch to WebGUI to do it there

### Expected behaviour
- additional command-item "remove"

### Actual behaviour
- miss "remove from playlist"
![IMG_20231223_083835](https://github.com/advplyr/audiobookshelf-app/assets/72630160/820b8177-7837-4398-8534-feb92c31db76)

### Environment data

Audiobookshelf Version:

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Huawei P30

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by nichwall** [comment] 2024-01-03 15:46
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/987

**Comment by advplyr** [comment] 2024-01-03 15:47
Duplicate of #987

**Closed by advplyr** 2024-01-03 15:47 UTC
Labels: bug
