### ISSUE TITLE
Playback speed no longer remembered

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf-app#610] opened 2023-02-27 08:31 UTC
### Steps to reproduce

1. Start playback
2. Set speed to 1.5×
3. Close app
4. Reopen app
    - Speed is again at 1×

### Expected behavior

I would expect ABS to remember the speed. Either in general or for each specific audiobook. My personal preference would be the former.

### Environment data

- Audiobookshelf: v2.2.15
- Android App: v0.9.62-beta
- Was not happening in v0.9.61-beta

**Comment by advplyr** [comment] 2023-02-27 15:34
Duplicate of #532

I'm pretty sure this started in 0.9.61 when I updated capacitor and its plugins.

**Closed by advplyr** 2023-02-27 15:34 UTC
Labels: bug
