### ISSUE TITLE
no internet > no login to local instance > no entry possible

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#586] opened 2023-02-17 15:10 UTC
### Steps to reproduce

1. change custom wlan gateway and dns to a different numbers as ur router (same as no internet but active wlan)
2. deactivate wlan > activate wlan (there is no internet access)
3. open audiobookshelf app > try connect (add new server) > is there no entry > create a new on > the field is not accessible and the submit button goes to "no internet"
4. is there an entry > u see name (filled) and password (empty) and the submit button goes to "no internet") >>> nothing possible ... i can enter the password but there is no submit button

### Expected behaviour
is there no internet cause of an issue with the provider, i cant paste en entry to an local instance but on a webbrowser this is possible

### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 11

Device model: sm-t 725

Stock or customized system: Stock

**Comment by advplyr** [comment] 2023-02-17 15:20
Duplicate of #566

**Closed by advplyr** 2023-02-17 15:20 UTC
Labels: bug

**Comment by galaxyfar** [comment] 2023-02-20 00:42
For those facing this issue, I have had similar issue and identified the fix. 

Internet connectivity check on Android devices is determined by constantly pinging Google's captive portal. 

Trick is to bypass this check by running the following command in ADB shell of the your Android device which is either not connected to the internet or Google's DNS is blocked at firewall level:

`settings put global captive_portal_mode 0`

Restart the device and ABS Android app will not no longer complain about "No Internet". 
Verified it myself on Android 9 and 11 device running todays [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta) release.
