### ISSUE TITLE
Make newly released podcasts list accessible in Android Auto

### ISSUE THREAD

**Issue by ahsee** [advplyr/audiobookshelf-app#1198] opened 2024-05-06 11:55 UTC
### Describe the solution you'd like
When I'm driving, I'd like to easily be able to see the list of latest episodes across all of my podcasts, and quickly select an episode. 

### Describe alternatives you've considered
The alternative is to navigate into each podcast which is cumbersome and too many screenpresses while driving. 

### Additional context
PocketCasts does this feature very well, it's the default screen on launch. It'd be great if "newly added" could be as accessible as "in progress". It could cover for recently added audiobooks as well, and it seems like there's a spare fourth menu button begging for it!

**Comment by nichwall** [comment] 2024-05-06 13:25
Are you talking about the "Latest" tab?

![Screenshot_20240506-062408.png](https://github.com/advplyr/audiobookshelf-app/assets/5686638/26dde41a-d67d-4e10-8fae-6882f58250c8)

**Comment by ahsee** [comment] 2024-05-06 21:19
> Are you talking about the "Latest" tab?

Yep! An equivalent of this for AA would be beautiful.

**Comment by advplyr** [comment] 2024-05-06 21:45
This FR was already opened it was difficult to find so I renamed it https://github.com/advplyr/audiobookshelf-app/issues/679

**Comment by advplyr** [comment] 2024-05-06 21:46
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/679

**Closed by advplyr** 2024-05-06 21:46 UTC
Labels: enhancement
