### ISSUE TITLE
[Enhancement]: Auto-Update Chapter Titles for Local Files if Different from Server Chapter Titles

### ISSUE THREAD

**Issue by colvdv** [advplyr/audiobookshelf-app#1310] opened 2024-09-03 20:45 UTC
### Describe the Feature/Enhancement

I notice that when I make changes to chapter titles on the server, any local files downloaded to the app still maintain the old chapter titles. I would like for the chapter titles on the local files to update without having to delete the local item and download it again.

### Why would this be helpful?

Currently, I have to delete the local item in the audiobookshelf app and then redownload it in order for chapter titles to update any changes.

When connected to the server and looking at the audiobook chapters, it does show the new chapter titles, but in the player itself it still shows the old chapter titles.

### Future Implementation (Screenshot)

-Described above-

### Audiobookshelf App Version

Android App - 0.9.76

### Current Implementation (Screenshot)

The player screen.

**Comment by advplyr** [comment] 2024-09-03 21:23
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/525

**Closed by advplyr** 2024-09-03 21:23 UTC
Labels: enhancement
