### ISSUE TITLE
Matching local files against server

### ISSUE THREAD

**Issue by toxic0berliner** [advplyr/audiobookshelf-app#827] opened 2023-08-01 22:11 UTC
### Steps to reproduce

1.download a book locally on phone A
2.transfert the files to phone B
3.scan the folder on phone B

### Expected behaviour
- phone B should be able to listen to the book locally and sync it's progress 

### Actual behaviour
- The book is visible but one cannot navigate inside it (.m4b) and it is not matched against any book on the same server. So no progress sync.
- file is seen as 0 second long
![Screenshot_20230802-000949_audiobookshelf](https://github.com/advplyr/audiobookshelf-app/assets/10488124/32531f5b-3cf0-43c2-a65a-234b26843040)

### Environment data

Audiobookshelf Version: 0.9.65beta server 2.3.3

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version:13

Device model: Zenfone 10 

Stock or customized system:stock

**Comment by advplyr** [comment] 2023-08-01 22:57
Duplicate of #810

**Comment by advplyr** [comment] 2023-08-01 22:58
Linking up files transferred to the device is likely not going to be supported. The scanning of local media may be removed in future releases to prevent this confusion.

**Closed by advplyr** 2023-08-01 22:57 UTC
Labels: bug
