### ISSUE TITLE
Player QOL improvement - add big skip option

### ISSUE THREAD

**Issue by samszotkowski** [advplyr/audiobookshelf-app#849] opened 2023-08-29 15:19 UTC
### Is your feature request related to a problem? Please describe.
Sometimes I only want to skip back/forward like 10 seconds when I just missed a word, and sometimes I want to skip a lot when I zoned out for 2 or 3 minutes.

### Describe the solution you'd like
Adding big skip buttons alongside a small skip would allow for two different levels of granularity.

You could make room for the extra buttons by moving the chapter skip buttons up next to where the chapter title is displayed, which seems like an intuitive place for it anyway.

Currently the app settings have "jump backwards time" and "jump forwards time", perhaps those could be combined into "small jump interval" and add a "big jump interval," or alternatively keep the two existing settings and add two more for the big jumps forward and back.

Idk much about the Android/iOS API but if buttons on external/bluetooth players need to pick a particular duration to skip forward/back they should use the small skip.

### Describe alternatives you've considered
One could simply scrub to move back larger intervals in the file, 1) this could be tricky if it's a very long chapter, and 2) "big jump" buttons could be better if you're driving or running or something and don't want to look too closely to know you went back exactly 3 minutes.

You could also just tap the small skip buttons a lot of times, but that doesn't seem ideal.

### Additional context
Before ABS I was using Smart Audiobook Player which has both these options, which I used quite a bit.

Libby on the other hand does not have this feature, but they have small skip buttons and solve the big skip problem by having a very fat, thumb-friendly scrub bar only showing about 3 minutes at a time regardless of chapter/book length (and have a separate, thin, traditional progress bar at the top, which doesn't allow scrubbing, to see where you're at in the larger scale).  Not that Libby is a masterclass in UI, but it's a rather unique attempt to solve the same problem I bring up here.  I find Smart's approach to be rather more intuitive and versatile.

Also I am on Android version 0.9.65, server 2.3.3 (docker)

Current appearance:
![Screenshot_20230829-101528](https://github.com/advplyr/audiobookshelf-app/assets/94253934/aafb348a-6739-46ff-9073-85c68a41e6ce)

Example mockup:
![Screenshot_20230829-101528-1](https://github.com/advplyr/audiobookshelf-app/assets/94253934/34a9e317-f833-4ad1-b983-a13ae257f261)

Thank you for reading, I'm loving audiobookshelf so far!

**Comment by advplyr** [comment] 2023-08-29 20:06
Duplicate of #695

**Closed by advplyr** 2023-08-29 20:06 UTC
Labels: enhancement

**Comment by advplyr** [comment] 2023-08-29 20:08
I like that graphic as well so I put a comment in the original issue with it
