### ISSUE TITLE
Allow local connection switching 

### ISSUE THREAD

**Issue by DrSeussFreak** [advplyr/audiobookshelf-app#356] opened 2022-09-02 00:27 UTC
### Is your feature request related to a problem?
Feature request, allow downloading from local network based on wifi network name.

### Describe the solution you'd like
Allow for network monitoring, monitor wifi name, switch to local address

**Comment by mefistos** [comment] 2022-10-10 23:19
This is great idea, the problem I am having is that when I download books, because I use sub domain to access audiobookshelf. The download speed is limited by my upload speed. But if there was option for the app to switch to local network it would download via Lan which is much faster.


I like how nzb360 has this option in settings:
![Screenshot_20221011_001630](https://user-images.githubusercontent.com/3752251/194966200-db22c01d-89e5-45a6-a901-a64c28a30407.jpg)

**Comment by advplyr** [comment] 2023-02-12 19:00
Related and possible dupe of #209

**Comment by advplyr** [comment] 2023-06-11 20:44
Duplicate of #209

**Closed by advplyr** 2023-06-11 20:44 UTC
Labels: enhancement
