### ISSUE TITLE
[Enhancement]: Android WearOS compatibility

### ISSUE THREAD

**Issue by goose-ws** [advplyr/audiobookshelf-app#1321] opened 2024-09-13 19:31 UTC
### Describe the Feature/Enhancement

An Android APK that is compatible with WearOS

### Why would this be helpful?

While the Android app is very well polished, I have occasional use cases (going on a jog) where I'd prefer to leave my phone behind and just use my smart watch and bluetooth earbuds. Having Audio Bookshelf on my smart watch would be a nice way to bring my library with me, without the phone. While storage could be an issue for some people, I would sat that LTE devices which can stream instead of using local storage are. Strong counter argument.

### Future Implementation (Screenshot)

Future implementation would be best achieved with WearOS compatibility, which a quick Google indicates would cover the majority of Android compatible smart watches.

### Audiobookshelf App Version

Android App - 0.9.76

**Comment by advplyr** [comment] 2024-09-13 19:33
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/676

**Closed by advplyr** 2024-09-13 19:33 UTC
Labels: enhancement

**Comment by goose-ws** [comment] 2024-09-13 19:55
My mistake @advplyr. I searched for "WearOS" with no results before creating this. Didn't think to try with a space in between.

**Comment by advplyr** [comment] 2024-09-13 20:01
No prob!
