### ISSUE TITLE
Automatic Download of episodes from server to smartphone when the smartphone is connected to wifi

### ISSUE THREAD

**Issue by update-freak** [advplyr/audiobookshelf-app#680] opened 2023-04-18 20:16 UTC
### Is your feature request related to a problem? Please describe.
The problem is that when I'm hiking I did not have access to internet all the time and also want to listen  to the podcasts episodes.
Therefore it would be nice to have an automatic sync of the files from server to smartphone when I'm at home (with wifi).
-> possibility to download the unlistened episodes to smartphone (download directly or from server)

### Describe the solution you'd like
Automatic synchronisation of the files from the server for a unlistened playlist

### Describe alternatives you've considered
Manually download all the files before (-> an automatic option would be nice) when I'm at home.

**Comment by advplyr** [comment] 2023-04-18 22:58
Duplicate of #613

**Comment by advplyr** [comment] 2023-04-18 22:59
Related #247

**Closed by advplyr** 2023-04-18 22:58 UTC
Labels: enhancement

**Comment by socialsciencesoftware** [comment] 2023-04-19 13:47
Bump
