### ISSUE TITLE
10 sec rewind

### ISSUE THREAD

**Issue by mediacowboy** [advplyr/audiobookshelf-app#143] opened 2022-04-24 18:10 UTC
### Steps to reproduce

1. Open App
2. Start playing book
3. Stop playing book
4. Wait awhile
5. Start playing book

### Expected behavior
- After a while of not playing, it should rewind 10 secs to allow the listener to remember where they are

### Actual behavior
- Plays where left off

### Environment data

Audiobookshelf Version: 0.9.41-beta

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Samsung S10+

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by DDriggs00** [comment] 2022-04-25 19:03
This is a feature request, not a bug report, and I would recommend a dynamic time based on how long it has been since pausing.

**Comment by mediacowboy** [comment] 2022-04-25 19:29
I labeled it as a bug as it was there before this weekends update. When the media player got reworked it did not get added back.

**Comment by hmlendea** [comment] 2022-04-28 07:29
You could also make it so that if you paused near the beginning of a chapter (e.g. within the first minute for example), it would just start that chapter from scratch.

**Comment by advplyr** [comment] 2022-04-30 10:54
This is fixed in [v0.9.43-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.43-beta)

If pause is less than 3 seconds there will be no rewind.
If pause is less than 5 minutes it will skip back 10s.
If pause is less than 30 minutes it will skip back 20s
anything over 30 min pause will skip back 30s.

**Closed by advplyr** 2022-04-30 10:54 UTC
Labels: bug
