### ISSUE TITLE
Local file library view

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf-app#378] opened 2022-09-12 13:35 UTC
### Is your feature request related to a problem? Please describe.
I'd like to be able to view local files in the library view. Strikes me as an easy win, just use the filters or create a new button on the top. 

### Describe the solution you'd like
The ability to display only linked local media on the library view. If I currently try to see this, I can only see it on the front page (which has a horizontal scroll - I think this is also limited to x number of books), or in the local media section. 

### Describe alternatives you've considered
Unless I'm missing something, this isn't a feature that is currently available.

**Comment by ronaldheft** [comment] 2022-09-13 00:59
If you open the "hamburger menu" on the top right, on both the iOS and Android version, you should have the ability to browse all downloaded books and their files.

**Comment by advplyr** [comment] 2022-09-13 21:30
This is planned just haven't gotten to it

**Comment by jt196** [comment] 2022-09-13 21:46
> If you open the "hamburger menu" on the top right, on both the iOS and Android version, you should have the ability to browse all downloaded books and their files.

As mentioned in the Local Media section. Made sense to have it as a filter in the main library as most of the interaction (thus familiarityl and GUI design work goes into that section.

**Comment by advplyr** [comment] 2023-02-12 18:51
Duplicate of #542

**Closed by advplyr** 2023-02-12 18:51 UTC
Labels: enhancement
