### ISSUE TITLE
Automatically delete podcasts from server when finished or easier deletion from file list 

### ISSUE THREAD

**Issue by darthrater78** [advplyr/audiobookshelf-app#737] opened 2023-06-09 12:59 UTC
An option to auto delete on finish or an easier way to delete files without having to click into them, then click the menu, delete, then go into another menu would be great.  Perhaps a long hold could bring up a delete modal.

**Comment by advplyr** [comment] 2023-06-09 20:17
Duplicate of #293

**Closed by advplyr** 2023-06-09 20:17 UTC
Labels: enhancement
