### ISSUE TITLE
[Feature request] (Android/iOS) Option to automatically delete local copies of audiobooks when they finished

### ISSUE THREAD

**Issue by b3nd1k** [advplyr/audiobookshelf-app#1031] opened 2024-01-04 14:17 UTC
In order to save mobile data while I am on the go, I like to download the audiobooks to my iPhone. However, when I am done listening to them. Either determined by the fact that I finish them or mak them as read manually, I would like for there to be an option to have the audiobook automatically deleted from the device. That way, I don't have to manually do it.

**Comment by kebbe** [comment] 2024-01-04 18:35
Good idea, maybe with an option to delay the auto delete for a specific time. I mainly listen to podcasts when I go to sleep or when I'm on the commute, so the book would get deleted if I fall asleep when it's finished so I can't listen to the rest I have missed on my way to work.

**Comment by nichwall** [comment] 2024-01-04 18:36
Duplicate of #293

**Comment by advplyr** [comment] 2024-01-04 18:51
Duplicate of #293

**Closed by advplyr** 2024-01-04 18:51 UTC
Labels: enhancement
