### ISSUE TITLE
[iOS] playback speed lost when closing the player or app

### ISSUE THREAD

**Issue by brandonocasey** [advplyr/audiobookshelf-app#799] opened 2023-07-21 18:23 UTC
### Steps to reproduce

1. Start audiobook plackback and set a playback speed
2. continue playback
3. close the app
4. Open the app and start the book again, note that the playback speed is lost

### Expected behaviour
- playback speed should be maintained between app sessions. Possibly even synced between the app and web?

### Actual behaviour
- playback speed is lost

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [x] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 0.9.65-beta

iPhone model: Iphone 14 Pro Max

**Comment by advplyr** [comment] 2023-07-21 22:13
Is this for a downloaded book or streaming or both?

**Comment by brandonocasey** [comment] 2023-07-23 22:17
I think it happens for both after testing.

**Comment by holazit** [comment] 2023-07-27 06:31
I have this same annoying problem too for a few days, I didn't have this issue with the previous version of Audiobookshelf.

**Comment by Drudoo** [comment] 2023-07-29 07:14
Same issue here (on iOS)

**Comment by benonymity** [comment] 2023-11-12 18:18
I think this has been solved and was a duplicate of #543

**Comment by advplyr** [comment] 2023-11-12 20:03
Is this still an issue on v0.9.66?

**Closed** 2023-11-18 18:01 UTC
Labels: bug, waiting, unable to reproduce
