### ISSUE TITLE
Add to currently playing queue

### ISSUE THREAD

**Issue by lhassell** [advplyr/audiobookshelf-app#687] opened 2023-04-26 15:12 UTC
### Is your feature request related to a problem? Please describe.

In most podcast apps, you can choose another podcast / episode and have it play after the currently playing stream. There does not seem to be a "playlist" that reflects what is currently playing in the app.

### Describe the solution you'd like

Simply put, have a "now playing" playlist, and give users the ability to choose a file (episode/new book/ whatever) and add it to play next in sequence. You should be able to build a list of media items and have them all play in sequence without having to choose to play the next item.

### Describe alternatives you've considered

I have not found another method, other than manually playing items one at a time.

**Comment by advplyr** [comment] 2023-05-21 16:58
Duplicate of #416

I'm merging the queue-related issues into one issue

**Closed by advplyr** 2023-05-21 16:58 UTC
Labels: enhancement
