### ISSUE TITLE
[Bug]:  0.9.77-beta - download doesn't background or resume

### ISSUE THREAD

**Issue by danielb2** [advplyr/audiobookshelf-app#1367] opened 2024-11-07 14:40 UTC
### What was the Problem?

when trying to download a book if I switch to another window the download stops. If I switch back it just says it's downloading but doesn't resume.

(Side note with the beta is that it also can't find current downloads )

### Steps to Reproduce the Issue

1. Download book
2. Switch to another app

### What was Expected?

Downloads should continue in the background 

### Phone Model

Pixel Pro 7

### Phone OS

Android 15

### Audiobookshelf App Version

Android App - 0.9.76

### Installation Source

Google Play Store

### Additional Notes

0.9.77-beta

**Comment by advplyr** [comment] 2024-11-07 15:35
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/956

**Closed by advplyr** 2024-11-07 15:35 UTC
Labels: bug

**Comment by danielb2** [comment] 2024-11-07 15:38
I filed this as a bug because I had no issues downloading before.

**Comment by advplyr** [comment] 2024-11-07 16:07
It's the same issue as far as I can tell?

**Comment by danielb2** [comment] 2024-11-07 16:31
The above issue is a year old though. I've been downloading books regularly until this latest beta without issues. This beta I had to delete the app (clear storage) and redownload all my books, and switching away from the app would stop the download. I had to set my display to timeout after 30 minutes and leave the app running so the book could be downloaded.

I've never had to do that before

**Comment by advplyr** [comment] 2024-11-07 16:40
Nothing changed with downloading in the app so it has to do with someone with the device. Most likely how it handles keeping background services alive. I've never had it happen so it only happens to some. Whatever it is it is the same issue described in #956

**Comment by advplyr** [comment] 2024-11-07 16:47
Most likely one of the many permission issues that haven't been figured out yet.

**Comment by danielb2** [comment] 2024-11-07 16:54
could it be because of the early access? trying to leave the program to see if the previous version has the issues

**Comment by danielb2** [comment] 2024-11-07 16:58
I can't seem to leave the early access :(

**Comment by danielb2** [comment] 2024-11-07 17:04
@advplyr I downloaded the previous beta 0.9.76 and followed the steps to reproduce, and I don't experience any problems downloading

**Comment by danielb2** [comment] 2024-11-07 17:08
I rolled back to 0.9.76 and I still have problems downloading. Maybe I'm delusional so I guess we can leave this closed
