### ISSUE TITLE
[Enhancement] : add "A-Z"-scrollbar to several lists

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf-app#1096] opened 2024-02-22 07:32 UTC
### Is your feature request related to a problem? Please describe.
If there is a long list of items ( 3700 books, 300 series, 1000 authors) it hard to scroll by move the screen up

### Describe the solution you'd like
it would be much easier and faster to have a "A-Z"-scrollbar lke you find in "contacts:
![image](https://github.com/advplyr/audiobookshelf-app/assets/72630160/645a7f13-d1b9-44a6-8f14-f5e961daa334)

please add the "A-Z-scrollbar to:
 - Books
 - Series
 - Authors
 - Narrators
 - Metadata
 
![image_authors](https://github.com/advplyr/audiobookshelf-app/assets/72630160/98a04f5d-b809-44fa-b092-07e53836a810)

**Comment by nichwall** [comment] 2024-02-22 13:36
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/544

**Closed** 2024-02-22 15:00 UTC
Labels: enhancement
