### ISSUE TITLE
[Bug]: Downloaded book in Android client - mobile data still being used extensively while listening

### ISSUE THREAD

**Issue by Kybeer** [advplyr/audiobookshelf-app#276] opened 2022-07-07 14:11 UTC
### Describe the issue

Hello,

First, thanks for the continuous improvement on Audiobookshelf!

I have Audiobookshelf server v. 2.0.23 running in a container (Podman). I'm using it exclusively with Android client 0.9.49-beta. 

I always keep the audiobook I currently listen to download:ed to the phone. 

It means the book is listed in the "local" on the main screen of the app. And when playing the book, it says "local" in green letters in the top. 

The problem I have is the app is using a lof of mobile data traffic, despite the book being downloaded. We're talking several MBs over 5-10 mintues of listening. 100:s of MB with extensive listening. It's depending on the book size I assume.

In other words, it's like the book is not being played locally, but over the internet/mobile data. 

This is not happening at home, when I'm on my local network (phone on wifi). It's happening when I'm out of home. 
I'm reaching my Audiobookshelf server over VPN when not at home. 

The server log also show local for my users' playback (as opposed to direct play):

![image](https://user-images.githubusercontent.com/57593336/177795810-b448aab0-389e-4c67-9a7d-131d235ed90e.png)

### Steps to reproduce the issue

1. Download the book in the Android app.
2. Leave my home or disconnect from wifi (so I loose connectivity to the server)
3. Connect to my VPN (so I have connectivity to the server)
4. Listen to the book
5. Observe "mobile data usage" for Audiobookshelf app in Android. 

### Audiobookshelf version

2.0.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2022-07-08 12:59
This is a duplicate of https://github.com/advplyr/audiobookshelf-app/issues/238

I spent yesterday evening testing this thoroughly and found some things so I'm going to post an update in that thread. I appreciate your thoroughness, it will be helpful to have your feedback and testing for the next release.

**Closed by advplyr** 2022-07-08 12:59 UTC
Labels: bug
