### ISSUE TITLE
Sleep timer counts down relative to playback speed.

### ISSUE THREAD

**Issue by ChiefMedicalOfficer** [advplyr/audiobookshelf-app#86] opened 2022-01-16 22:29 UTC
### Steps to reproduce

1. Increase playback speed. 
2. Set sleep timer. 
3.

### Expected behaviour
- Tell us what should happen

Sleep timer should countdown in realtime. 

### Actual behaviour
- Tell us what happens

Sleep timer counts down relative to playback speed. 1.3x will cause 1 minute of the timer to complete in 40 seconds. 1.5x = 30 seconds. 

### Environment data

Audiobookshelf Version: 1.6.57

- [ 0.9.37-beta] Android App?

#### Android Issue
Android version: 8

Device model: Galaxy S7

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by jcrmit** [comment] 2022-01-19 06:35
Hey @ChiefMedicalOfficer - I cannot reproduce this. I usually listen at 1.3x - but for me the countdown sleep timer counts in real time - whether I set the playback speed first or after the sleep timer.

**Comment by ChiefMedicalOfficer** [comment] 2022-01-19 07:59
Thanks for trying. I used a stopwatch and it definitely counted down at those speeds. 

I'll try again.

**Comment by ChiefMedicalOfficer** [comment] 2022-01-19 08:10
Tried again.

5 minute timer, 1.5x speed. First minute completes in 30 seconds.

I've just noticed too that when I set the timer to 1 minute it'll jump to a value above 60 seconds.

You know how on an audiobook player the actual book time will count down like -1.20.35 -1.20.33 if the book speed has been increased (not every second is counted) the sleep timer is doing the same thing.

**Comment by jcrmit** [comment] 2022-01-19 09:52
@ChiefMedicalOfficer - I take it back it was more pronounced when I put it up to 1.5x - but is there at 1.3x. Funny thing is - i don't mind it. That way if I set a sleep timer for 15min and fall asleep - it will stop after 15min of book time, but 22.5mins (@1.5x) 😂.

**Comment by ChiefMedicalOfficer** [comment] 2022-01-19 19:40
It's certainly not an experience ruiner, that's for sure.

**Comment by advplyr** [comment] 2022-02-04 18:46
This is hopefully fixed in `v0.9.40-beta`

**Comment by ChiefMedicalOfficer** [comment] 2022-02-04 18:52
Thanks again mate. Great work.

**Comment by ChiefMedicalOfficer** [comment] 2022-02-08 08:18
Seems to be working fine.

Thanks again.

**Comment by advplyr** [comment] 2022-02-08 14:20
Awesome, thanks for confirming.

**Closed by advplyr** 2022-02-08 14:20 UTC
Labels: bug
