### ISSUE TITLE
The ability to delete podcast episodes after a selectable amount of time.

### ISSUE THREAD

**Issue by FuzzyWereBeast** [advplyr/audiobookshelf-app#767] opened 2023-07-01 14:24 UTC
### Is your feature request related to a problem? Please describe.

Currently, podcasts have the ability to keep so many episodes.  However, it seems that only 1 episode is deleted when new ones are added regardless of how many are added.  This causes the amount of saved episodes to increase and need to be manually pruned.

### Describe the solution you'd like

I would like to have the ability to delete podcast episodes after a period of time that can be set.

### Describe alternatives you've considered

I have attempted to adjust the frequency of download times, but this doesn't solve the problem if the feed drops multiple episodes at the same time.

**Comment by advplyr** [comment] 2023-07-01 17:23
Duplicate of #175

**Closed by advplyr** 2023-07-01 17:23 UTC
Labels: enhancement
