### ISSUE TITLE
iOS book starts playing when app opens

### ISSUE THREAD

**Issue by mdeeter** [advplyr/audiobookshelf-app#973] opened 2023-12-07 14:03 UTC
### Steps to reproduce

1. Listen to book (it's one I've downloaded)
2. Pause book (typically done from lock screen, not sure if it matters)
3. Hours later, open the app
4. The last book will resume playing before the UI is finished loading 

### Expected behaviour
- Preferred behavior:  The book doesn't automatically start playing (or if some users want it to, make it configurable in the app settings to 'autoplay when opened'.
- At the very least, I'd prefer if the book didn't start playing before the UI was loaded... it's playing before the player is even visible... so I have to wait for several seconds for the player UI to show up in order to pause the book.

### Actual behaviour
- Tell us what happens

### Environment data

Audiobookshelf Version: 2.5.0

- [ ] Android App?
- [x] iOS App? - version 0.9.68-beta

#### iOS Issue
iOS Version: 17.1.2

iPhone model: iPhone 12 Pro

**Comment by advplyr** [comment] 2023-12-08 22:24
I'm not able to reproduce this. What version of the iOS app are you using?

Is this happening every time for you? Are you leaving the app open in the background or closing it?

**Comment by mdeeter** [comment] 2023-12-09 00:53
app version `0.9.68-beta` (updated in og description)

I typically always switch apps (leaving apps in the bg)... until something doesn't seem to be working, then I'll hard-close the app and re-open it.

It's happened several times in the past week, but it doesn't seem to happen all of the time... often enough to be a little annoying :)

**Comment by mdeeter** [comment] 2023-12-09 10:31
Just happened again...

I put in my airpods... Unlocked my phone... Opened the app...

The book started playing immediately... Here's the ui

![image](https://github.com/advplyr/audiobookshelf-app/assets/136902/c1e9618b-ac39-4e6d-acdc-6a2caa622d97)

Then I try tapping on the book... But it won't open until the ui finishes loading...
![image](https://github.com/advplyr/audiobookshelf-app/assets/136902/f6d65fb0-63d1-4d08-b5b5-6ff153c5a4af)

Then the book opens (it's still playing) and there's no player UI showing...
![image](https://github.com/advplyr/audiobookshelf-app/assets/136902/68cd43e2-6656-4a3c-a4a9-99c6f2498ac7)

I click play button and it pauses the book and it shows the player UI at the bottom...
![image](https://github.com/advplyr/audiobookshelf-app/assets/136902/bf5dda1e-b9e1-4bde-8757-3e28f63bccfb)

**Comment by KaiStarkk** [comment] 2023-12-18 01:02
It’s a weird one. I get the same issue. Doesn’t really bother me but still, curious.

**Comment by dathbe** [comment] 2023-12-20 16:41
I experienced this same issue.  Here are some additional details in case it is helpful in recreating:

I was listening to a book on my iPhone in the car via Bluetooth.
I then switched the car to play a different audio source (though I don't think I explicitly paused Audiobookshelf)
I then was listening on my phone to the same book via headphones.
I then paused the book in my phone.
I then listened to the book on my iPad via headphones.
I paused the iPad.
Both devices were put down for several hours, but the app was not killed on either device.
When I picked up the phone several hours later, this issue popped up.

The immediately-start-playing issue doesn't bother me too much (I would hate to have a fix for this prevent being able to get in and out of a car and continue listening without a bunch of button presses), but I experienced a secondary issue where the controls were not visible while the book was playing.  Possibly the same as OP's "before the UI is finished loading."

**Comment by RealWalts** [comment] 2023-12-22 21:27
I also have the same issue, it used to happen before but seems to got fixed. But now it's back.

**Comment by livineasy629** [comment] 2023-12-27 02:40
This happens whether the book is downloaded or streaming. The streaming one is way more confusing because it starts playing the audio even before the server connects. 

When I go to the book that's playing it shows as if it isn't playing.

This is also happening on the macOS client which seems to be the iOS app running on Mac. It randomly starts playing there and I can't get the play controls to come up so I have to quit the app. 

I just updated the server app so I'll test it this week and report back.

**Comment by livineasy629** [comment] 2024-01-03 22:09
Still present on the latest server version and updated iOS app. It will even continue playing a file that isn't downloaded while the server is disconnected.

**Comment by dathbe** [comment] 2024-01-04 04:38
> It will even continue playing a file that isn't downloaded while the server is disconnected.

This isn't too surprising.  Presumably the app caches some duration while it's streaming.  Would be interesting to know how long it will play when this happens.

**Comment by GiladHi** [comment] 2024-02-05 09:45
I also have the same issue with the latest version...

**Comment by mdeeter** [comment] 2024-02-06 22:35
> > It will even continue playing a file that isn't downloaded while the server is disconnected.
> 
> This isn't too surprising. Presumably the app caches some duration while it's streaming. Would be interesting to know how long it will play when this happens.

In a recent play, I just left the house and left my wifi, I opened my app in the car and got about 3-5 min away when it stopped and I noticed it wasn't connected to my server.  I killed the app and reconnected and it played fine.

I agree that it seems that the app is automatically playing from the cache.  I think I'd prefer it if it wouldn't autoplay when I open the app.

**Comment by advplyr** [comment] 2024-02-08 00:01
Is anyone able to reproduce this consistently yet? I'm trying to reproduce it again but unsuccessful so far.

By reproduce consistently I mean you are able to cause this to happen with a specific set of steps that you can share.

I've taken a guess at what could be happening while reading through the docs but I can't be sure until I can reproduce it. https://developer.apple.com/documentation/avfaudio/avaudiosession/interruptionreason/appwassuspended

**Comment by advplyr** [comment] 2024-02-11 23:15
Let me know if this issue persists in 0.9.72-beta

**Comment by mdeeter** [comment] 2024-02-11 23:20
I'll test it asap.  I made attempts to trigger this intentionally (to try to gauge a cause/effect) for about 20 min yesterday and couldn't get it to happen.  Then it happened (seemingly randomly) when I opened the app last night.... and then again just now when I opened up the app to check what version I had installed (0.9.71).  I'll update again next week if I do or don't see it again (after updating).

**Comment by mdeeter** [comment] 2024-02-15 23:09
So this is continuing to happen to me in the latest version (0.9.72).  Idk if this is related, but I also experienced my current book starting to play at 1-2 AM seemingly on it's own.

This is really weird.    I wonder if there's some logging that could be enabled (perhaps that I could opt-into) that could cache interactions that I could then send you (or upload here) to help triage this issue.

**Comment by dathbe** [comment] 2024-02-15 23:29
If we're right that this is a caching issue, the server may not even know.  Thus, logs may not be entirely useful.

**Comment by GiladHi** [comment] 2024-02-15 23:32
Still happened with the latest build, even with downloaded local files.

**Comment by advplyr** [comment] 2024-02-15 23:55
The best way to figure this out is to find out how to reproduce it

**Comment by dathbe** [comment] 2024-02-16 16:27
I experienced an extreme example of this last night where a book started playing randomly at midnight.  The phone was otherwise sitting peacefully on my nightstand.  When I opened the app to stop it, I was greeted with this:
![2024-02-15 23-40-38 Darin_Phone 1518](https://github.com/advplyr/audiobookshelf-app/assets/14321825/efe68813-e710-412c-af8d-872a411be01b)
There was at least one, if not 2 more copies of the error message on the screen when I first opened it, and they were disappearing quickly.  I didn't have my full senses about me, but I don't believe I had the option to stop the playback from within the app and had to force quit the app to get playback to stop (i.e., the playback controls were missing).  

Steps to repeat:

1. Open app from force-closed state.
2. Play book for about 2-5 minutes
3. Pause book (I think i used the in-app controls for this, but it's possible I used the lock screen widget)
4. About 8 hours later, playback randomly restarted

I had not touched the app since pausing.

**Comment by RealWalts** [comment] 2024-02-16 16:31
> I experienced an extreme example of this last night where a book started playing randomly at midnight. The phone was otherwise sitting peacefully on my nightstand. When I opened the app to stop it, I was greeted with this:
> 
> There was at least one, if not 2 more copies of the error message on the screen when I first opened it, and they were disappearing quickly. I didn't have my full senses about me, but I don't believe I had the option to stop the playback from within the app and had to force quit the app to get playback to stop (i.e., the playback controls were missing).
> 
> Steps to repeat:
> 
> 1. Open app from force-closed state.
> 2. Play book for about 2-5 minutes
> 3. Pause book (I think i used the in-app controls for this, but it's possible I used the lock screen widget)
> 4. About 8 hours later, playback randomly restarted
> 
> I had not touched the app since pausing.

It also started playing at night here as well randomly. It had been a few hours since I last used it.

**Comment by advplyr** [comment] 2024-02-16 16:34
I know it was mentioned that this also happens while streaming but the screenshots I've seen so far have all been downloaded. Is it possible the streaming is a slightly different situation happening that is getting conflated with this one? Because that happens often and makes it difficult to narrow down the issue.

**Comment by dathbe** [comment] 2024-02-16 16:36
This book was not downloaded -- at least not manually.

**Comment by mdeeter** [comment] 2024-02-16 16:36
I'm currently on book 16 of Dresden Files... I've been streaming this series since book 10 and still seeing this issue... so I don't think it's specific to downloaded vs streaming.

**Comment by dathbe** [comment] 2024-02-18 01:26
I'm surprised you haven't been able to reproduce this.  I just tried it again (play, pause, don't force close, wait many hours, open app) and it did it again.  I have a habit of force closing apps, so I think  I'm 3 for 3 when leaving it in the background and having it play when re-opening.

**Comment by nigiriemoji** [comment] 2024-02-23 21:51
I have this issue too on latest ios and latest ABS ios app version

It seems like after the ABS app is in the background for a while, it forgets its playback state even though it's for sure paused. When opening the app it resumes to become playing BUT WITHOUT the miniplayer coming up

**Comment by nichwall** [comment] 2024-02-23 22:14
> I have this issue too on latest ios and latest ABS ios app version

Would you mind adding the version numbers instead of just `latest`, since that can help with future debugging when reviewing old issues? Assuming that's 0.9.72

**Comment by nigiriemoji** [comment] 2024-02-23 22:15
> > I have this issue too on latest ios and latest ABS ios app version
> 
> Would you mind adding the version numbers instead of just `latest`, since that can help with future debugging when reviewing old issues? Assuming that's 0.9.72

done, thank you. any logs i can provide to help?

**Comment by nigiriemoji** [comment] 2024-02-27 03:47
Here is a video of the exact bug that I’m experiencing.

I was playing an audiobook a few hours ago. The ABS app stays in background apps for iOS 17.3.1, then when I open up the app the play continues to resume 


https://github.com/advplyr/audiobookshelf-app/assets/53108354/d158c905-84df-4775-9860-82a7f8c83927

**Comment by dathbe** [comment] 2024-02-27 13:26
That’s effectively identical to what I experience. I’m using an iPhone 13 mini in case that’s making a difference.

**Comment by mdeeter** [comment] 2024-02-27 14:11
yes, that's the exact same UX I have as well

**Comment by advplyr** [comment] 2024-02-27 14:27
@nigiriemoji Are you able to reproduce this consistently? To where you can give me an exact set of steps to reproduce it on my end?

**Comment by nigiriemoji** [comment] 2024-02-28 07:27
Adding another recording of the bug. Haven’t used ABS app in several hours, feels like something to do with it being in the background for so long that it forgets its playback state?

https://github.com/advplyr/audiobookshelf-app/assets/53108354/8b44bc1c-1b10-43d2-a51c-67ba8a3ab275

**Comment by dathbe** [comment] 2024-02-28 15:03
I think the timing thing is important. I tried after about an hour and the app opened fine.  But after 12 the bug occurred. Also, I left the app on the book screen (did not back out to the bookshelf) when I switched apps. That may or may not matter. So just pause and swipe up to switch apps, don’t press back to leave the book page.

**Comment by advplyr** [comment] 2024-02-28 17:44
> > @nigiriemoji Are you able to reproduce this consistently? To where you can give me an exact set of steps to reproduce it on my end?
> 
> @advplyr
> 
> I can sort of consistently reproduce it with many minutes/hours between each playback session. I just don’t know how many minutes to wait, but taking a night’s sleep usually is long enough. Just happened to me right now this morning.
> 
> 1. Open ABS app on iOS
> 2. Play any audiobook
> 3. Eventually manually pause it or set a sleep timer (I experienced bug both ways)
> 4. Leave ABS app by swiping up to Home Screen, browse other apps, whatever. But ensure that the ABS app remains in the background but not fully closed (as in DO NOT swipe the app away to kill/terminate it in the app switcher screen)
> 5. Don’t use ABS app for an hour or more (overnight sleep is long enough)
> 6. Open up ABS app
> 7. Experience automatic playback bug

I tested this with a book streaming and let it play for about 10 minutes in the background with the screen off. I paused from the lock screen and just left the device for a little over 12 hours. I just unlocked the device and opened the app (that was still open in the background) and the bug did not occur.

I'm still on iOS 16.x, haven't updated to 17 yet. It seems everyone here is on 17 so maybe this bug started on newer iOS versions. Is anyone still on iOS 16 that is having this issue?

**Comment by dathbe** [comment] 2024-02-28 17:51
I don't have any devices on ios 16 anymore.  But try pausing from within the app and then switching apps.

**Comment by nigiriemoji** [comment] 2024-02-28 22:19
> > > @nigiriemoji Are you able to reproduce this consistently? To where you can give me an exact set of steps to reproduce it on my end?
> > 
> > 
> 
> I tested this with a book streaming and let it play for about 10 minutes in the background with the screen off. I paused from the lock screen and just left the device for a little over 12 hours. I just unlocked the device and opened the app (that was still open in the background) and the bug did not occur.
> 
> I'm still on iOS 16.x, haven't updated to 17 yet. It seems everyone here is on 17 so maybe this bug started on newer iOS versions. Is anyone still on iOS 16 that is having this issue?

Also on iOS 17 sorry. I typically pause directly within the app, though unsure what is the last screen/menu of the app that causes the bug

Any logs that I could provide to you the next time I encounter this bug?

**Comment by advplyr** [comment] 2024-02-29 19:10
I tested pausing within the app and left it in the bg asleep for a day. Still not able to reproduce that on iOS 16.

I don't know about any logs that can provided

**Comment by mdeeter** [comment] 2024-02-29 19:12
this still happens to me daily... any idea when you might be able to test on iOS 17?

**Comment by advplyr** [comment] 2024-02-29 19:35
I have an iPhone 10 that is only used for testing and iOS 17 isn't supported for it. I will probably get a new one since these types of things are why I opened up donations.

**Comment by nigiriemoji** [comment] 2024-03-05 23:35
This issue is still occurring for v0.9.73-beta iOS that came out in the last 48 hours.

**Comment by dathbe** [comment] 2024-03-19 15:46
I had a weird situation this weekend where this bug popped up while I was in the middle of listening.  I was running around, so I don't have the exact steps to reproduce, but generally I was listening, and then at some point while the audio was playing I opened the app to find that the controls had disappeared.  When I clicked "stream" like I normally do when this bug pops up, the playback went back a couple minutes and started playing again with the control.  Very odd.

**Comment by mdeeter** [comment] 2024-03-19 16:32
I continue to have this bug on a daily basis.  I'm assuming it won't get resolved until the devs have time/chance to test against iOS 17.

**Comment by advplyr** [comment] 2024-03-19 16:51
Yeah I still have to buy a newer iphone

**Comment by dathbe** [comment] 2024-03-19 17:32
Completely understand.  I just wanted to add a new data point in case it's helpful in finding the issue.

**Comment by advplyr** [comment] 2024-03-19 17:43
For sure, I appreciate the reports since we haven't narrowed down how exactly to reproduce this.

**Comment by mdeeter** [comment] 2024-04-10 07:53
![image](https://github.com/advplyr/audiobookshelf-app/assets/136902/d90db066-1559-45d7-b69f-7d3ded6c4e41)

...More random playing in the middle of the night.

Same as mentioned above... Except that I didn't have to force-cc lose the app.  I've been steaming this book... And paused the book around 830pm by removing my airpods. Was awoken to the app playing on its own at 230am.

**Comment by advplyr** [comment] 2024-05-22 15:32
Can anyone confirm if this issue still exists in v0.9.74-beta?

**Comment by dathbe** [comment] 2024-05-22 15:42
I haven't had it happen on the latest update, but I also have gotten into the habit of force-closing the app when I'm done.  Let me see if I can get it to happen again.

**Comment by nichwall** [comment] 2024-05-22 15:44
May have been inadvertently fixed by https://github.com/advplyr/audiobookshelf-app/pull/1179?

**Comment by dathbe** [comment] 2024-05-22 22:30
I'm going off a small sample size (1), but I did not get this error with the latest version after trying what had caused it before.  So it's entirely possible 0.9.74 has a fix.  Anyone else?

**Comment by nigiriemoji** [comment] 2024-05-22 22:32
+1 seems to be fixed after three sessions

usually the bug was play book, sleep timer activates, come back to app ~1 hour later and auto play without input being the bug

no longer occurs

**Comment by advplyr** [comment] 2024-05-23 16:22
Awesome thanks for testing and thanks to @indiefan for tracking that one down

**Closed by advplyr** 2024-05-23 16:22 UTC
Labels: bug, waiting, unable to reproduce

**Comment by benonymity** [comment] 2024-05-25 12:49
I managed to get the playback error once yesterday in a whole day of listening, but far more rarely than before. Perhaps an unrelated issue, since I didn't have any unexpected resumes

**Comment by bloodscript** [comment] 2025-01-22 14:53
Can anyone still reproduce this issue with latest 2.18.1 server and 0.9.78 client? @benonymity @mdeeter?

**Comment by mdeeter** [comment] 2025-01-22 15:24
I haven't seen this occur in quite a long time... unsure if it's from an iOS update  (I'm on 18.2.1) or ABS update (I'm on 0.9.78).
