### ISSUE TITLE
[iOS] Seeking not possible if audiobook was finished

### ISSUE THREAD

**Issue by p-rintz** [advplyr/audiobookshelf-app#1023] opened 2024-01-02 19:43 UTC
### Steps to reproduce

1. Play audiobook to end
2. Do not close the app
3. Try to seek (or jump to a chapter/audiofile) anywhere in the audiobook
4. Play until next chapter or audiofile
5. Audiobook either stops (most often) or jumps to any (seemingly) random chapter/file in the audiobook

### Expected behaviour
- Audiobook should simply continue from where it should be

### Actual behaviour
- Audiobook either stops or jumps to any (seemingly) random chapter/file in the audiobook
- This can be "fixed" if you close the app and then discard the progress and then jump to any chapter/audiofile.

### Environment data

Audiobookshelf Version: 2.7.1 (but its been an issue for a while)

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 0.9.71 (28)

iPhone model: iPhone 12

**Comment by advplyr** [comment] 2024-01-02 20:00
Duplicate of #452

**Closed by advplyr** 2024-01-02 20:00 UTC
Labels: bug

**Comment by p-rintz** [comment] 2024-01-02 20:02
Im not downloading the audiobook though.

Just streaming it. 

Is it still the same issue?

**Comment by advplyr** [comment] 2024-01-02 20:09
Yeah it's the same, I just updated the title of the issue, thanks!
