### ISSUE TITLE
Rename Series

### ISSUE THREAD

**Issue by MikeBishop** [advplyr/audiobookshelf-app#665] opened 2023-04-10 14:31 UTC
### Is your feature request related to a problem? Please describe.
When arranging series, the only way to change the name of a series is to mass remove the old series from the books, mass add the new series to the books, then go book-by-book re-assigning the sequence.

### Describe the solution you'd like
Ability to rename a series in place without losing the book sequence within it.

**Comment by advplyr** [comment] 2023-04-10 14:42
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1604

**Closed by advplyr** 2023-04-10 14:42 UTC
Labels: enhancement
