### ISSUE TITLE
[Feature Request] Add Chromecast Support

### ISSUE THREAD

**Issue by frameset** [advplyr/audiobookshelf-app#38] opened 2021-11-20 17:27 UTC
Would it be possible to add Chromecast streaming to the android app?

**Comment by advplyr** [comment] 2021-11-21 01:29
Yes, I took a look at this today and I think this is doable when streaming the audiobook from your server. Playing a downloaded audiobook will be more difficult, so that will come later.
This is a duplicate of #11. I will follow up there when this is ready for testing.

**Closed by advplyr** 2021-11-21 01:29 UTC
