### ISSUE TITLE
[Enhancement]: Allow multi-select in the mobile app to select more than one book at once for download

### ISSUE THREAD

**Issue by kuldan5853** [advplyr/audiobookshelf-app#1203] opened 2024-05-15 21:48 UTC
### Describe the Feature/Enhancement

Right now, to download a book to your phone, you need to open it in the library view, and then select download. 

I would suggest that on the library view, a long press on an audiobook opens a multi-select mode (same as the radio button in the web gui) to select multiple books, enabling a "download" button to batch queue downloads. 

(This would then also apply to the downloaded content view for deletion I assume). 

### Why would this be helpful?

If you want to keep a big library available offline, you need to do a lot of individual clicking to download books one by one. 

### Future Implementation (Screenshot)
![Untitled](https://github.com/advplyr/audiobookshelf-app/assets/168973729/3247a8fb-0440-4e38-a97d-67b58819d991)

### Audiobookshelf App Version

Android App - 0.9.63

### Current Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf-app/assets/168973729/fd8d8a1f-f73c-47f7-b9ee-c8793f463eab)

**Comment by kuldan5853** [comment] 2024-05-15 21:58
This also links to:
https://github.com/advplyr/audiobookshelf-app/issues/1043
https://github.com/advplyr/audiobookshelf-app/issues/1114

**Comment by nichwall** [comment] 2024-05-15 22:14
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/188

**Comment by advplyr** [comment] 2024-05-15 22:19
renamed #188 to be more easy to find

**Closed by advplyr** 2024-05-15 22:19 UTC
Labels: enhancement

**Comment by kuldan5853** [comment] 2024-05-15 22:20
> renamed #188 to be more easy to find

Thank you!
