### ISSUE TITLE
[Enhancement]: Option to Obscure Notification Cover Art

### ISSUE THREAD

**Issue by cy-24** [advplyr/audiobookshelf-app#1219] opened 2024-06-02 05:54 UTC
### Describe the Feature/Enhancement

It would be great if there was an option in the settings to obscure or disable the cover art in media playback notifications. It could be a single toggle for all playback or applied only to books tagged as Explicit.

### Why would this be helpful?

My wife likes listening to romance books which often have covers that are simply not appropriate for children. Ive been able to move these books into a seperate library that is restricted, however this doesnt prevent the images from appearing in full view on her phone's notifications.
It would be good to disable this behaviour either globably or case by case using the Explicit tag.

### Future Implementation (Screenshot)

Just an extra toggle in settings would be nice.

### Audiobookshelf App Version

Android App - 0.9.63

**Comment by nichwall** [comment] 2024-06-02 16:26
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/885

**Comment by advplyr** [comment] 2024-06-02 16:43
Duplicate of #885

**Closed by advplyr** 2024-06-02 16:43 UTC
Labels: enhancement
