### ISSUE TITLE
Podcast library's Latest tab to automatically queue episodes and auto play them

### ISSUE THREAD

**Issue by joshuatly** [advplyr/audiobookshelf-app#806] opened 2023-07-25 01:22 UTC
### Is your feature request related to a problem? Please describe.
Request to auto queue and play episodes from a Podcast library's Latest page.
I think this behavior exist in web player.
The desirable outcome would be starting an episode from the top, and it will play all unplayed episodes from top (latest) to bottom (oldest)

However the web player's behavior is also odd as the latest page sort in reverse chronological order, and starting on the latest (first) item only play the first. While starting an episode while scrolled down will queue up episodes from bottom to top. (I don't think here is the right place to request for the change or feature request for web player, just fyi)

Using server version 2.2.23, Android app version 0.9.65-beta.

**Comment by advplyr** [comment] 2023-07-26 14:56
Duplicate of #416

**Closed by advplyr** 2023-07-26 14:56 UTC
Labels: enhancement
