### ISSUE TITLE
AndroidTV / FireTV Stick Navigation Support

### ISSUE THREAD

**Issue by colvdv** [advplyr/audiobookshelf-app#1121] opened 2024-03-06 17:32 UTC
I managed to sideload audiobookshelf onto a FireTV Stick and it loads up great, the only issue is navigation. I am unable to navigate down into the selected library, "cursor" stays stuck in the top area where I can switch libraries and access the settings menu and filters, but cant access anything below that, and so can't play content.

### Describe the solution you'd like:
Improve navigation / add navigation support for FireTV & other screens that arent touchscreens.

**Comment by nichwall** [comment] 2024-03-06 17:43
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/606

**Comment by advplyr** [comment] 2024-03-06 21:01
Duplicate of #606

**Closed by advplyr** 2024-03-06 21:01 UTC
Labels: enhancement

**Comment by bilbospocketses** [comment] 2026-04-07 12:35
apk for sideloading is available for Android TV.

It needs to be tested on devices beyond my Google TV Streamer 4K, but on that device it works pretty well, so it should be fine on standard Android and Google TV devices back to Android 8. Not sure how well it will work on Fire TV, but am interested to hear any feedback.

All feedback is appreciated over on my forked repo so I can continue to tune the app while the devs of the main repo work on reviewing and merging the PR.

APK: https://github.com/bilbospocketses/audiobookshelf-app/releases/

Issues page for feedback (bugs, enahncements, etc): https://github.com/bilbospocketses/audiobookshelf-app/issues

Pull Request: https://github.com/advplyr/audiobookshelf-app/pull/1843

User guide for the ATV app: https://github.com/bilbospocketses/audiobookshelf-app/blob/android-tv-dpad-navigation/docs/TV_USER_GUIDE.md
