### ISSUE TITLE
Add Option: remember playback speed per book / series / library

### ISSUE THREAD

**Issue by dedors** [advplyr/audiobookshelf-app#918] opened 2023-10-21 22:13 UTC
### Is your feature request related to a problem? Please describe.
I listen to a book at the day and a episode of a series to fall asleep. I never want to listen to my night books other than 1x. I have to switch speeds every day.

Other usecases maybe: podcasts at higher speed (which may have it's own series or library too).

### Describe the solution you'd like
Easy: add option "remember playbackspeed per book"

### Describe alternatives you've considered
Advanced (optimal for my usecase): Add a option with a dropdown list: 

```
Remember Playback speed: 
- Always (default)
- per Book
- per Series                *would be my setting        
- per Library
```

**Comment by advplyr** [comment] 2023-10-21 22:27
Related issue https://github.com/advplyr/audiobookshelf/issues/1785

Would you expect this selected playback speed to sync with the server?

**Comment by dedors** [comment] 2023-10-21 23:16
> Would you expect this selected playback speed to sync with the server?
yes

**Comment by advplyr** [comment] 2023-10-21 23:48
Ah okay then this belongs in the server repo. It's unlikely this is added anytime soon if at all because of the UI/UX challenges so I'll put as a dupe of that existing issue

**Comment by advplyr** [comment] 2023-10-21 23:48
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1785

**Closed by advplyr** 2023-10-21 23:48 UTC
Labels: enhancement

**Comment by dedors** [comment] 2023-10-24 02:11
If it just remember it on the client side, it would be sufficient. At least a lot better than switching all the time. 
If that would be easier to implement.
