### ISSUE TITLE
[Enhancement]: Autoadd newly downloaded podcasts to playlist

### ISSUE THREAD

**Issue by P8ntBal1551** [advplyr/audiobookshelf-app#447] opened 2022-11-21 19:14 UTC
I would like a feature that auto-adds podcasts to the current playlist after they are downloaded.

**Comment by advplyr** [comment] 2023-02-16 23:49
Duplicate of #416

**Comment by advplyr** [comment] 2023-02-16 23:49
Actually duplicate for #199

**Closed by advplyr** 2023-02-16 23:49 UTC
