### ISSUE TITLE
Downloaded books aren't working correctly when the app was reset or reinstall.

### ISSUE THREAD

**Issue by Demian98** [advplyr/audiobookshelf-app#653] opened 2023-03-30 11:26 UTC
### Steps to reproduce

1. Download a book in the android app for offline usage, to your preferred download location.
2. Reinstall the app (or delete its data).
3. Go to local media and add the download location with the before downloaded book.
4. Force a scan of the location.
5. All In short: Configure the app to detect already downloaded books.

### Expected behaviour
- The local books should be detected and handled like they are downloaded right now.

### Actual behaviour
- The local books are detected and displayed under local media. When the app is started without a connection to the server, the books are available to listen to them offline. But when the app is started with connection to the server, these specific books are not handled like offline books. The button still displays "Stream" instead of "Play". The player also shows that these books are streamed directly from the server.
- Books downloaded in this instance of the app are always played from the local resources, regardless of the connection state to the server.

### Why is this an issue?
- If I start playback in online mode and losses connection for a while of switch my phone to offline mode, then the playback does stop, because the book is streamed. This forces me to actually delete the downloaded books together with the app and redownload everything.
- Currently, #635 forces me to reset the app weekly. This is very annoying, especially under the condition of this issue.

### Environment data

Audiobookshelf Version: Server: 2.2.16, App: 0.9.63-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
- Android version: 10
- Device model: SM-N975F
- Stock or customized system: Stock

**Comment by advplyr** [comment] 2023-03-30 11:51
Duplicate of #157 

We still need to build in a way to automatically link downloaded items back to server items

**Closed by advplyr** 2023-03-30 11:51 UTC
Labels: bug
