### ISSUE TITLE
Can't login to my local audiobookshelf server when there's no internet

### ISSUE THREAD

**Issue by SurjitSahoo** [advplyr/audiobookshelf-app#1151] opened 2024-03-24 17:59 UTC
### Steps to reproduce

1. Turn off internet in local network
2. Open the mobile app and enter the server IP address
3. Goto Login screen, enter userid and password.
4. Login button is not present, instead it says "no network connection" 

### Expected behaviour
- As it's a local server, I should be able to login, listen to and download audiobooks and podcasts to my phone from my local server without internet connection.

Audiobookshelf Version: 0.9.73-beta (android app), 2.8.1 (server)

- [x] Android App
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Mi F3 

Stock or customized system: PixelExperience 13 Plus

**Comment by nichwall** [comment] 2024-03-24 18:04
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/566

**Comment by SurjitSahoo** [comment] 2024-03-24 18:12
It's been 1 year since #566 And the issue still exists 😂

**Closed** 2024-03-24 18:14 UTC
Labels: bug

**Comment by hobesman** [comment] 2024-03-26 19:20
I'm not sure I ever heard any feedback of my proposal: if the app detects no Internet, instead of disabling the sign in button, just say "You don't appear to be online. Attempt connection anyway?" And let the user override it.

Is that as simple as it sounds? (Says the non-programmer in the room...)
