### ISSUE TITLE
[Enhancement]: Cache sort settings or make it configurable

### ISSUE THREAD

**Issue by 10461097** [advplyr/audiobookshelf-app#1420] opened 2024-12-27 05:58 UTC
### Describe the Feature/Enhancement

The default sort setting for episodes is 'Pub Date (desc)' and 'Incomplete.' If I need to change it, I have to do so manually every time I visit the podcast page. However, this is not the case in a web browser, where sort settings are cached or persisted. I hope the App can implement a similar feature to retain sort settings for convenience.

### Why would this be helpful?

Better usage experience

### Future Implementation (Screenshot)

No UI change involved

### Audiobookshelf App Version

Android App - 0.9.77

**Comment by nichwall** [comment] 2024-12-27 13:57
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/304

**Closed** 2024-12-27 14:48 UTC
Labels: enhancement
