### ISSUE TITLE
[iOS] Reset progress in open player when discarding progress

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#714] opened 2023-05-26 11:01 UTC
### Steps to reproduce

1. Start playing a podcast to an arbitrary position
2. Pause the podcast
3. Navigate back through your library to that specific episode. 
4. Click the three dot menu and select "Mark as played"
5. 4. Click the three dot menu and select "Discard progress"
6. Click the "Play" button in the bottom right corner.

### Expected behaviour
- The podcast should start playing from 0:00

### Actual behaviour
- The podcast starts playing from where it was paused

### Environment data

Audiobookshelf Version: 2.2.20

- [ ] Android App?
- [X] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.3.1

iPhone model:
14 Plus

**Comment by advplyr** [comment] 2023-06-18 19:28
I'm not sure this is expected behavior. If you already have the audio player open to that podcast episode then just press the prev track button or track the seek cursor to the beginning.

Let me know if I'm misunderstanding

**Comment by ScuttleSE** [comment] 2023-06-18 19:36
Hm, why doesn't "Discard progress" reset the progress in the player too?

If I have a podcast ep open in the player at 10:00, pause it, select "Discard progress" and then un-pause it, shouldn't it start playing at 00:00?

**Comment by advplyr** [comment] 2023-06-18 19:59
What would your expected behavior be if you press discard progress while playing?

**Comment by ScuttleSE** [comment] 2023-06-19 05:08
Well, shouldn't Discard Progress do just that? reset progress back to 00:00?

**Comment by advplyr** [comment] 2023-06-19 13:15
I see what you mean. I might be biased because I built it and just see these actions as separate.
We can see if anyone else has thoughts on this.

**Comment by advplyr** [comment] 2023-06-19 13:16
What would the expected action be if you mark the episode as finished while it is currently playing?

**Comment by nichwall** [comment] 2023-07-08 16:00
My expectation is the currently open session is not affected by changing progress status.

Plex and Jellyfin do it similarly, where you can "Mark as Watched", "Mark as Unwatched", and "Play from Beginning". Marking as un/watched updates the watch status, but does not affect the open playback session (regardless of whether the player is paused). "Play from Beginning" does restart playback in the open session from the beginning, which I expect to happen.

**Comment by advplyr** [comment] 2023-07-08 22:16
I agree. It would seem unusual to me to update the state of the open player.

**Closed by advplyr** 2023-07-08 22:16 UTC
Labels: enhancement
