### ISSUE TITLE
[iOS] Disable scrubbing on MPRemoteCommandCenter

### ISSUE THREAD

**Issue by fidoriel** [advplyr/audiobookshelf-app#1093] opened 2024-02-20 16:17 UTC
### Is your feature request related to a problem? Please describe.
In the past days I accidentally touched the progress bar on the 'Now Playing' widget in numerous situations on iOS (this is not a ABS issue, I have this with a lot of apps, I do not like that touching on the progress bar is sensitive.). I had to find the position in the audiobook where I left off, which is not a great listening experience.

### Describe the solution you'd like
Add an option to settings to disable `commandCenter.changePlaybackPositionCommand.isEnabled`. 

### Describe alternatives you've considered
Just disable the `commandCenter.changePlaybackPositionCommand.isEnabled`. 

### Additional context
I thought about why I would like this to be enabled at all. I was not able to find one.
- It is not possible to navigate through a multi hour audiobook precisely. If I do want to find a chapter, I use the app and not the widget. It is not possible to find the exact position.
- If I want to go back 30s, I would use the 10s back button multiple times, because it is way more precise.
- I can change it to the chapter view, so that not the full audiobook is displayed, only the current chapter. Same reason. I would use the go back button or the app to find the chapter.

Therefor, I do not see any reason why allowing scrubbing through the audiobook on the widget.

**Comment by nichwall** [comment] 2024-02-20 16:29
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/526 but also includes specific option

**Comment by fidoriel** [comment] 2024-02-20 16:32
Oh, thank you, did not find it because of different wordings.

It is a question of wished behavior, philosophy of usage. The fix seems trivial.

**Comment by advplyr** [comment] 2024-02-20 16:33
Duplicate of #526

**Closed by advplyr** 2024-02-20 16:33 UTC
Labels: enhancement

**Comment by nichwall** [comment] 2024-02-20 16:45
> It is a question of wished behavior, philosophy of usage. The fix seems trivial.

It just hasn't been done yet. If you can make and test the change, that would be great.

**Comment by fidoriel** [comment] 2024-02-20 18:14
> > It is a question of wished behavior, philosophy of usage. The fix seems trivial.
> 
> It just hasn't been done yet. If you can make and test the change, that would be great.

I created and tested a pr. So now we can discuss ;)
