### ISSUE TITLE
Pull chapter info from podcast description

### ISSUE THREAD

**Issue by kpervin** [advplyr/audiobookshelf-app#1113] opened 2024-03-03 16:27 UTC
### Is your feature request related to a problem? Please describe.
As a user, I would like for Podcast chapters to be included when listening to a podcast.

### Describe the solution you'd like
Podcasts, such as [The NoSleep Podcast](https://www.thenosleeppodcast.com/episodes/s20/20x20), will typically have time codes of various parts of the podcast in their descriptions. It would be great if Audiobookshelf could infer these chapters based on the description and automatically create chapter metadata based on such.

### Describe alternatives you've considered
Alternatively being able to swipe to the description of the podcast and highlight any timestamps in the description with a hyperlink to that timestamp in the playback would be fantastic. Pocket Casts has this feature and it is very intuitive.

**Comment by advplyr** [comment] 2024-03-03 17:56
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2363

**Closed by advplyr** 2024-03-03 17:56 UTC
Labels: enhancement
