### ISSUE TITLE
When reading epub files, the text slightly shifts further to the right every time a page is turned.

### ISSUE THREAD

**Issue by Storkundus** [advplyr/audiobookshelf-app#834] opened 2023-08-06 11:27 UTC
### Steps to reproduce

1. Read an epub file on windows using a web browser.
2. Continue reading, the problem becomes apparent after turning the page a number of times (approx 40-50 page turns)
![Audiobookshelf Screenshot 2023-08-06 212455](https://github.com/advplyr/audiobookshelf-app/assets/141557588/86095f6f-39e6-40b6-baa6-cdd49ef0bf15)
.

### Expected behaviour

- Pages should appear consistently in the centre after turning a page

### Actual behaviour

1. The right hand side of the text will be being cut off and some text from the previous page will appear on the left of screen.
2. The problem gets worse the more pages are turned.

### Environment data
Windows 11 22H2 22621.1992
Can reproduce on Chrome & Brave 

Audiobookshelf Version:
2.3.3
- [ ] Android App?
- [ ] iOS App?

**Comment by Storkundus** [comment] 2023-08-07 03:42
I just tried this in firefox browser. Initial indications are that it's not occurring. Perhaps it only affects chromium based browsers.
Firefox also appears to be more reliable at resuming at the correct page.

**Comment by advplyr** [comment] 2023-09-16 13:27
Duplicate of #867

**Closed by advplyr** 2023-09-16 13:27 UTC
Labels: bug

**Comment by advplyr** [comment] 2023-09-16 13:30
This is reproducible for me on certain ebooks. I shared an issue on #867 that shows it is a bug with epubjs library we use
