### ISSUE TITLE
Sleeptimer resetting at every chapter while using Cast

### ISSUE THREAD

**Issue by Krieten** [advplyr/audiobookshelf-app#1197] opened 2024-05-06 06:09 UTC
### Steps to reproduce

1. Play Audiobook
2. Cast Audio
3. Set Sleeptimer
4. wait for chapter to end

### Expected behaviour
- Sleeptimer should run out of time and stop playback

### Actual behaviour
- Sleeptimer resets at the end/start of every chapter

### Environment data

Audiobookshelf Version: v2.9.0 docker

Android App v0.9.73-beta

#### Android Issue
Android version: 14

Device model: Samsung Galaxy S21 Ulta

Stock or customized system: stock

**Comment by nichwall** [comment] 2024-05-06 13:26
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/780

**Closed** 2024-05-06 16:31 UTC
Labels: bug
