### ISSUE TITLE
Podcast playlists do not progress in iOS app

### ISSUE THREAD

**Issue by was2** [advplyr/audiobookshelf-app#652] opened 2023-03-28 15:36 UTC
### Steps to reproduce

1. In a podcast library, create a playlist with several items in the web interface
2. From the iOS app, access the playlist and click 'Play'

### Expected behaviour
- Tell us what should happen
The latest incomplete item in the playlist should start playing. Once complete, the item should be marked compete and the next item should begin playing.

### Actual behaviour
- Tell us what happens
The first/current item will begin playing, but once complete, the next playlist item does not play. Also, the 'Play' button is not available even after playback stops - you have to select another item elsewhere in the app, then come back and restart the playlist.

### Environment data

Audiobookshelf Version:

- [ ] Android App?
- [ X] iOS App? 0.9.63-beta

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.3.1

iPhone model: iPhone 11

**Comment by advplyr** [comment] 2023-09-11 22:28
Duplicate of #416

**Closed by advplyr** 2023-09-11 22:28 UTC
Labels: bug
