### ISSUE TITLE
Rewind in the notification panel and equalizer

### ISSUE THREAD

**Issue by Otnak** [advplyr/audiobookshelf-app#1157] opened 2024-03-28 17:34 UTC
Greetings!,
 I have a wish.  Short rewind in the notification panel does not rewind the current track to the previous one; you have to manually open the application and do it in the player.  The notification also lacks chapter switching buttons.
 I also really wanted an equalizer in the application with the option to increase the sound level.

**Comment by advplyr** [comment] 2024-04-01 22:21
Duplicate of #1086

**Closed by advplyr** 2024-04-01 22:21 UTC
Labels: enhancement

**Comment by Otnak** [comment] 2024-04-30 07:19
You probably didn't understand the problem.  I mean the bug of the existing short rewind.  If you rewind using short rewind, it will go to the beginning of the track and will not go further to the previous one.  Please check it yourself and correct it in future versions.  I'm not asking you to add anything new to the application, but only to correct an existing defect.

**Comment by Otnak** [comment] 2024-05-01 09:45
![Screenshot_2024-05-01-12-39-58-754-edit_com audiobookshelf app](https://github.com/advplyr/audiobookshelf-app/assets/158036126/fd16ebef-9983-4b65-a6fe-865952cf4af1)

Rewind button marked in red.  It rewinds the audiobook file only to the beginning of the file.  Rewinding to the previous file does not work.  What is the problem?
