### ISSUE TITLE
AndroidAuto - M4B shows full length of book in the "now playing" screen and not length of current chapter

### ISSUE THREAD

**Issue by anthonysciutto** [advplyr/audiobookshelf-app#729] opened 2023-06-03 16:01 UTC
With single file m4b audiobooks in the now playing section the entire length of the book is shown even if there are chapter divisions in the metadata. On the app I see a second progress bar for current chapter length.

Perhaps this is intended and I should adjust my use case? I can split the m4b into an mp3 per chapter but that seems antithetical to the purpose of the m4b file and making an app have a higher ease of use.

I assume AndroidAuto limits you to a single progress bar so I think a couple options are reasonable:
- option to display total book length or current chapter
- display current chapter only

**Comment by advplyr** [comment] 2023-06-03 17:25
This is because the app is giving the audio player (exoplayer) the audio file(s) and the audio player is handling how that information is displayed. This is why if you have an audiobook with many mp3 it will show the track for each mp3.

I intend on building this to override the defaults so that we can show the progress bars by chapter instead of by audio track. I haven't decided how that will be done but it will handle the case of android auto and the audio player in the notification/lock screen.

There is an issue open for this #239. Without explaining the underlying reason it wouldn't be intuitive that that issue is related.

**Comment by advplyr** [comment] 2023-06-03 17:25
Duplicate of #239

**Closed by advplyr** 2023-06-03 17:25 UTC
Labels: enhancement

**Comment by anthonysciutto** [comment] 2023-06-03 19:11
Appreciate the explanation and apologies for the duplicate request!
