### ISSUE TITLE
listening history.

### ISSUE THREAD

**Issue by tboudreaux** [advplyr/audiobookshelf-app#490] opened 2023-01-04 12:20 UTC
Sometimes book progress is lost due to user error. For example I'll sometimes accidentally slide the progress slider on the media notification while returning the phone to my pocket and loose my place. Given that ABS already stores the time at the end of the last listening session it would be helpful to have a way to quickly jump to these times available in the mobile app. Something like a "listening history"

**Comment by advplyr** [comment] 2023-01-04 12:41
Duplicate of #466

**Closed by advplyr** 2023-01-04 12:41 UTC
Labels: enhancement
