### ISSUE TITLE
IOS: Testflight - Wrong app version reported?

### ISSUE THREAD

**Issue by prolife86** [advplyr/audiobookshelf-app#558] opened 2023-02-07 18:45 UTC
### Steps to reproduce

1. Install Testflight
2. Install app
3. Wrong version??

### Expected behaviour
- Tell us what should happen
TestFlight notes 0.9.61-beta installed

### Actual behaviour
- Tell us what happens
Version 0.9.60-Beta is shown in the app.
This was seen as I was trouble shooting syncing issues.

Via Testflight going back to 0.9.60-beta results in a non-starting app with an immidiate crash of the app.
Going back to 0.9.61-beta (according to Testflight) results in a working app, but with version 0.9.60-beta noted in the ABS-app.

### Environment data

Audiobookshelf Version:
- [X] iOS App?

#### iOS Issue
iOS Version: 16.1.1

iPhone model: iPhone 13 Mini

![514942e4-495c-4d43-b962-84c1b38dc892](https://user-images.githubusercontent.com/49482721/217337633-afbd60bb-9f43-4e81-8ead-00c558993d9c.jpg)

![fa777fcd-214b-4ea2-960c-15c68d803406](https://user-images.githubusercontent.com/49482721/217337635-9c5feb41-f0de-4e7e-b834-1827fb3e9bbb.jpg)

**Comment by advplyr** [comment] 2023-02-12 18:27
Duplicate of #539

**Closed by advplyr** 2023-02-12 18:27 UTC
Labels: bug
