### ISSUE TITLE
Carplay support

### ISSUE THREAD

**Issue by kraen** [advplyr/audiobookshelf-app#974] opened 2023-12-07 22:11 UTC
### Is your feature request related to a problem? Please describe.
I often listen to audiobooks when driving my car

### Describe the solution you'd like
A simple interface to use with Carplay

### Describe alternatives you've considered
None

### Additional context
None

**Comment by nichwall** [comment] 2023-12-07 22:12
Duplicate of #475

**Comment by advplyr** [comment] 2023-12-07 22:37
Duplicate of #475

**Closed by advplyr** 2023-12-07 22:37 UTC
Labels: enhancement
