### ISSUE TITLE
ReplayGain Support

### ISSUE THREAD

**Issue by reverendj1** [advplyr/audiobookshelf-app#1156] opened 2024-03-27 21:41 UTC
### Is your feature request related to a problem? Please describe.
It seems like many audiobooks are recorded at very low volumes. Or perhaps, most music MP3s are recorded at very loud volumes. :-| Regardless, it can be difficult to hear many audiobooks and some of my headphones just can't be turned up high enough to hear some books well. Because of this, I have taken to using setting the [ReplayGain](https://wiki.hydrogenaud.io/index.php/ReplayGain) on all of my books. It adds a few ID3 tags to each file, to increase/decrease the volume per track, and normalize them all to a consistent volume per library, so they can be heard well on all speakers/devices. However, it appears that audiobookshelf may ignore these tags. I've increased the volume quite a bit on my library, and it doesn't seem to make a difference.

### Describe the solution you'd like
Add support for ReplayGain tags and increase/decrease the volume output based on them.

### Describe alternatives you've considered
An alternative, which I would like to see either way, is to add a "volume boost" button or slider in the UI to boost the volume ad-hoc.

**Comment by nichwall** [comment] 2024-03-27 23:05
It looks like that means additional logic needs to be added to playback?

The ABS app is just using the default audio player (exoplayer on Android, not sure what it is called on iOS), and a quick Google search shows exoplayer doesn't support replaygain tags or the format. Not sure if there's something else more information you can provide on implementing it.

**Comment by nichwall** [comment] 2024-03-27 23:06
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/195

**Comment by advplyr** [comment] 2024-03-28 15:44
Duplicate of #195

**Closed by advplyr** 2024-03-28 15:44 UTC
Labels: enhancement
