### ISSUE TITLE
[Enhancement]: Series or Multi-select download option

### ISSUE THREAD

**Issue by Callidin** [advplyr/audiobookshelf-app#655] opened 2023-04-01 13:12 UTC
### Is your feature request related to a problem? Please describe.
Downloading a longer series can take a while. Having to go into each item individually and select the download option for each item is tedious and gets annoying when the "download complete" banner blocks books at the bottom of the scroll. Having a bulk download option would be very nice to have. 

### Describe the solution you'd like
Two main ideas come to mind. Either would work. Both would be fantastic. 

1. Add a "Download Series" button/option in the Series hamburger menu.
2. Allow multi-item selection and have an option to download selected items. 

### Describe alternatives you've considered
Aside from the above, not much else I can think of that is also simple/UI friendly.

**Comment by advplyr** [comment] 2023-04-01 13:37
Duplicate of #188

**Closed by advplyr** 2023-04-01 13:37 UTC
Labels: enhancement
