### ISSUE TITLE
Chromecast volume keys

### ISSUE THREAD

**Issue by dabanhfreak** [advplyr/audiobookshelf-app#754] opened 2023-06-22 00:16 UTC
### Is your feature request related to a problem? Please describe.
Might be a bug might not be, but my volume keys don't turn volume up/down when connecting to Chromecast audio

### Describe the solution you'd like
Volume keys to integrate with Chromecast just like YouTube

### Describe alternatives you've considered
Only solution that works us to use Google Home app.

**Comment by advplyr** [comment] 2023-06-22 13:58
Duplicate of #584

**Closed by advplyr** 2023-06-22 13:58 UTC
Labels: enhancement
