### ISSUE TITLE
M4B Download to local Storage Fails

### ISSUE THREAD

**Issue by jparrish88** [advplyr/audiobookshelf-app#154] opened 2022-04-29 05:21 UTC
### Steps to reproduce

1. Open Android App, Ensure you have storage permissions and a download folder setup. Find an audiobook you want to download. Ensure, in the file list, that it is m4b. 
2. Click the "download" icon in the app, wait for it to reach 100%
3. On 100% it shows an Error instead. "Item download complete but failed to create library item"

### Expected behaviour
I would expect the file to show up in the local folder storage and the app able to play from that local storage. 

### Actual behaviour
The Error is issued, in red, at the bottom of the screen. One can check the app's scan of the folder, it does not show up. It is, however, able to be seen inside the folder with various folder applications. 

### Environment data

Audiobookshelf Version:

[ 0.9.43-beta] Android App

#### Android Issue
Android version: 10

Device model: Samsung Galaxy Note 9

Stock or customized system: Stock

**Comment by jparrish88** [comment] 2022-04-29 05:26
I thought it might be worth it to post some images. The files that show up in the app are mp3 based, where the others are all m4b, but are downloaded in full and appear in a file manager. 

Also wanted to mention that another has confirmed this issue on their side through discord.

**Comment by kmatasfp** [comment] 2022-04-30 12:11
Happens to me as well

**Comment by advplyr** [comment] 2022-04-30 15:57
This is happening when trying to move the file to the folder you selected.

If you can also test this by selecting a folder already on the phone by default that would be helpful. By that I mean a folder like "Audiobooks" or "Music" or "Downloads", the ones that are there by default. I'm assuming you created your own folder since that is where most of the permission issues I've seen are coming up.

Also, if anyone can provide a logcat for this that would be best.

**Comment by kmatasfp** [comment] 2022-04-30 18:37
Here are the relevant logs
```
04-30 11:29:29.222 20251 20251 D AbsDownloader: DOWNLOAD: FILE MOVE COMPLETED
04-30 11:29:29.224 20251 20251 D AbsDownloader: DOWNLOAD: COMPLETED FILE INFO /storage/emulated/0/Audiobooks/The Tower of the Swallow_ The Witcher, Book 04/The Tower of the Swallow.m4b
04-30 11:29:29.304 20251 20419 D AbsDownloader: checkDownloads Download cover.jpg bytes 33010 | bytes dled 33010 | downloadStatus 8
04-30 11:29:29.311  3657  4322 I MediaProvider: Begin Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///storage/emulated/0/Audiobooks/The Tower of the Swallow_ The Witcher, Book 04/The Tower of the Swallow.m4b flg=0x1000010 cmp=com.android.providers.media.module/com.android.providers.media.MediaService }
04-30 11:29:29.801  3657  4322 I MediaProvider: End Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///storage/emulated/0/Audiobooks/The Tower of the Swallow_ The Witcher, Book 04/The Tower of the Swallow.m4b flg=0x1000010 cmp=com.android.providers.media.module/com.android.providers.media.MediaService }
04-30 11:29:29.844 20251 20407 D FolderScanner: scanDownloadItem failed to find media folder
04-30 11:29:29.844 20251 20407 D AbsDownloader: Item download complete The Tower of the Swallow: The Witcher, Book 04 | local library item id: null | Items remaining in Queue 0
```

Download finishes, media scan afterwards seem to fail

And If I do manual scan afterwards I get
```
04-30 11:33:54.813 20251 20330 D FolderScanner: Probe Result DATA 59044.876 | 520312959 | Intro | Andrzej Sapkowski
04-30 11:33:54.813 20251 20330 D FolderScanner: Found local media item named The Tower of the Swallow_ The Witcher, Book 04 with 1 tracks and 2 local files
04-30 11:33:54.820 20251 20330 D FolderScanner: Folder $Audiobooks scan Results: 1 Added | 0 Updated | 0 Removed | 1 Up-to-date
04-30 11:33:54.821 20251 20330 D AbsFileSystem: Scan DATA {"itemsAdded":1,"itemsUpdated":0,"itemsRemoved":0,"itemsUpToDate":1,"localFolder":{"id":"cHJpbWFyeTpBdWRpb2Jvb2tz\n","name":"Audiobooks","contentUrl":"content://com.android.externalstorage.documents/tree/primary%3AAudiobooks/document/primary%3AAudiobooks","basePath":"Audiobooks","absolutePath":"/storage/emulated/0/Audiobooks","simplePath":"primary:Audiobooks","storageType":"EXTERNAL","mediaType":"book"},"localLibraryItems":[{"id":"local_cHJpbWFyeTpBdWRpb2Jvb2tzL1RoZSBUb3dlciBvZiB0aGUgU3dhbGxvd18gVGhlIFdpdGNoZXIsIEJvb2sgMDQ=","folderId":"cHJpbWFyeTpBdWRpb2Jvb2tz\n","basePath":"Audiobooks/The Tower of the Swallow_ The Witcher, Book 04","absolutePath":"/storage/emulated/0/Audiobooks/The Tower of the Swallow_ The Witcher, Book 04","contentUrl":"content://com.android.externalstorage.documents/tree/primary%3AAudiobooks/document/primary%3AAudiobooks%2FThe%20Tower%20of%20the%20Swallow_%20The%20Witcher%2C%20Book%2004","isInvalid":false,"mediaType":"book","media":{"metadata":{"title":"The Tower of the Swallow_ The Witcher, Book 04","subtitle":null,"authors":[],"narrators":[],"genres":[],"publishedYear":null,"publishedDate":null,"publisher":null,"description":null,"isbn":null,"asin":null,"language":null,"explicit":false,"authorName":null,"authorNameLF":null,"narratorName":null,"seriesName":null},"coverPath":"/storage/emulated/0/Audiobooks/The Tower of the Swallow_ The Witcher, Book 04/cover.jpg","tags":[],"audioFiles":[],"chapters":[{"id":0,"start":0.0,"end":99.653,"title":"Intro"},{"id":1,"start":99.653,"end":4153.504,"title":"Chapter One"},{"id":2,"start":4153.504,"end":10003.771,"title":"Chapter Two"},{"id":3,"start":10003.771,"end":15267.873,"title":"Chapter Three"},{"id":4,"start":15267.873,"end":21742.432,"title":"Chapter Four"},{"id":5,"start":21742.432,"end":26111.266,"title":"Chapter Five"},{"id":6,"start":26111.266,"end":30510.101,"title":"Chapter Six"},{"id":7,"start":30510.101,"end":36101.976,"title":"Chapter Seven"},{"id":8,"start":36101.976,"end":40841.447,"title":"Chapter Eight"},{"id":9,"start":40841.447,"end":47466.61,"title":"Chapter Nine"},{"id":10,"start":47466.61,"end":53671.352,"title":"Chapter Ten"},{"id":11,"start":53671.352,"end":58997.845,"title":"Chapter Eleven"},{"id":12,"start":58997.845,"end":59044.875,"title":"Outro"}],"tracks":[{"index":1,"startOffset":0.0,"duration":59044.876,"title":"The Tower of the Swallow.m4b","contentUrl":"content://com.android.externalstorage.documents/tree/primary%3AAudiobooks/document/primary%3AAudiobooks%2FThe%20Tower%20of%20the%20Swallow_%20The%20Witcher%2C%20Book%2004%2FThe%20Tower%20of%20the%20Swallow.m4b","mimeType":"audio/mp4","metadata":null,"isLocal":true,"localFileId":"cHJpbWFyeTpBdWRpb2Jvb2tzL1RoZSBUb3dlciBvZiB0aGUgU3dhbGxvd18gVGhlIFdpdGNoZXIsIEJvb2sgMDQvVGhlIFRvd2VyIG9mIHRoZSBTd2FsbG93Lm00Yg==","audioProbeResult":{"streams":[{"index":0,"codec_name":"aac","codec_long_name":"unknown","channels":1,"channel_layout":"mono","duration":59044.875238,"bit_rate":69109.0}],"chapters":[{"id":0,"start":0,"end":99653,"tags":{"title":"Intro"}},{"id":1,"start":99653,"end":4153504,"tags":{"title":"Chapter One"}},{"id":2,"start":4153504,"end":10003771,"tags":{"title":"Chapter Two"}},{"id":3,"start":10003771,"end":15267873,"tags":{"title":"Chapter Three"}},{"id":4,"start":15267873,"end":21742432,"tags":{"title":"Chapter Four"}},{"id":5,"start":21742432,"end":26111266,"tags":{"title":"Chapter Five"}},{"id":6,"start":26111266,"end":30510101,"tags":{"title":"Chapter Six"}},{"id":7,"start":30510101,"end":36101976,"tags":{"title":"Chapter Seven"}},{"id":8,"start":36101976,"end":40841447,"tags":{"title":"Chapter Eight"}},{"id":9,"start":40841447,"end":47466610,"tags":{"title":"Chapter Nine"}},{"id":10,"start":47466610,"end":53671352,"tags":{"title":"Chapter Ten"}},{"id":11,"start":53671352,"end":58997845,"tags":{"title":"Chapter Eleven"}},{"id":12,"start":58997845,"end":59044875,"tags":{"title":"Outro"}}],"format":{"filename":"/storage/emulated/0/Audiobooks/The Tower of the Swallow_ The Witcher, Book 04/The Tower of the Swallow.m4b","f
```

File itself does not seem to contain metadata regarding authors, genre etc

**Comment by kmatasfp** [comment] 2022-04-30 18:48
And if that is useful medatata extracted from the file using exiftools
```
ExifTool Version Number         : 12.41
File Name                       : The Tower of the Swallow.m4b
Directory                       : /home/kmatas/tmp/work 3
File Size                       : 496 MiB
File Modification Date/Time     : 2022:04:30 11:44:16-07:00
File Access Date/Time           : 2022:04:30 04:58:08-07:00
File Inode Change Date/Time     : 2022:04:30 11:44:16-07:00
File Permissions                : -rw-r--r--
File Type                       : M4A
File Type Extension             : m4a
MIME Type                       : audio/mp4
Major Brand                     : MP4 Base Media v1 [IS0 14496-12:2003]
Minor Version                   : 0.2.0
Compatible Brands               : isom, iso2, mp41
Media Data Size                 : 325
Media Data Offset               : 510072093
Movie Header Version            : 0
Create Date                     : 0000:00:00 00:00:00
Modify Date                     : 2022:04:30 09:09:52
Time Scale                      : 1000
Duration                        : 16:24:05
Preferred Rate                  : 1
Preferred Volume                : 100.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 3
Track Header Version            : 0
Track Create Date               : 0000:00:00 00:00:00
Track Modify Date               : 0000:00:00 00:00:00
Track ID                        : 1
Track Duration                  : 16:24:05
Track Layer                     : 0
Track Volume                    : 100.00%
Handler Description             : SoundHandler
Balance                         : 0
Audio Format                    : mp4a
Audio Channels                  : 2
Audio Bits Per Sample           : 16
Audio Sample Rate               : 44100
Chapter List Track ID           : 2
Handler Vendor ID               : Apple
Cover Art                       : (Binary data 59021 bytes, use -b option to extract)
Media Type                      : Audiobook
Artist                          : Andrzej Sapkowski
Album                           : The Tower of the Swallow: The Witcher, Book 04
Comment                         : 
Content Create Date             : 2016
Encoded By                      : m4b-tool
Genre                           : Fantasy
Title                           : Intro
Encoder                         : Lavf58.76.100
Chapter List                    : [0:00:00.000] Intro, [0:01:39.653] Chapter One, [1:09:13.504] Chapter Two, [2:46:43.771] Chapter Three, [4:14:27.873] Chapter Four, [6:02:22.432] Chapter Five, [7:15:11.266] Chapter Six, [8:28:30.101] Chapter Seven, [10:01:41.976] Chapter Eight, [11:20:41.447] Chapter Nine, [13:11:06.610] Chapter Ten, [14:54:31.352] Chapter Eleven, [16:23:17.845] Outro
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Media Header Version            : 0
Media Create Date               : 2022:04:30 09:09:52
Media Modify Date               : 2022:04:30 09:09:52
Media Time Scale                : 1000
Media Duration                  : 16:24:05
Media Language Code             : und
Handler Type                    : Text
Gen Media Version               : 0
Gen Flags                       : 0 0 0
Gen Graphics Mode               : ditherCopy
Gen Op Color                    : 32768 32768 32768
Gen Balance                     : 0
Other Format                    : text
Warning                         : [minor] The ExtractEmbedded option may find more tags in the media data
Avg Bitrate                     : 69.1 kbps

```

**Comment by advplyr** [comment] 2022-04-30 18:57
It looks like there is an underscore used in the folder name: `Tower of the Swallow_ The Witcher`. What is the title of the audiobook on your server?

**Comment by kmatasfp** [comment] 2022-04-30 19:02
Title on my server is `The Tower of the Swallow: The Witcher, Book 04` same as `Album` in the metadata - `Album                           : The Tower of the Swallow: The Witcher, Book 04`

**Comment by kmatasfp** [comment] 2022-04-30 19:04
and folder stucture on my server is - `.../media/audiobooks/Sapkowski, Andrzej/The Witcher Saga/Vol 4 - 1997 - The Tower of the Swallow
`

**Comment by advplyr** [comment] 2022-04-30 19:04
Just confirmed, the semicolon is getting replaced with an underscore that is causing the issue. Looking into why that is happening.

**Comment by kmatasfp** [comment] 2022-04-30 19:07
I am pretty sure one cannot have a semicolon as part of the file/folder name

**Comment by advplyr** [comment] 2022-04-30 19:10
Yeah and it seems android changes it automatically

**Comment by kmatasfp** [comment] 2022-04-30 19:12
and semicolon was added there by audible provider when I filled the metadata - all my audiobooks are from my books converted from my audible library

**Comment by kmatasfp** [comment] 2022-04-30 19:13
quickest fix would be probably to the audible matcher so instead of semicolon it uses `-` when book is part of series

**Comment by advplyr** [comment] 2022-04-30 19:17
I'm adding a function that will replace all invalid characters for android file system

**Comment by jparrish88** [comment] 2022-04-30 19:27
Just wanted to confirm my original and downloaded file name has an
underscore.

**Comment by jparrish88** [comment] 2022-05-01 08:51
I changed my file name in the folder and rescanned. Then I downloaded
again. The file itself has no strange characters in the filename, now. But
still failed download.



FolderScanner: scanDownloadItem starting for
/storage/emulated/0/Download/audiobooks/The Dragon Reborn |
content://com.android.externalstorage.documents/tree/primary%3ADownload%2Faudiobooks/document/primary%3ADownload%2Faudiobooks%2FThe%20Dragon%20Reborn
| Item Folder Id:primary:Download/audiobooks/The Dragon Reborn | LLI
Id:local_cHJpbWFyeTpEb3dubG9hZC9hdWRpb2Jvb2tzL1RoZSBEcmFnb24gUmVib3Ju
FolderScanner: scanDownloadItem 1 files found in
/storage/emulated/0/Download/audiobooks/The Dragon Reborn
FolderScanner: scanDownloadItem did not find any audio tracks in folder for
/storage/emulated/0/Download/audiobooks/The Dragon Reborn
AbsDownloader: Item download complete The Dragon Reborn | local library
item id: null | Items remaining in Queue 0


05-01 01:33:22.138 20320 20320 D ExternalStorage: After updating volumes,
found 2 active roots
05-01 01:33:22.205 18512 14561 D FolderScanner: scanForMediaItems Checking
Existing LLI
local_cHJpbWFyeTpEb3dubG9hZC9hdWRpb2Jvb2tzL0FyaXN0b3RsZSBhbmQgRGFudGUgRGlzY292ZXIgdGhlIFNlY3JldHMgb2YgdGhlIFVuaXZlcnNl
05-01 01:33:22.209 18512 14561 D FolderScanner: scanForMediaItems Checking
Existing LLI
local_cHJpbWFyeTpEb3dubG9hZC9hdWRpb2Jvb2tzL0FyaXN0b3RsZSBhbmQgRGFudGUgRGl2ZSBpbnRvIHRoZSBXYXRlcnMgb2YgdGhlIFdvcmxk
05-01 01:33:22.209 18512 14561 D FolderScanner: scanForMediaItems Checking
Existing LLI
local_cHJpbWFyeTpEb3dubG9hZC9hdWRpb2Jvb2tzL0FzdHJvcGh5c2ljcyBmb3IgUGVvcGxlIGluIGEgSHVycnk=
05-01 01:33:22.209 18512 14561 D FolderScanner: scanForMediaItems Checking
Existing LLI
local_cHJpbWFyeTpEb3dubG9hZC9hdWRpb2Jvb2tzL1RoZSBDaXR5IG9mIEVtYmVy
05-01 01:33:22.209 18512 14561 D FolderScanner: scanForMediaItems Checking
Existing LLI
local_cHJpbWFyeTpEb3dubG9hZC9hdWRpb2Jvb2tzL0l0cyBpbiBIaXMgS2lzcw==
05-01 01:33:22.335 18512 14561 D FolderScanner: Iterating over Folder Found
The Dragon Reborn | primary:Download/audiobooks/The Dragon Reborn | URI:
content://com.android.externalstorage.documents/tree/primary%3ADownload%2Faudiobooks/document/primary%3ADownload%2Faudiobooks%2FThe%20Dragon%20Reborn
05-01 01:33:22.369 18512 14561 D FolderScanner: Found image/jpeg file
cover.jpg in folder The Dragon Reborn
05-01 01:33:22.373 18512 14561 D FolderScanner: File attributes
Id:cHJpbWFyeTpEb3dubG9hZC9hdWRpb2Jvb2tzL1RoZSBEcmFnb24gUmVib3JuL2NvdmVyLmpwZw==|ContentUrl:content://com.android.externalstorage.documents/tree/primary%3ADownload%2Faudiobooks/document/primary%3ADownload%2Faudiobooks%2FThe%20Dragon%20Reborn%2Fcover.jpg|isDownloadsDocument:false
05-01 01:33:22.373 18512 14561 D FolderScanner: scanLibraryItemFolder new
local file found /storage/emulated/0/Download/audiobooks/The Dragon
Reborn/cover.jpg


Nothing to indicate to me that the actual m4b was scanned.

**Comment by jparrish88** [comment] 2022-05-01 09:05
Here's into the normal downloads directory: 

05-01 01:59:21.594 18512 30992 D AbsDownloader: checkDownloads Download TheDragonRebornBookThreeofTheWheelofTimeep6.m4b bytes 708690458 | bytes dled 708690458 | downloadStatus 8
05-01 01:59:21.594 18512 30992 D AbsDownloader: checkDownloads Download TheDragonRebornBookThreeofTheWheelofTimeep6.m4b Done
05-01 01:59:21.608 18512 30992 D AbsDownloader: DOWNLOAD: Attempt move for file at destination file:///storage/emulated/0/Android/data/com.audiobookshelf.app/files/Download/TheDragonRebornBookThreeofTheWheelofTimeep6.m4b | Android/data/com.audiobookshelf.app/files/Download/TheDragonRebornBookThreeofTheWheelofTimeep6.m4b
05-01 01:59:21.608 18512 30992 D AbsDownloader: DOWNLOAD: Move file to final destination path: /storage/emulated/0/Download/The Dragon Reborn/TheDragonRebornBookThreeofTheWheelofTimeep6.m4b
05-01 01:59:22.795 18512 18512 D AbsDownloader: DOWNLOAD: PREPARING MOVE FILE

05-01 01:59:53.571 18512 18512 D AbsDownloader: DOWNLOAD: FILE MOVE COMPLETED
05-01 01:59:53.574 18512 18512 D AbsDownloader: DOWNLOAD: COMPLETED FILE INFO /storage/emulated/0/Download/The Dragon Reborn/TheDragonRebornBookThreeofTheWheelofTimeep6.m4b
05-01 01:59:53.650  5402 29041 I MediaProvider: Begin Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///storage/emulated/0/Download/The Dragon Reborn/TheDragonRebornBookThreeofTheWheelofTimeep6.m4b flg=0x1000010 cmp=com.android.providers.media/.MediaService }
05-01 01:59:53.658 18512 30992 D AbsDownloader: checkDownloads Download cover.jpg bytes 24036 | bytes dled 24036 | downloadStatus 8
05-01 01:59:53.694  1310  2213 D SyncManager: userId - 0 auto - true
05-01 01:59:53.699  5402 29041 I MediaProvider: End Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///storage/emulated/0/Download/The Dragon Reborn/TheDragonRebornBookThreeofTheWheelofTimeep6.m4b flg=0x1000010 cmp=com.android.providers.media/.MediaService }
05-01 01:59:53.699  1310  2213 D SyncManager: userId - 0 auto - true
05-01 01:59:53.702  1310  2213 D SyncManager: userId - 0 auto - true
05-01 01:59:53.705  5402  5605 D MediaSync: noting to sync
05-01 01:59:53.705  1310  2213 D SyncManager: userId - 0 auto - true
05-01 01:59:53.708  1310  2213 I chatty  : uid=1000(system) Binder:1310_7 identical 1 line
05-01 01:59:53.712  1310  2213 D SyncManager: userId - 0 auto - true
05-01 01:59:53.714  1310  2825 D SyncManager: userId - 0 auto - true
05-01 01:59:53.717  1310  2825 D SyncManager: userId - 0 auto - true
05-01 01:59:53.721  1310  2213 D SyncManager: userId - 0 auto - true

05-01 01:59:58.553 18512 30992 D FolderScanner: scanDownloadItem starting for /storage/emulated/0/Download/The Dragon Reborn | content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2FThe%20Dragon%20Reborn | Item Folder Id:primary:Download/The Dragon Reborn | LLI Id:local_cHJpbWFyeTpEb3dubG9hZC9UaGUgRHJhZ29uIFJlYm9ybg==
05-01 01:59:58.583 18512 30992 D FolderScanner: scanDownloadItem 1 files found in /storage/emulated/0/Download/The Dragon Reborn
05-01 01:59:58.599 18512 30992 D FolderScanner: scanDownloadItem did not find any audio tracks in folder for /storage/emulated/0/Download/The Dragon Reborn
05-01 01:59:58.627 18512 30992 D AbsDownloader: Item download complete The Dragon Reborn | local library item id: null | Items remaining in Queue 0

**Comment by advplyr** [comment] 2022-05-01 11:08
And mp3's are downloading okay for you?

**Comment by jparrish88** [comment] 2022-05-01 23:15
Yes, no problems downloading or playing mp3.

**Comment by advplyr** [comment] 2022-05-01 23:36
Do any of the audio file names have special characters in them?

**Comment by jparrish88** [comment] 2022-05-02 01:36
None of the mp3 files had special characters (they all had spaces). When I
originally tried the m4b, they all had an underscore in the filename.

I removed the underscore from the file name last night, that's where the
log at comes from and still had issues. Then I removed it from the folder
name too and still had issues ( audiobookshelf saw it as another book,
which is ok ).

I retried the same test as above into the normal Downloads folder too and
still have what looks to be the same issue.  Would a complete log of both
mp3 and m4b locally downloaded help?

**Comment by advplyr** [comment] 2022-05-07 17:07
This should be fixed now in [v0.9.44-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.44-beta) but let me know

**Comment by jparrish88** [comment] 2022-05-07 17:55
> This should be fixed now in [v0.9.44-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.44-beta) but let me know

Apologize for bad news.  I just tested with 2.10 and 9.44. Unfortunately,  I get the same issue.  Will post logcat later today.

**Comment by kmatasfp** [comment] 2022-05-07 18:47
Sorry for late reply.

@jparrish88 in you book metadata to you specify a `Subtitle` i.e 
```
Title: The Handmaids Tale
Subtitle: Special Edition
```
?

That would cause the downloaded file name to become ` The Handmaids Tale: Special Edition` which contains special character `:`, which would be replaced by Android downloader with underscore, after replacement happens the Audiobookshelf App scanner cannot match any of the "titles" (Title + Subtitle) and hence it fails, at least this is how it seems to me

**Comment by jparrish88** [comment] 2022-05-07 19:01
Book Four of The Wheel of Time
The above is the subtitle. I don't see that happening with the assignment of the name of the folder or filename. Either way I removed the subtitle and tried it again with no luck. To confirm, are we talking ABS Metadata or id3 tags? I only removed the abs subtitle for now.

**Comment by kmatasfp** [comment] 2022-05-07 19:06
Yes file metadata and how does it show in the Audiobookshelf Book Details page, like this?

![Book details](https://user-images.githubusercontent.com/33095685/167268377-1b11ad92-467e-46ed-9c11-04ae385e4d23.PNG)

or like this

![Book details 2](https://user-images.githubusercontent.com/33095685/167268433-b979fb5a-9c0e-4cca-b191-27d40133ec32.PNG)

Book name (downloaded directory name) seems to be the one that is in the `Title` field in Book Details

**Comment by kmatasfp** [comment] 2022-05-07 19:11
In my case if I had subtitle tag in my file metadata the `Title` become `The Handmaid's Tale: Special Edition` which is "wrong". So I had to manually fix it. Also I saw that for some books even if I did not have `Subtitle`, but if I used `Audible` Matcher I sometimes got titles that had concatenated of book name and subtitle with `:` i.e `Recursion: A Novel`

**Comment by advplyr** [comment] 2022-05-07 19:12
Subtitle is not going to be appended to the name when downloading. It is only using the title.

**Comment by kmatasfp** [comment] 2022-05-07 19:17
Yeah, but for me when I initially scanned the files that had `Subtitle` metadata, the title became `book name: subtitle`.  Now that I think about it I also had this peace of metadata in my file `Album: Handmaid;s Tale: Special Edition` - title and subtitle already concatenated

Anyway one of my points still stands - Audiobookhelf App scanner that runs after downloading expects to find a book with a downloaded name, but as downloader changed the name, by adding underscore, it cannot find any books and fails

**Comment by gone** [comment] 2022-05-08 19:44
I have an mb4 w/o a subtitle that's failing in the same way

**Comment by advplyr** [comment] 2022-05-12 23:51
I'm not able to reproduce this issue. Is this isolated to specific m4b files or is it all of your m4b files?

The folder scanner is looking for these file types `"audio/*", "image/*", "video/mp4"` and these aren't matching your m4b.

If we can isolate whether it is specific m4b's encoded a certain way, or if it is all m4b's on your device that could help narrow this down.

**Comment by jparrish88** [comment] 2022-05-13 00:28
For testing, I just tried doing this on a Android 11 system. With the same
file it doesn't happen. This may be an Android 10 issue (Or possibly 10 and
below)  what os version are you running?

**Comment by advplyr** [comment] 2022-05-13 00:46
Android 12

**Comment by whaddayakno** [comment] 2022-05-20 19:39
I'm having the same issue on android 10. It downloads fine for mp3 but can't get any m4b downloads to work

**Comment by hobesman** [comment] 2022-05-21 02:51
Same issue. On Android 9.

**Comment by advplyr** [comment] 2022-05-22 23:34
This should be fixed in [0.9.46](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.46-beta) but please let me know

**Comment by SenorSmartyPants** [comment] 2022-05-23 00:01
Just tried this build on my moto g 7 Android 10. App crashes, download manager continues to download M4B, but then is not in download location. Please let me know how/where to contribute logs if needed.

**Comment by advplyr** [comment] 2022-05-23 00:15
@SenorSmartyPants Is your issue specific to M4B?

**Comment by SenorSmartyPants** [comment] 2022-05-23 00:36
Trying a multi-file mp3 audio book now. App didn't crash when I started download, updates progress for a bit, but does crash .

All mp3s and cover seem to download based on the download manager notifications, but do not show up in my Download/Audiobookshelf folder.

I changed folder to "Downloads" the system created folder. Downloads finished and are visible in Files by Google. But the app crashed (after 100%) and does not know that there are local media files, or when I view the book there's no indication that the files have been downloaded.

**Comment by SenorSmartyPants** [comment] 2022-05-23 00:39
I tried the same M4B again, but using "Downloads" as the directory. App shows download progress until 100% then shortly after crashes. Files are present in Downloads, but no indication of that in "local media" in app.

Attempted to scan local media in app, but app crashed.

**Comment by advplyr** [comment] 2022-05-23 00:39
You're having a different issue then, most likely related to permissions. You can try the workaround brought up here: https://github.com/advplyr/audiobookshelf-app/issues/115

**Comment by SenorSmartyPants** [comment] 2022-05-23 00:57
I don't get any access denied messages. I cleared my cache/storage and just selected "Download" for my local directory (which seems to be the workaround you mention). Tried mp3 download, it gets to 100%, app crashes. Files are in Downloads. I start up app, go to local media, 0 books. Scan, app crashes.

**Comment by advplyr** [comment] 2022-05-23 12:44
The workaround is actually a bit more complicated to explain, described in that post I shared.

This issue was confirmed in discord to have been solved though so I'm going to close this. It had to do with Android 10 and below showing m4b files to have a mime type of application/octet-stream

**Closed by advplyr** 2022-05-23 12:44 UTC
Labels: bug

**Comment by whaddayakno** [comment] 2022-05-23 20:17
Can confirm this is fixed for me in 0.9.46. Really appreciate it, thanks advplyr!!

**Comment by gone** [comment] 2022-05-23 20:19
Can confirm this works for me, Thanks for fixing!

**Comment by yegods** [comment] 2023-05-10 01:18
I am also having the same problem... just started recently (though it may be the first time i've used m4b files).  How do we get this issue re-opened?

**Comment by advplyr** [comment] 2023-05-12 23:32
I think you may be encountering some other issue. Are you sure your issue is only limited to M4B files and you have tried other M4B files from different sources?

**Comment by yegods** [comment] 2023-05-13 00:11
I just checked with a standard mp3 based audiobook, and got the same error message.  Is this an outstanding issue?  How do I find out the cause?

**Comment by advplyr** [comment] 2023-05-13 01:12
I would have to be able to reproduce it. Is this happening with every audiobook you try? What device are you using?
Can you try setting a new download folder, usually these are permission issues.

**Comment by yegods** [comment] 2023-05-14 15:30
I created a new download folder, and all file types downloads worked perfectly.  Sorry for the false alarm!

**Comment by dgl3906464** [comment] 2023-07-01 23:26
I've tried setting a new download folder. It pulls the cover but not m4bs. If I manly pull the m4b and rename to match the cover, it "sees" it, but doesn't allow tracking of progress, and any skip forward or back restarts the book. Book streams fine.

(I've tried 6 different m4bs with the same results) 

How do I capture a log for you?

**Comment by indiefan** [comment] 2023-07-06 21:15
I'm experiencing this issue with all m4bs as well (they stream fine, but cannot download). The download "finishes" suspiciously quickly as well (likely not actually downloading data).

Should we file a new bug for this, or reopen this one? (I don't actually know if there is any relation in cause, just symptoms)

**Comment by advplyr** [comment] 2023-07-06 22:03
Make sure you are using the latest app `0.9.65-beta` and the latest server `2.2.23`

Can you share what android version and device you are using?

Can you try both a shared folder and internal storage?

Are you seeing an error alert come up after the download finishes?

When you download to a shared folder, can you check that folder on your device and see if the files are there or not?

Have you checked the server logs for errors after the failed download?

Have you tried downloading an audiobook that is mp3 or another format?

When you stream the m4b is this direct playing or transcoding? You can see the word "Direct" or "Transcoding" at the top of the audio player when opened full screen.

**Comment by indiefan** [comment] 2023-07-07 02:19
Nm, my issue ended up being an out of date server. I'll file a separate bug about better error reporting...

**Comment by dgl3906464** [comment] 2023-07-09 15:24
Mine was the server as well - I found this article on how to set up watchtower to keep the server up to date automagically:
https://mariushosting.com/synology-30-second-watchtower-install-using-task-scheduler-docker/

**Comment by shezxx** [comment] 2023-08-24 10:22
I have the issue as well, the last time i had it i updated the server and everything was good - this time though im on v2.3.3 and 0.9.65-beta

**Comment by xanthos84** [comment] 2023-11-27 06:01
this error is now also on iOS in version 0.9.67…
cant download items on the device….

**Comment by advplyr** [comment] 2023-11-27 10:06
@xanthos84 This wouldn't be the same issue since it was specific to Android 10 and below

**Comment by github-e51** [comment] 2023-11-27 10:09
> @xanthos84 This wouldn't be the same issue since it was specific to Android 10 and below

okay, well anyway I made a new bug report...

**Comment by tazztone** [comment] 2024-04-01 20:50
i also had this error when trying to download an audiobook to local storage:
"Item download complete but failed to
create library item"

solution was to go to
1. menue
2. local media
3. local folders: remove them and then re-add them (it will ask for file access permission again, which was missing, i suspect)
