### ISSUE TITLE
[Android Auto] Displayed Total track even if "chapter track" is selected

### ISSUE THREAD

**Issue by Ansem93** [advplyr/audiobookshelf-app#1125] opened 2024-03-09 14:58 UTC
### Steps to reproduce

1. From Player uncheck "total track" and check "chapter track"
2.  Just use Android Audio

### Expected behaviour
It should follow the same option as Android player, so display the Chapter track and not the Total track.

### Environment data

Audiobookshelf Version:

Android App: 0.9.73-beta

#### Android Issue
Android version: 14

Device model: galaxy s21+

Stock or customized system: stock

**Comment by advplyr** [comment] 2024-03-10 14:22
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/239

**Comment by advplyr** [comment] 2024-03-10 14:23
Also see https://github.com/advplyr/audiobookshelf-app/issues/729#issuecomment-1575082870 for an explanation on the issue and why it is a duplicate

**Closed by advplyr** 2024-03-10 14:22 UTC
Labels: bug
