### ISSUE TITLE
Progress is not being synced. Restart playback

### ISSUE THREAD

**Issue by Commiccannon** [advplyr/audiobookshelf-app#671] opened 2023-04-15 07:16 UTC
### Steps to reproduce
Docker install on windows server, listen to audiobooks on web player getting following error: Progress is not being synced. Restart playback
Restarted the server and progress from last two days from android app had disappeared, all stats bar items finished have been deleted. Logs giving: [DB] Update entity user Failed: Error: Lock file is already being held

### Expected behaviour
No errors and progress storage 
### Actual behaviour
Errors and progress not stored

### Environment data

Audiobookshelf Version:
V2.2.18
- [ X] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
0.9.63
Device model:
S32
Stock or customized system:
Stock

**Comment by Commiccannon** [comment] 2023-04-15 07:27
Update, found the logs in the docker environment not just the web gui
`2023-04-15 17:22:47 [2023-04-15 07:22:47] ERROR: Failed to get session Error: Lock file is already being held
2023-04-15 17:22:47     at /server/libs/properLockfile/lib/lockfile.js:68:47
2023-04-15 17:22:47     at callback (/node_modules/graceful-fs/polyfills.js:306:20)
2023-04-15 17:22:47     at FSReqCallback.oncomplete (node:fs:203:5) {
2023-04-15 17:22:47   code: 'ELOCKED',
2023-04-15 17:22:47   file: '/config/sessions/data/data.1.json'
2023-04-15 17:22:47 } (Db.js:458)`

**Comment by advplyr** [comment] 2023-04-15 15:26
This is a known issue that has to do with the database specifically on some Windows file systems.
I'm not able to reproduce this on my Windows machine so haven't been able to figure out why some users have this problem.

**Comment by advplyr** [comment] 2023-04-15 15:26
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1326

**Closed by advplyr** 2023-04-15 15:26 UTC
Labels: bug

**Comment by DebrodeD** [comment] 2023-05-24 21:58
I just had this problem after restarting my audiobookshelf container after restarting my windows pc (ABS running in docker desktop). I cleared the cache in ABS and then restarted my container in docker desktop and it fixed the issue.

**Comment by DebrodeD** [comment] 2023-05-25 18:33
Nevermind, the problem comes back shortly after restarting (though restarting does fix it temporarily).
![2023-05-25 12_31_58-Audiobookshelf](https://github.com/advplyr/audiobookshelf-app/assets/16518976/fb9e58c7-f17e-433c-8b64-195b5d4dfc52)

@advplyr any ideas?

**Comment by advplyr** [comment] 2023-05-25 20:01
This lock file issue only seems to happen with Windows and using a remote file system. Can you describe your server set up and file system?

**Comment by DebrodeD** [comment] 2023-05-25 20:30
A bit more info: When I restart, it seems to start working again, but there are hundreds of entries under listening sessions where there should only be a few. They all seem to be duplicated.
![2023-05-25 14_29_35-Audiobookshelf](https://github.com/advplyr/audiobookshelf-app/assets/16518976/f1e82fdc-497a-4e00-a6a4-8d3314b2c090)

**Comment by DebrodeD** [comment] 2023-05-25 22:13
As you can see from my android app, the saves are showing up with an error message:

![photo_2023-05-25_16-10-27](https://github.com/advplyr/audiobookshelf-app/assets/16518976/b8489abb-ee35-4b78-b32c-a0200414c94d)

However, the "time remaining" status on the web app is updating with each one, so it seems like it's still making it through? What definitely isn't working at all with these errors however is the "listening sessions".

**Comment by advplyr** [comment] 2023-05-25 22:56
If you are seeing lock file errors on the server then data isn't being saved. I haven't been able to reproduce that lockfile issue on Windows yet so I'm not sure how to resolve it.

**Comment by riffy13** [comment] 2023-06-17 07:06
Happening here too on linux. Audiobookshelf docker files are on the main ext4 disk. Stopping the container & deleting all the lock files & folders, sometimes fixes it temporarily. Error I get:

`[2023-06-17 01:53:42] ERROR: [DB] Update entity user Failed: Error: Lock file is already being held (Db.js:415)

[2023-06-17 01:53:45] ERROR: [DB] Update entity session Failed: Error: Lock file is already being held (Db.js:415)

[2023-06-17 01:53:48] ERROR: [DB] Update entity user Failed: Error: Lock file is already being held (Db.js:415)

[2023-06-17 01:53:50] ERROR: [DB] Update entity session Failed: Error: Lock file is already being held (Db.js:415)

[2023-06-17 01:53:52] ERROR: [DB] Update entity user Failed: Error: Lock file is already being held (Db.js:415)

[2023-06-17 01:53:55] ERROR: [DB] Update entity session Failed: Error: Lock file is already being held (Db.js:415)

[2023-06-17 01:53:58] ERROR: [DB] Update entity user Failed: Error: Lock file is already being held (Db.js:415)

[2023-06-17 01:54:00] ERROR: [DB] Update entity session Failed: Error: Lock file is already being held (Db.js:415)

[2023-06-17 01:54:02] ERROR: [DB] Update entity user Failed: Error: Lock file is already being held (Db.js:415)

[2023-06-17 01:54:05] ERROR: [DB] Update entity session Failed: Error: Lock file is already being held (Db.js:415)
`

**Comment by DocBrown101** [comment] 2024-04-04 17:56
I am also experiencing this error. Debian 12 with Android and browser. 
@advplyr Why was the bug closed?

**Comment by nichwall** [comment] 2024-04-04 18:10
Is your database stored on a network drive?

**Comment by riffy13** [comment] 2024-04-04 18:50
Not on network drive, & still happening only in browsers.

**Comment by DocBrown101** [comment] 2024-04-04 18:51
No, just a normal internal NVME SSD

**Comment by advplyr** [comment] 2024-04-05 20:51
This is closed because the database that was causing this issue was removed entirely so you won't be getting that error log unless you are on v2.2.24 or earlier.

**Comment by DocBrown101** [comment] 2024-04-06 08:19
I am running the latest version 2.8.1, but I have to add that this problem only occurred at the beginning, now that my progress is well over 30%, the sync seems to work.
