### ISSUE TITLE
automatically download podcast episodes

### ISSUE THREAD

**Issue by theballdredge** [advplyr/audiobookshelf-app#1132] opened 2024-03-14 04:09 UTC
### Describe the solution you'd like
It would be great if the app would automatically download new episodes from the server instance automatically when it syncs.

### Describe alternatives you've considered
Doing it manually is kind of a pain.

**Comment by nichwall** [comment] 2024-03-14 04:36
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/613

**Comment by advplyr** [comment] 2024-03-14 13:19
Duplicate of #613

**Closed by advplyr** 2024-03-14 13:19 UTC
Labels: enhancement
