### ISSUE TITLE
Support for Google Android Automotive OS

### ISSUE THREAD

**Issue by roniez** [advplyr/audiobookshelf-app#1017] opened 2023-12-30 07:57 UTC
### Is your feature request related to a problem? Please describe.
Currently i need to have my phone plugged in to my car to use Android Auto or Apple CarPlay where i can access Audiobookshelf it causes me to look away from the road and down on my phone which is illegal in my country but also takes away the focus from driving and keeping eyes on the road when skipping in audiobooks.

### Describe the solution you'd like
Implement support for Google's Android Automotive OS.

### Describe alternatives you've considered
Be stuck using Android Auto or Apple Carplay

### Additional context
More information on how todo this can be found here. 
https://developer.android.com/training/cars/apps/automotive-os

If i had knowledge in development i would add this as a PR my self but my dev skills are extremely limited and my time to spend on this kind of project is even less viable.

**Comment by advplyr** [comment] 2023-12-30 14:27
Duplicate of #621

**Closed by advplyr** 2023-12-30 14:27 UTC
Labels: enhancement
