### ISSUE TITLE
Caching of Home Screen

### ISSUE THREAD

**Issue by Cobolt78** [advplyr/audiobookshelf-app#875] opened 2023-09-17 12:34 UTC
### Is your feature request related to a problem? Please describe.
it seems every time since 2.3+ server/page load times are lengthy (around 25 seconds most times)

### Describe the solution you'd like
Not sure if it's possible but it would be a big QoL addition to have the home screen cached or something like that. Not sure if anyone else is having slow load times since 2.3+ on android and web app but it take up to 25 seconds on most occasions to load the home screen as well as search and clicking on a book and waiting for it to load, when you do click on a book it takes roughly the same amount of time to load, then if you swipe or touch home it then has to take another 25 or so seconds to load that same home screen when nothing has changed but it.
Where as if the home screen could be cached or something then the load times would be really quick and once connecting and verifying from the server it only updates the changes if needed.
I hope I have explained this clear enough, if not let me know and I'll try and reword it. 

Thanks

### Describe alternatives you've considered
None

### Additional context
None

**Comment by advplyr** [comment] 2023-09-17 12:53
Yeah this is an issue with larger libraries that has to do with the new database migration to sqlite. We have to improve the sql queries still. There is an open issue about this on the server repo https://github.com/advplyr/audiobookshelf/issues/2073

**Comment by advplyr** [comment] 2023-09-17 12:53
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2073

**Closed by advplyr** 2023-09-17 12:53 UTC
Labels: enhancement
