### ISSUE TITLE
Allow speed adjustments on a per-book basis

### ISSUE THREAD

**Issue by ak-42** [advplyr/audiobookshelf-app#1035] opened 2024-01-05 13:10 UTC
Hi. Loving the app and the service. Thank you for all the work you've put into this, I am eternally grateful.

---
### Is your feature request related to a problem? Please describe.
I like to listen to non-fiction at about 1.2x, but to fiction at the original speed. It would be excellent if I could set a per-book speed selection, and the app would remember it and use it.  
Then, as I switched from one book to another, it would switch the speed as well.

### Describe the solution you'd like
When speed is adjusted on the individual book, the setting should only apply to that book. This would allow the user to have different speed settings per book.

It would also be good to have a default speed set in settings, so that books where speed has not been adjusted yet can follow a uniform speed policy, while the ones where it was adjusted get their own specific speed.

**Comment by advplyr** [comment] 2024-01-05 17:27
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1173

**Comment by advplyr** [comment] 2024-01-05 17:27
Related https://github.com/advplyr/audiobookshelf/issues/1785

**Closed by advplyr** 2024-01-05 17:27 UTC
Labels: enhancement
