### ISSUE TITLE
iOS App keeps crashing (Offline/Not on same Network)

### ISSUE THREAD

**Issue by gh0sti** [advplyr/audiobookshelf-app#471] opened 2022-12-14 03:49 UTC
### Steps to reproduce

1. Have a downloaded audiobook
2. Start playing
3. After a few minutes the app stops and crashes. Pausing the audiobook also crashes and won't resume till I launch the app again and keeps saying the app crashed. I have sent several emails from testflight app with stack trace of the issue.
4. This issue seems to be related to app not communicating with server when offline or not on the same network as the server.

### Expected behaviour
- Tell us what should happen
- app shouldn't crash trying to play a downloaded audiobook

### Actual behaviour
- Tell us what happens
- app crashes after playing an audiobook after awhile.

### Environment data

Audiobookshelf Version:

- [ 0.9.60 (17)] iOS App

#### iOS Issue
iOS Version: 16.2

iPhone model: iPhone 13 PM

**Comment by taxilian** [comment] 2022-12-14 21:43
That's really strange -- I'm on ios 16.0.2, iphone 13 pro max, 0.9.60 (17), and no issues. I'll try updating my iphone and see if it lets me reproduce this issue, since I have the same model phone as @gh0sti

**Comment by gh0sti** [comment] 2022-12-14 22:27
@taxilian I agree it has been strange. I keep submitting the crash logs through testflight each time the app crashes too.

**Comment by benonymity** [comment] 2022-12-15 02:34
I just experienced this too--and I think it might have something to do with the device being online and the server being unreachable. If I turn off wifi and data the app doesn't crash, if one is on but the server isn't reachable it routinely crashes.

**Comment by lerndmina** [comment] 2022-12-19 16:25
I appear to have the same or similar issue.
I have my ABS instance hosted privately at home, so when my device has access to the internet it often does not have access to the ABS instance and often crashes when playing downloaded media.
When I use a VPN to my home network I hardly ever experience any crashes.

IOS: 1.16.2
iPhone 14 Pro
Version: 0.8.60-beta

**Comment by benonymity** [comment] 2022-12-19 17:01
Good to know--I'll try to reproduce it in the simulator to capture some logs. Hopefully we can track down the issue!

**Comment by gh0sti** [comment] 2022-12-19 17:08
> Good to know--I'll try to reproduce it in the simulator to capture some logs. Hopefully we can track down the issue!

It almost sounds like to me a DRM in a way that audiobookshelf needs to contact the server always even with the content locally downloaded and device is no longer connecting to the server. Sounds like others are experiencing this issue as well.

**Comment by anha7196** [comment] 2022-12-21 08:18
This happens to me as well. The app cashes randomly, maybe 5-10 times during an hour, and as far as i have been able to test it, it seems to crash only when not on the same network as the server. If i turn of wifi and data the app still crashes though, but maybe less frequently, hard to tell as i have found no pattern to the crashes. I will try vpn next.

**Comment by lerndmina** [comment] 2022-12-24 02:04
Just commenting to say I have experienced this again. My server is temporarily offline and my phone is connected to the internet. I've reported the crash with a mention of my GitHub username in hopes that the crash logs can be correlated with what we think is causing the issue.

**Comment by blumarten** [comment] 2023-01-01 19:43
i have this as well. trying to play downloaded books and the app just stops playing after about (rough guess) 5 minutes.

**Comment by pewter77** [comment] 2023-01-03 03:59
Have this issue as well. Currently my server is only locally available.

**Comment by blumarten** [comment] 2023-01-03 13:07
i changed my ABS server to my exposed domain for accessing ABS outside my home but this made no difference. My iphone stopped playing a downlaoded file after 7 mins. I'm not sure if the whole app crashed or whether it just stopped playing, but one way or another it still stopped playing.

**Comment by gh0sti** [comment] 2023-01-03 13:48
Having the app crash while not being connected to our server defeats the purposing of having our audiobooks downloaded to play locally.

**Comment by blumarten** [comment] 2023-01-03 14:05
> Having the app crash while not being connected to our server defeats the purposing of having our audiobooks downloaded to play locally.

it still crashes when connected to the server, i tested it earlier

**Comment by lerndmina** [comment] 2023-01-11 11:56
I sometimes get app crashes when connected to the abs server but that is rare and inconsistent. Whereas I can reliably reproduce a crash when not connected to my abs server playing local audiobooks.

**Comment by anha7196** [comment] 2023-01-16 11:56
After testing some more i think the crashes occur after starting the playback offline, but do not occur when starting playback online and then going out of range of the network where the server is available. Pausing playback for a while seems to bring on the crashes again. 

Can someone else confirm this behavior?

**Comment by gh0sti** [comment] 2023-01-16 12:28
I almost wonder if it has to do with syncing the time stamp of where you are in the playback of the audiobook so the server keeps track of where you are on any device.

**Comment by anha7196** [comment] 2023-01-16 15:09
Sounds possible. A bit strange to me though is that the crashes seem to be so irregular. Sometimes very often ans sometimes seldom. 

Please till me if I can help by testing something.

**Comment by jmt-gh** [comment] 2023-01-19 17:01
Just noting that I'm also experiencing this:

iPhone 7
iOS 15.7.1
ABS 0.9.60 (17)

@advplyr -- I'm submitted the crash reports through testflight each time it happens (added a few comments on some of them). Not sure if there's anything relevant in any of those to share here that could help anyone looking in to this?

**Comment by advplyr** [comment] 2023-01-23 23:38
The crash reports are all the same and they show it has to do with Realm. It isn't giving us much but here are screenshots of the report:

![image](https://user-images.githubusercontent.com/67830747/214176302-fa8f4058-9afd-4430-a618-89f4711dfa38.png)


![image](https://user-images.githubusercontent.com/67830747/214176257-ffb56a8c-4a63-4d95-9543-ed21bee01d49.png)

![image](https://user-images.githubusercontent.com/67830747/214176277-6c7cff91-286b-4443-9dd9-14c1ebff76d8.png)

In case anyone wants to dig into this

**Comment by advplyr** [comment] 2023-01-23 23:39
This seems to occur when the phone gets locked and the app gets put in the background.

**Comment by advplyr** [comment] 2023-01-29 20:32
Hopefully fixed in #519 and will be in the next release

**Comment by advplyr** [comment] 2023-01-31 20:24
Fixed in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)

**Closed by advplyr** 2023-01-31 20:24 UTC
Labels: bug, awaiting release
