### ISSUE TITLE
Token based server identification

### ISSUE THREAD

**Issue by TDderpy** [advplyr/audiobookshelf-app#520] opened 2023-01-26 21:18 UTC
### Is your feature request related to a problem? Please describe.

This request has come from, a "issue" I've been having when using a mix between a VPN and local network to access my server. Due to how my VPN is set up I have two accounts saved in my android app. One for accessing over the lan, the other via the VPN. 

I've noticed however this causes a small bug in how ADB tracks progress as it sees the same server as two separate ones. As such it doesn't seem to update my progress correctly. It'll only update on one of the two connection types depending on how I downloaded the book. I.e. if I download off the lan, it'll only show the progress in local files or on the lan, and not when I'm connected over the VPN (or in a few rare instances I'll have two different progress positions for the same book). 

### Describe the solution you'd like

Ideally I'd like a way for the app to tell which server it's connected to regardless of its IP address/app account. In my head something like an identification token would make sense. But happy to discuss alternative options. 

### Additional context

I understand this is partly of my own making with how I've got my VPN set up, and I could fix this by using the remote access method explained in the installation guide. However this is the method I access my lan externally and I'm sure I'm not the only one.

**Comment by advplyr** [comment] 2023-01-26 21:26
This is a duplicate of #356

Essentially the solution is to allow for adding a local ip address that will automatically be used when you are home. This way both addresses are the same connection.

Let me know though if this is different from #356

**Closed by advplyr** 2023-01-26 21:26 UTC
Labels: enhancement

**Comment by hobesman** [comment] 2023-01-26 22:01
I think it's one way to solve the same problem as 356, or 356 is another way to dive what this user is experiencing.

But from a technical standpoint this is a different approach. This would be to have the server identify itself to the app with some sort of unique id, and that way if you connect the app to the server using any of various URLs or IPs, the app will still be able to tell it's the same server.

This approach would also help if you migrate to another host on a different IP, or one day if there's a portable version of the server, the app could tell it's the same server and allow syncing progress on books downloaded before you migrated, etc. So in a way this approach is more flexible than just having "remote" and "local" access URLs. 

Then again, allowing two addresses to be explicitly labeled as the same server that the app can auto switch between might also offer benefits. I think the features are not mutually exclusive even though they somewhat overlap when it comes to addressing this particular need.

**Comment by advplyr** [comment] 2023-01-26 22:17
It's not just the same server that matters, it's the same server and user. The same auth token.

The ID of the connection attached to the local download is something like `username@ipaddress`. We could instead make this a random ID and allow for changing the external & local ip address. That way if you change your home IP or your external you can just update the existing connection and not lose your downloads.

**Comment by hobesman** [comment] 2023-01-27 02:19
True, so basically the username and user token are enough to identify the server as the same or not. Makes sense.
