### ISSUE TITLE
IOS Podcasts do not play

### ISSUE THREAD

**Issue by ddubnyk** [advplyr/audiobookshelf-app#294] opened 2022-07-18 03:26 UTC
### Steps to reproduce

1. Click on any podcast, click play. 

### Expected behaviour
- Clicking play should play the podcast. 

### Actual behaviour
Clicking play, no reaction in the app. 

### Other notes
Podcasts and the app work fine on the android app. Can connect to the server whether or not it's local or remote. 

On iOS, I can listen to podcasts perfectly fine if going through Safari browser. But through the app, no reaction. I have noticed, that if I try to start the podcast in the app first, when I open the webpage in Safari after, the podcast I chose in the app, is actually open on the webpage. So the communication to play the podcast episode is getting to the server. I can look at all the podcasts and see all the podcasts in the app, but I can't play any of them. 

### Environment data

Server Version:
2.0.24

Audiobookshelf Version:

[ 0.9.51 ] iOS App

#### iOS Issue
iOS Version: 15.5

iPhone model: 13 Pro

**Comment by jimbolimbo13** [comment] 2022-07-31 16:33
I’ve noticed this issue as well. It’s not entirely consistent, but have a theory on what causes it:
I have two libraries - one for audiobooks and the other for podcasts. When the play head for the audiobook is farther ahead than the length of the podcast, the podcast won’t play at all. If I go to the audiobook and reset the progress back to the beginning (or some duration less than the length of the podcast) I can play the podcast now. 

A separate issue, but possibly related: I have a suspicion that the two libraries share the same play counter. When I pause with my Bluetooth headphones then hit play again some minutes later, I hear two things being played back (the current audiobook and the current podcast). Going into the app itself and hitting play does not cause this issue. 

Server version: 2.1.1
app Version: 0.9.55-beta iOS

**Comment by advplyr** [comment] 2022-07-31 18:04
@jimbolimbo13 I just tried to test your theory and wasn't able to reproduce that, here is what I did:

1. Open audiobook library and start playback on a audiobook
2. Jump to 4 hours into the audiobook (longer than any episode I have) and let it play at least 10 seconds (ensuring progress sync)
3. Open podcast library leaving the audiobook playing
4. Play a podcast episode with or without progress less than current progress in the player

Result: Audiobook correctly stops playback and episode starts playback

Are these the correct reproduction steps for you?

iPhone X
Server v2.1.1
App v0.9.55-beta

**Comment by ddubnyk** [comment] 2022-08-01 00:33
Here is the weird thing.  It started to work fine for a few days out of nowhere in the app for me.  Same version and server version.  And now, it just suddenly stopped playing anything in the app again.  However if i browse to the website in Safari on the iPhone, it works just fine as always.

**Comment by jimbolimbo13** [comment] 2022-08-01 12:59
@advplyr , those are the steps I would take to break it based on how I fixed it before. I just tried now to reproduce breaking the podcast playback and can’t either.

The steps I mentioned are what I did to fix it when it broke. Perhaps it could be a suggested workaround for now (if that’s actually what fixed it). 

I’ll keep trying to reproduce it on my device.

**Comment by advplyr** [comment] 2022-08-01 13:02
@jimbolimbo13 Got it. I don't think the position of the playback is the difference maker here but it may have helped to open and close the audiobook again.
This one really has me stumped though, can't find any pattern.

**Comment by benonymity** [comment] 2022-08-04 02:29
This happened to me once, but a while ago and ever since podcasts have worked on iOS

**Comment by gboxxx** [comment] 2022-08-11 18:01
Facing the same issue as @ddubnyk original post. 

Like @jimbolimbo13  I have 2 libraries - audiobooks and podcasts. No issues with audiobooks, but clicking play for a podcast highlights the button, but does not play. If I play a podcast via computer, it works. After playing on computer, the iOS app updates progress bar and time remaining. 

--

iOS App - 0.9.55 beta
Server 2.1.2
iOS System - 15.5
iPhone 13 Mini

**Comment by ronaldheft** [comment] 2022-08-20 19:23
I fixed a number of issues in playback on iOS with PR #277. When we get that merged and released, I’d be curious if you can still reproduce.

**Comment by ddubnyk** [comment] 2022-08-20 23:20
I personally will no longer be able to test on iPhone. I got rid of my iPhone due to this issue and only have Android now. Android playback has never had an issue for me. So hopefully someone else will be able to give you feedback.

**Comment by advplyr** [comment] 2022-08-28 16:49
Please follow up if this issue still persists in the latest version [v0.9.57-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.57-beta)

**Comment by booleansmith** [comment] 2022-09-02 05:08
I've never been able to get playback from podcasts until 0.9.57- but now it works for me 🥳 thanks for the continued support of this application!

**Comment by advplyr** [comment] 2022-09-02 13:18
Great, thanks for following up!

**Closed by advplyr** 2022-09-02 13:18 UTC
Labels: bug, unable to reproduce
