### ISSUE TITLE
[Android] Pause button from Bluetooth headset interpreted as Pause -> Rewind -> Play

### ISSUE THREAD

**Issue by dchawisher** [advplyr/audiobookshelf-app#1147] opened 2024-03-22 16:38 UTC
### Steps to reproduce

1. Listen to an audiobook using Jabra Elite 10 earbuds.
2. Press either earbud once to pause.

### Expected behaviour
- Playback should pause.

### Actual behaviour
- The audiobook pauses momentarily, skips back based on the configured rewind interval, and resumes playback.
- History shows "pause," "seek," and "play" occurring in that order, nearly simultaneously.
- This does not occur with other headphones or with other media apps.
- The earbuds' in-ear detection, which pauses media when an earbud is removed, works as expected.

### Environment data

Audiobookshelf Version: 2.8.1

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 9.73-beta

Device model: Pixel 7

Stock or customized system: Stock

**Comment by nichwall** [comment] 2024-03-22 19:29
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/1048

**Comment by advplyr** [comment] 2024-03-22 19:41
Duplicate of #1048

**Closed by advplyr** 2024-03-22 19:41 UTC
Labels: bug
