### ISSUE TITLE
App crashes when play multi-file audiobook

### ISSUE THREAD

**Issue by firain** [advplyr/audiobookshelf-app#1173] opened 2024-04-09 20:10 UTC
### Steps to Reproduce

1. Play the downloaded multi-file audiobook.
2. Play the downloaded multi-file audiobook in the background.

### Expected Behavior

- The app should play the media files without crashing or experiencing performance issues.

### Actual Behavior

- The app is sluggish when starting to play the multi-file audiobook. After about 10 to 20 minutes of playtime, whether in the foreground or background, the app crashes.

### Environment Data

**Audiobookshelf Version:**
- Android App
- Version 0.9.73-beta

**Android Issue**
- Android Version: Android 14
- Device Model: Samsung S23
- System: Stock

**Comment by advplyr** [comment] 2024-04-09 20:35
Is this happening with just this one book or many? Have you tested streaming the book and that is working?

**Comment by advplyr** [comment] 2024-04-11 22:21
If you manually change between files using the progress bar or next/prev chapter buttons does it crash then?

This crash only occurs when the screen is off?

Are you downloading the files to internal storage or selecting a download folder? If you are selecting a download folder can you try with the downloaded book in internal storage?

**Comment by firain** [comment] 2024-04-12 05:49
It happens either the screen on or off. 
The prev/next button didn't crash it. But clicking on the screen or player area while the media starts or switch files will cause the app to crash. The file are downloaded to a selected folder. 
I have tested with internal storage, it plays without any issues, even the sluggish issue is gone.

**Comment by advplyr** [comment] 2024-04-19 20:09
This is the same issue as reported in #1143. 

It is an issue with permissions and the cover image. If you were to remove the cover image from the server and re-download the book it should work.

I'm not able to reproduce this issue with my Google Pixel or emulators and there are not many reports of this so I'm wondering if this is specific to Samsung Galaxy. I'm not sure how to fix this atm

**Comment by firain** [comment] 2024-04-23 03:58
Thank you for looking into the issue. I will combine all of my audiobooks into one file for the time being, and download any multi-file audiobooks that could not be combined to internal storage. Also, thank you very much for making this project.

**Comment by advplyr** [comment] 2024-04-28 21:04
Duplicate of #1143

**Closed by advplyr** 2024-04-28 21:04 UTC
Labels: bug, waiting, unable to reproduce
