### ISSUE TITLE
[BUG]: Artwork missing on Android Auto

### ISSUE THREAD

**Issue by tdp4** [advplyr/audiobookshelf-app#913] opened 2023-10-16 17:54 UTC
### Steps to reproduce

1. open app in android auto
2. begin playing book/audio
3. No album artwork shown on screen

### Expected behaviour
- Artwork and/or blurred background from artwork should be seen.

### Actual behaviour
- background is black/grey, artwork is typically on left next to text. (as seen in other apps)

### Environment data
- Car: Honda CRV 2019

Audiobookshelf Version: 0.9.66-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 14

Android Auto version: 10.5.633834

Device model: Pixel 6 Pro

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by tdp4** [comment] 2023-10-16 17:55
![image](https://github.com/advplyr/audiobookshelf-app/assets/20672410/87ea7b78-9fd9-4a46-9a51-ba4f832243d9)
![image](https://github.com/advplyr/audiobookshelf-app/assets/20672410/02c634a3-7644-4abb-b35e-f47e2cd4fa9a)

**Comment by advplyr** [comment] 2023-10-16 20:56
Duplicate of #141

**Closed by advplyr** 2023-10-16 20:56 UTC
Labels: bug

**Comment by Kavorka9** [comment] 2024-07-17 00:00
This is still an issue fyi

**Comment by nichwall** [comment] 2024-07-17 00:23
This is a duplicate issue
