### ISSUE TITLE
cannot play downloaded book if extension is invalid - iOS 

### ISSUE THREAD

**Issue by jasonblewis** [advplyr/audiobookshelf-app#1122] opened 2024-03-08 01:06 UTC
### Steps to reproduce

1. add an mp3 audiobook where it has been incorrectly saved with the extension m4b
2. press the button in iOS app to download the book to local storage, and wait until book is fully downloaded 
3. press the play button and note error "Playback Failed: Playback Error"

![IMG_1762](https://github.com/advplyr/audiobookshelf-app/assets/129165/fde654ae-014f-4f36-ad29-70666c94a8a0)

### Expected behaviour
- Tell us what should happen

it should either just play, or notify the user why it failed. (or have some other warning system in place to help user fix this kind of issue)

### Actual behaviour
- Tell us what happens
fails to play and shows error on screen

### Environment data

Audiobookshelf Version: 0.9.73.beta

- [ ] Android App?
- [x ] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 17.3.1

iPhone model: 14 Pro Max

**Comment by pengliscu** [comment] 2024-03-25 12:08
有同样的问题

**Comment by advplyr** [comment] 2024-04-01 22:26
Duplicate of #968

**Closed by advplyr** 2024-04-01 22:26 UTC
Labels: bug
