### ISSUE TITLE
Multi Book download

### ISSUE THREAD

**Issue by sharinganthief** [advplyr/audiobookshelf-app#982] opened 2023-12-11 18:38 UTC
### Is your feature request related to a problem? Please describe.
It is annoying to go into each book in a series you would like to download

### Describe the solution you'd like
I would like to long press a book and be given selection dots and a menu to download selected books

### Describe alternatives you've considered
go into each book in a series you would like to download

### Additional context
Could always add more elements, mark finished, add to playlist etc

**Comment by nichwall** [comment] 2023-12-11 23:02
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/188

You can show support for the feature by reacting with a thumbs up to the top comment (please don't just comment "+1")

**Closed** 2023-12-12 00:17 UTC
Labels: enhancement
