### ISSUE TITLE
Continiously playback

### ISSUE THREAD

**Issue by groetg** [advplyr/audiobookshelf-app#1062] opened 2024-02-01 20:01 UTC
When I listen to a podcasts and the podcasts ends, audio bookshelf stops playback. Other podcast app Antennapod keeps playing the next podcast automaticly. What am I doing wrong?

**Comment by groetg** [comment] 2024-02-01 20:02
When I listen to a podcasts and the podcasts ends, audio bookshelf stops playback. Other podcast app Antennapod keeps playing the next podcast automaticly. What am I doing wrong?

**Comment by advplyr** [comment] 2024-02-01 20:38
Duplicate of #416

**Closed by advplyr** 2024-02-01 20:38 UTC
Labels: bug
