### ISSUE TITLE
Remember the current audiobook over app restarts

### ISSUE THREAD

**Issue by asdil12** [advplyr/audiobookshelf-app#1078] opened 2024-02-11 10:11 UTC
### Is your feature request related to a problem? 
It is annoying having to select the audiobook I'm currently listening again, when the app was closed.

### Describe the solution you'd like
The all should remember the current audiobook like the smart audiobook player does it, and directly open the player when opening the app.
Or there should be at least a setting to enable that behavior.

**Comment by nichwall** [comment] 2024-02-11 14:11
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/854

**Comment by advplyr** [comment] 2024-02-11 15:06
Duplicate of #854

**Closed by advplyr** 2024-02-11 15:06 UTC
Labels: enhancement
