### ISSUE TITLE
Android Auto Display Cover Art

### ISSUE THREAD

**Issue by weswitt** [advplyr/audiobookshelf-app#872] opened 2023-09-14 23:56 UTC
It would be great if the android auto app would display the cover art in the playing window. Right now you get a blank window with the media controls.

**Comment by advplyr** [comment] 2023-09-16 13:10
Duplicate of #141

**Closed by advplyr** 2023-09-16 13:10 UTC
Labels: enhancement

**Comment by weswitt** [comment] 2023-09-16 15:01
why would this be "not planned"? every app that plays media displays cover art. this resolution makes no sense.

**Comment by hobesman** [comment] 2023-09-16 15:04
I believe just your instance of the issue is closed. The original posting 141 is still being worked on.

**Comment by advplyr** [comment] 2023-09-16 20:33
That is how github displays when you close an issue as a duplicate. We don't want to have multiple open issues about the same thing.
