### ISSUE TITLE
[Feature] Sleep timer "Custom Time" should also offer "chapters", not just minutes

### ISSUE THREAD

**Issue by DavidPesticcio** [advplyr/audiobookshelf-app#1111] opened 2024-03-01 22:27 UTC
Although the "End of Chapter" option is very useful, if chapters are short that might not be sufficient.

You could calculate the time to the end of your chosen chapter - but there's no easy/accessible way to do that.

Whereas an option to "Stop after n Chapters" (possibly displaying the remaining playtime of those chapters) would be also be very useful. :smile:

**Comment by advplyr** [comment] 2024-03-01 22:32
Duplicate of #202

**Closed by advplyr** 2024-03-01 22:32 UTC
Labels: enhancement
