### ISSUE TITLE
Android Auto - Stuck on Downloads

### ISSUE THREAD

**Issue by sts2302** [advplyr/audiobookshelf-app#951] opened 2023-11-22 11:36 UTC
In the initial Android auto dashboard only the Downloads folder appears and not the list of contents

### Expected behaviour
- Similar experiences as app on the smartphone

### Actual behaviour
- A blank panel called Downloads

### Environment data
Run as a docker in UNRAID

Audiobookshelf Version:

- [X ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model:
Oneplus 8 PRO

Stock or customized system:
OxygenOS 13.1

**Comment by advplyr** [comment] 2023-11-22 13:31
Duplicate of #310

**Closed by advplyr** 2023-11-22 13:31 UTC
Labels: bug
