### ISSUE TITLE
Server (internal/evenfall) + app sync issues

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#946] opened 2023-11-19 18:22 UTC
![Screenshot_2023-11-19-23-43-56-38_e9782661401ed6f222682e1e02b74bd4.jpg](https://github.com/advplyr/audiobookshelf-app/assets/42061703/60b1478d-991c-44dc-96b2-b427afda9c40)

I have a server that's accessible internally as well as externally. There has to be a step to check if the server connected to is the same to eliminate this problem.

I had mentioned this before (a while back) that ABS should implement something similar to Home Assistant and allow automatic switching based on whether connected to a specific SSID - if connected to 'Home wifi' use internal address, else use external address (where the SSID is provided by the user/auto-detected by the app).

When I saw the option of two servers, I thought that this is what was implemented; but from the image it seems it wasn't.

I understand that users may connect to multiple servers (like own servers and those of friends'), but that's a different use case.

I need to be able to connect to '192.168.1.x:port' and 'https://my server.com' (both being the same server) depending on whether I'm at home or outside.

Please include the functionality. Check out home assistant mobile app. They've implemented this well.

Cheers.

**Comment by advplyr** [comment] 2023-11-19 18:31
Duplicate of #209

**Closed by advplyr** 2023-11-19 18:31 UTC
