### ISSUE TITLE
Podcasts - Auto next episode

### ISSUE THREAD

**Issue by JReming85** [advplyr/audiobookshelf-app#742] opened 2023-06-13 20:18 UTC
### Is your feature request related to a problem? Please describe.
I have a large amount of podcasts on my server, when listening to an episode when it ends it just stops playing and I have to manually wake my phone and play the next episode.

### Describe the solution you'd like
I would like it to automatically play the next unplayed episode for that podcast

**Comment by jacky9246** [comment] 2023-08-08 10:01
me too

**Comment by ljy920325** [comment] 2023-08-16 04:43
Has it been resolved yet？

**Comment by JReming85** [comment] 2023-08-17 14:18
> Has it been resolved yet？

No

**Comment by advplyr** [comment] 2023-09-11 22:22
Duplicate of #416

**Closed by advplyr** 2023-09-11 22:22 UTC
Labels: enhancement

**Comment by ktfcaptain** [comment] 2024-02-14 00:07
I can't take silence, and lose track of my phone all the time. 

I love this app and really hope this is coming. 🤞
