### ISSUE TITLE
No network connection / vpn

### ISSUE THREAD

**Issue by Arctic4161** [advplyr/audiobookshelf-app#1183] opened 2024-04-17 17:22 UTC
### Steps to reproduce

1. Android version 8.1.0
2. Install tailscale or zerotier vpn
3. Audiobookshelf server on
4. Audiobookshelf version 0.9.73-beta

### Expected behaviour
- Should be able to type in IP address of server and submit

### Actual behaviour
- can't type into IP address field, submit button turns into No Network Connection 

### Environment data

Audiobookshelf Version: 0.9.73-beta
- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 8.1.0

Device model:
S7

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by Arctic4161** [comment] 2024-04-17 17:23
I am able to connect to the server with the same methods using my s24 with no issues. Not sure why there is an issue on the older device. Also see the same issue on a Samsung tablet model SM-T378V

**Comment by advplyr** [comment] 2024-04-17 18:53
Duplicate of #566

**Closed by advplyr** 2024-04-17 18:53 UTC
Labels: bug
