### ISSUE TITLE
Saved play speed resets when connecting to or switching servers (iOS)

### ISSUE THREAD

**Issue by benonymity** [advplyr/audiobookshelf-app#543] opened 2023-02-01 20:47 UTC
When switching server, or even clicking the connect to server button while offline, the saved play speed resets to zero. Is this stored variable tied to server configs on iOS?

**Comment by advplyr** [comment] 2023-02-01 20:52
I haven't figured out what is going on here yet but I believe it is related to upgrading the capacitor storage plugin. https://capacitorjs.com/docs/updating/4-0#storage

We switched from storing the playback rate on the server to storing it locally on the device, so we are only storing it locally using that plugin.

For some reason it isn't updating. Related or possible duplicate issue is #532

**Comment by advplyr** [comment] 2023-02-19 20:34
Duplicate of #532

I'm pretty confident these are the same issue so merging them. iOS & Android

**Closed by advplyr** 2023-02-19 20:34 UTC
Labels: enhancement
