### ISSUE TITLE
Android When using Tailscale VPN, app displays no internet.

### ISSUE THREAD

**Issue by OpnSrcConstruction** [advplyr/audiobookshelf-app#662] opened 2023-04-07 08:20 UTC
### Steps to reproduce

1. Start Talescale
2. Open App.
3. tap on connect
4. Final screen says No Internet

### Expected behaviour
I Tested expected behavior, by turning off my Tailscale NT, adding a local address, U/n & p/w and it seams to work as expected.

** Side-note. 99.999% of the time T.S. does NOT stop normal internet traffic, but let's me get into my local machines for free. **

### Actual behaviour
The connect settings screen, where a user would normally add credentials is NOT selectable to edit the address;
unless I turn off T.S. Saying "No Internet".

### Environment data

Audiobookshelf Version:
Android App: 0.9.3-63-beta

#### Android Issue
Android version:
8.0.0

Device model:
Samsung Galaxy S7

Stock or customized system:
Stock/non-rooted

** I am going to test this behavior on a few other Android devices around the house, later and report any differences or similarities. **

**Comment by OpnSrcConstruction** [comment] 2023-04-07 14:06
I tested the app on a few Other devices I have access to. I was surprised to see a Lenovo 14e gen. 2 chromebook all worked as expected. The Samsung galaxy Tab A(wifi-only) worked well as well. Also a pair of Newer phones worked as well; although they had their own data connection. My s7 and a spare s7 around the house, that ONLY use wifi are the only mobile devices in the house that the connection address couldn't be added.

**Comment by advplyr** [comment] 2023-04-07 15:04
Is this a duplicate of #566?

**Comment by advplyr** [comment] 2023-05-20 19:57
Duplicate of #566

**Closed by advplyr** 2023-05-20 19:57 UTC
Labels: bug

**Comment by pssandhu** [comment] 2023-07-10 19:49
I had a quick look at this issue and from my basic understanding of the code, it seems that the capacitor network plugin sees the vpn connection as the active network and correctly identifies that it doesnt provide general internet access. However, it doesnt then check other connections for internet access.

I'm assuming this is the relevant code but please correct me if i'm wrong.
https://github.com/ionic-team/capacitor-plugins/blob/798f788452f1f21e868cbab32743db3875d930e9/network/android/src/main/java/com/capacitorjs/plugins/network/Network.java#L91

Some useful info: https://developer.android.com/reference/android/net/NetworkCapabilities

I don't really have a way to test/debug this theory so some help would be appreciated and then maybe the bug can be filed upstream against the plugin

**Comment by advplyr** [comment] 2023-07-10 19:56
@pssandhu Yeah this is correct. I'm not sure this is a bug with the plugin. The main thread for this issue is #566
