### ISSUE TITLE
Advanced seeking options, e.g., a large and small (SABP) or dynamic/increasing incremental (Kodi)

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf-app#937] opened 2023-11-12 17:03 UTC
### Is your feature request related to a problem? Please describe.
Moving forward and backward by either 10 sec. or chapters/files (if present) does not allow for moving in useful increments when needing to move in more than several tens of seconds.  

### Describe the solution you'd like
Here's several ideas that can _all_ be added as enhancements to help with this issue:

1. have a major and minor increment that can be defined by the user the way Smart Audiobook Player (SABP) does.
2. Where available toggle between the overall [book] progress and the progress on the chapter/file so that seeking can be done within that smaller section vs. the larger one (since, while the former is quite imprecise, the latter is hopelessly so)
3. A dynamic seek that can be triggered either by multiple pressing or by holding down the seek arrow.  These jumps are definable on e.g., Kodi.  I've been using SABP for so long that I forget how Rockbox used to work, but I'm fairly sure it had something similar to this.
4. Hold down the seek button to seek continuously in a direction, possibly in a dynamic/increasing speed (1x > 2x > 4x > 8x ...)

### Describe alternatives you've considered
Asking the author of smart audioboook player to integrate ABS into that app.

**Comment by advplyr** [comment] 2023-11-12 19:59
Duplicate of #695

**Closed by advplyr** 2023-11-12 19:59 UTC
Labels: enhancement
