### ISSUE TITLE
Playback speed resets

### ISSUE THREAD

**Issue by tknorris** [advplyr/audiobookshelf-app#689] opened 2023-04-28 21:00 UTC
### Steps to reproduce

Recently (for the last month or so), I'm seeing playback speed reset intermittently when playing back an audiobook. I normally listen at 1.2x and usually download the book in advance for local playback. At first I thought it only happened when I started a new book, but it's also happening when starting a new session of the same book. Unfortunately, I haven't found a reliable way to reproduce it yet.

### Expected behaviour
Playback speed should be persistent.

### Actual behaviour
It isn't

### Environment data

Audiobookshelf Version:
Server: docker 2.2.19 (issue predates this server version to at least 2.2.16)

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
Client: Android 0.9.63-beta

Device model:
Samsung S22+

Stock or customized system:
Stock

**Comment by advplyr** [comment] 2023-04-28 21:05
Duplicate of #532

**Comment by advplyr** [comment] 2023-04-28 21:05
The playback speed issue happens when you re-open the app

**Closed by advplyr** 2023-04-28 21:05 UTC
Labels: bug
