### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by IstadR** [advplyr/audiobookshelf-app#1100] opened 2024-02-25 06:57 UTC
There should be support for IPv6 in the app.

Today, when CG-NAT are coming more and more, IPv6 is the easiest way to connect to our servers.

But the app don't support IPv6.

**Comment by advplyr** [comment] 2024-02-25 10:43
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2151

**Closed by advplyr** 2024-02-25 10:43 UTC
Labels: enhancement
