### ISSUE TITLE
[Bug] Android home screen widget not updated

### ISSUE THREAD

**Issue by 0verEngineer** [advplyr/audiobookshelf-app#658] opened 2023-04-02 22:03 UTC
### Steps to reproduce

1. Add home screen widget
2. Go into the app
3. Play something
4. Widget does not show the playing book

### Expected behaviour
- Widget should always be synced with the app

### Actual behaviour
- Widget not always synced with the app

### Environment data

Audiobookshelf Version:

- [x] Android App? 2.2.17

#### Android Issue
Android version: 13

Device model: Google Pixel 7 Pro

Stock or customized system: Graphene OS

**Comment by shlomitan** [comment] 2023-04-04 18:40
Hi,
Just started my self-hosted server today and downloaded the app.
This happens to me as well. The widget is static, doesn't update what's playing or even changes the play/pause icon.

Would love to give more info or try and figure this out, but I don't know where to begin 🤷🏼‍♂️

**Comment by 0verEngineer** [comment] 2023-04-08 08:48
@advplyr what does the "1 Task completed" thing mean?

**Comment by MikeBishop** [comment] 2023-04-10 14:29
@0verEngineer, it's because of the (checked) checkbox in front of the Android App version. The GitHub feature is intended for tracking subtasks of an issue that are/aren't checked off, but it seems to have been accidentally invoked by the bug description here.

**Comment by lerndmina** [comment] 2023-05-17 21:43
Hey, just commenting to say I have this issue too. If I remove and re-add the widget, then it will work for a little while but after some time of the app not being in use, the next time I go to use the widget the play and pause buttons are missing. When I then resume playback via the app, the widget does not update to reflect the playback status.

Device: Google Pixel 7A
OS: Android 13 (Stock installed from Google)

![signal-2023-05-17-224151](https://github.com/advplyr/audiobookshelf-app/assets/10632157/6cfa8cfb-0815-457d-9fa2-0617ad10d878)

**Comment by advplyr** [comment] 2023-05-23 20:47
Fixed in [v0.9.64-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.64-beta)

**Comment by 0verEngineer** [comment] 2023-05-23 21:12
@advplyr Is it not possible to always show the audio controls even if the app is not running in the background and then start the app in the background and just play without showing the app?

**Comment by advplyr** [comment] 2023-05-23 21:17
It is possible because some other apps do this however I was not able to get this working entirely in the background. I would like to get that figured out eventually, maybe with just downloaded books at first

**Comment by advplyr** [comment] 2023-05-25 20:15
I'm testing this v0.9.64-beta and still seeing issues with the widget updating

**Comment by revilo951** [comment] 2023-05-29 06:18
Same here

**Comment by advplyr** [comment] 2023-06-01 21:53
I re-added the widget on the latest release to do more testing and now it seems to be working.

If anyone else can re-add and test that would be great.

**Comment by JohanSF** [comment] 2023-06-02 04:04
> I re-added the widget on the latest release to do more testing and now it seems to be working.
> 
> If anyone else can re-add and test that would be great.

This works short while (hours or a couple of days according to my tests) and then it stops working again.

**Comment by advplyr** [comment] 2023-06-02 18:21
Yep just confirmed coming back to test today and it is no longer working.

**Comment by advplyr** [comment] 2023-06-25 19:41
Added in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)

**Closed by advplyr** 2023-06-25 19:41 UTC
Labels: bug, awaiting release
