### ISSUE TITLE
Translation for the App

### ISSUE THREAD

**Issue by Demian98** [advplyr/audiobookshelf-app#861] opened 2023-09-05 09:35 UTC
### Is your feature request related to a problem? Please describe.
It would be great if the app is available in different languages.

### Describe the solution you'd like
I have compared the strings file of the ABS App (audiobookshelf-app/strings/en-us.json) with the string file of the web client (audiobookshelf/client/strings/en-us.json). The fields names in the JSON are the same.

Could a simple solution be, to take the translations from the web version (de.json, nl.json, ...) and place it in the android version as well?

I'm especially interested in the German version, as my family is starting more and more to use ABS and their English is not that well.

**Comment by advplyr** [comment] 2023-09-05 13:21
Duplicate of #448

**Comment by advplyr** [comment] 2023-09-05 13:22
Yeah we can re-use the same strings from the web. I just wanted to set something up so they can be updated once in the same place

**Closed by advplyr** 2023-09-05 13:21 UTC
Labels: enhancement
