### ISSUE TITLE
add hotkeys for non-touchscreen device?

### ISSUE THREAD

**Issue by gotbletu** [advplyr/audiobookshelf-app#1154] opened 2024-03-27 11:05 UTC
### Is your feature request related to a problem? Please describe.
the app works fine if you have a touchscreen to swipe pages when reading comicbooks like CBZ files but i also use this on my big TV with a Nvidia Shield device and a wireless mini keyboard. But it does not have any hotkeys mapping that im aware of, I tried arrow keys, vim hotkeys, mouse clicks and nothing works.

### Describe the solution you'd like
add keyboard hotkeys like arrows keys, vim hotkeys (hjkl), zoom hotkeys and mouse clicks support 

### Describe alternatives you've considered
Maybe add a feature like an on-screen bar for navigation instead? This way people that uses a simple remote can still read comicbooks on the TV without much issues.
zoom in/out, next page, prev page, jump to page ...etc

**Comment by nichwall** [comment] 2024-03-27 13:37
Related to https://github.com/advplyr/audiobookshelf-app/issues/784 and https://github.com/advplyr/audiobookshelf-app/issues/606

**Comment by advplyr** [comment] 2024-03-27 21:06
Duplicate of #606

**Comment by advplyr** [comment] 2024-03-27 21:06
If something specific isn't mentioned there you can add to that thread

**Closed by advplyr** 2024-03-27 21:06 UTC
Labels: enhancement

**Comment by bilbospocketses** [comment] 2026-04-07 12:33
apk for sideloading is available for Android TV.

It needs to be tested on devices beyond my Google TV Streamer 4K, but on that device it works pretty well, so it should be fine on standard Android and Google TV devices back to Android 8. Not sure how well it will work on Fire TV, but am interested to hear any feedback.

All feedback is appreciated over on my forked repo so I can continue to tune the app while the devs of the main repo work on reviewing and merging the PR.

APK: https://github.com/bilbospocketses/audiobookshelf-app/releases/

Issues page for feedback (bugs, enahncements, etc): https://github.com/bilbospocketses/audiobookshelf-app/issues

Pull Request: https://github.com/advplyr/audiobookshelf-app/pull/1843

User guide for the ATV app: https://github.com/bilbospocketses/audiobookshelf-app/blob/android-tv-dpad-navigation/docs/TV_USER_GUIDE.md
