### ISSUE TITLE
[Feature Request] Carplay

### ISSUE THREAD

**Issue by simonaplin** [advplyr/audiobookshelf-app#667] opened 2023-04-13 12:51 UTC
### Is your feature request related to a problem? Please describe.
Long drives are a great time to listen to audiobooks and while audible, the audiobooks native app and my podcatcher Overcast all support carplay Audiobookshelf does not

### Describe the solution you'd like
I would like it if the Audiobookshelf iOS app supported Carplay and was available as an app on the in-car dashboard to continue listening to my books in the car. 

### Describe alternatives you've considered
Hooking up my phone as a straight bluetooth audio source works for listening to the books, but I can't use apple's navigation or get notifications through carplay and use it as a straight bluetooth audio source at the same time. 

### Additional context
https://developer.apple.com/carplay/

**Comment by advplyr** [comment] 2023-04-13 12:57
Duplicate of #475

**Closed by advplyr** 2023-04-13 12:57 UTC
Labels: enhancement
