### ISSUE TITLE
[Enhancement] Reduce battery usage

### ISSUE THREAD

**Issue by p-rintz** [advplyr/audiobookshelf-app#1104] opened 2024-02-26 08:05 UTC
### Steps to reproduce

1. Run app in background

### Expected behaviour
- It should not use large amounts of battery

### Actual behaviour
- In the last 1-2 weeks or so, keeping ABS app open in the background uses large amounts of battery

### Environment data

Audiobookshelf Version: 2.8.0

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 17.3.1 // 0.9.72-beta

iPhone model: 12

![IMG_1111](https://github.com/advplyr/audiobookshelf-app/assets/13933258/7c93a51c-f13e-45c9-aaf4-80f26241986a)

**Comment by TeroKeso** [comment] 2024-05-24 10:07
I use an iPhone 15 IOS 17.4.1 and typically get about 3 hours with ABS 12% battery. This with local books only.

With a 10 day view I get 22 hours and 5% total battery drain. I don't know how Apple calculates these numbers :D 

Note: On the road I use tailscale connection back to my server and then ABS and tailscale use crazy amount of battery. Still this has been calculated to my 10 days usage and still overall low.

**Comment by hjk321** [comment] 2024-05-29 04:33
Considering this is now considered an enhancement and not a bug, I don't think it should be a blocker for the ios app to come out of beta. (#541)

**Comment by mfcar** [comment] 2024-06-05 19:11
I'm trying to find some piece of information to understand why i'm out of juice so fast
I don't have knowledge in Xcode, then probably all of this can be wrong

I kept the app running, playing an audiobook in the background with the device on standby, and I got these data after 1 hour:

----

<img width="1517" alt="Screenshot 2024-06-05 at 17 58 19" src="https://github.com/advplyr/audiobookshelf-app/assets/814828/34855688-cde9-4bed-9fd0-a8c006ed0ef9">

After 1 hour

<img width="1517" alt="Screenshot 2024-06-05 at 18 58 24" src="https://github.com/advplyr/audiobookshelf-app/assets/814828/d4c7cf49-6c18-4ee7-a21a-08140b285152">

----

Look at the major problems: Overhead and the Network. In a 1-hour period, the gauge has always been in the Hard range.

Regarding the overhead, Apple says: _Overhead represents energy use as a result of bringing up radios and other system resources your app needs to perform work._

Based on this, I activated the Network Inspector. Times in times, a POST request is sent to the session endpoint. I commented out the ReportProgress code just to check, and tried to run it again. 

----

<img width="1005" alt="Screenshot 2024-06-05 at 20 01 35" src="https://github.com/advplyr/audiobookshelf-app/assets/814828/c689f107-f73d-49bb-a47b-9735cc519714">

----

I notice that the Energy Usage gauge sometimes drops to Low, sometimes goes to High, but generally stays on the Low

<img width="1517" alt="Screenshot 2024-06-05 at 19 31 32" src="https://github.com/advplyr/audiobookshelf-app/assets/814828/37ce5630-e543-43ff-a2a2-a6f5a3bfe398">

**Comment by jerry00020001** [comment] 2024-08-19 13:52
Can this be marked as complete? I’ve got zero issues with battery after checking battery usage.

**Comment by advplyr** [comment] 2024-08-19 14:58
Yup thanks for following up

**Closed by advplyr** 2024-08-19 14:58 UTC
Labels: enhancement

**Comment by Gadgetroch** [comment] 2024-09-27 09:40
Hi -- i have the same issue on android

**Comment by dierochade** [comment] 2024-09-28 15:38
> Hi -- i have the same issue on android

Please open a new issue, cause this is 

- ios related thread
- closed as completed. 

Thanks
