### ISSUE TITLE
[Android Auto] Use book cover as background

### ISSUE THREAD

**Issue by Ansem93** [advplyr/audiobookshelf-app#1126] opened 2024-03-09 15:58 UTC
### Is your feature request related to a problem? Please describe.
Right now the widget is just a brownish square, or it has a black background if it have ABS opened

### Describe the solution you'd like
Use the book cover as background. Voice recently updated their Android Auto player and added this feature too, not sure if you can use/learn from their code

### Additional context
If you need it I can take some photos of ABS and Voice to make a comparison!

**Comment by advplyr** [comment] 2024-03-09 19:46
Are you talking about a homescreen widget or android auto? Can you take a screenshot of where you are seeing no cover?

**Comment by Ansem93** [comment] 2024-03-09 20:16
Sorry, i had to go to the car.
I made 3 photos to compare voice and abs
![20240309_192456](https://github.com/advplyr/audiobookshelf-app/assets/6626218/5d958348-92ce-47bd-b0ff-36e8ad464ee4)
![20240309_192502](https://github.com/advplyr/audiobookshelf-app/assets/6626218/c6b2af50-73ee-4038-b9b0-c9e1cbe9356f)
![20240309_192540](https://github.com/advplyr/audiobookshelf-app/assets/6626218/2e865c32-8e21-4203-9c35-8c428ce943ba)
![20240309_192609](https://github.com/advplyr/audiobookshelf-app/assets/6626218/5f1b8365-97cd-465b-bf16-503cc610218b)
![20240309_192625](https://github.com/advplyr/audiobookshelf-app/assets/6626218/3d394601-d97c-42fe-af30-9953c0363b52)
![20240309_192711](https://github.com/advplyr/audiobookshelf-app/assets/6626218/f41ad027-6682-40fd-a1a4-2cb23f41ddba)

**Comment by advplyr** [comment] 2024-03-10 10:19
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/141

**Closed by advplyr** 2024-03-10 10:19 UTC
Labels: enhancement
