### ISSUE TITLE
All images on "Newest Episodes" have green underline, even tho i've not listened to them (show fine on webpage)

### ISSUE THREAD

**Issue by cooljimy84** [advplyr/audiobookshelf-app#264] opened 2022-07-01 08:48 UTC
### Steps to reproduce

1.Open app
2. scroll down to "Newest Episodes"
3.

### Expected behaviour
- Unlistened episodes to not have green underline of image

### Actual behaviour
- All show green under line, tho half listened to show the yellow progress bar on them

### Environment data

Audiobookshelf Version: 2.0.22

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version:7.0

Device model:
Samsung S8

Stock or customized system:
Rooted Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment] 2022-07-03 20:50
I wasn't able to replicate this. Is this every time a new podcast episode is added it shows as finished?

**Comment by cooljimy84** [comment] 2022-07-04 07:55
I thought it was all, but "linux game cast" ep 515 came down and on the app it shows no green under the art work, all the others have the green, even tho i've not listened to them (and confirmed with the webpage)
Linux unplugged, ubuntu security podcast and others show green, only on the app tho.

Are there any logs i can turn on/pull ?

**Comment by cooljimy84** [comment] 2022-07-04 20:42
I've got another android phone i will install and try on.

**Comment by cooljimy84** [comment] 2022-07-16 22:04
Same issue on my andriod 12.

**Comment by advplyr** [comment] 2022-07-16 23:56
Are you able to reproduce this every time? Can you show a screenshot or something of you downloading a new podcast episode and it appearing on the desktop and mobile as 100% finished?

I need more information to look into this since it isn't happening for me.

**Comment by cooljimy84** [comment] 2022-08-10 08:32
i've done a fresh server install (2.1.2 deb) and android app install. Add one one podcast and they all came in as new with out any green banner. I've just started listen on the web interface and i can see all the episodes have the yellow in progress bottom banner ?

**Comment by cooljimy84** [comment] 2022-08-10 08:33
![Screenshot_20220810-093029_audiobookshelf](https://user-images.githubusercontent.com/12459151/183854645-2970ab46-3b8a-467d-bd81-215c0392ffd9.png)

**Comment by advplyr** [comment] 2022-08-12 21:46
Fixed in [v0.9.56-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.56-beta)

**Closed by advplyr** 2022-08-12 21:46 UTC
Labels: bug
