### ISSUE TITLE
Listening progress skipping backwards

### ISSUE THREAD

**Issue by scorpio862** [advplyr/audiobookshelf-app#1] opened 2021-09-12 13:12 UTC
This app is great but I can see one problem with it. 
When I'm listening to audiobook on my mobile phone this application is working in the background and I use the media notification to play and pause the book. But then, when I open this app, the progress of the currently listened book is skipping backwards a lot and I have to manually search the timeline to adjust the progress of the audiobook. This happens quite often.

I'm guessing this happens because when I open the app, it takes the listening progress of the book from the server which is not up to date. 
Is it possible to store the progress in the android app so it doesn't download out of date data from the server?

I only listen to audiobooks using this app and never with web browser so I don't really need the listening progress to be downloaded from the server.

**Comment by advplyr** [comment] 2021-09-13 00:35
You are correct, it was not storing progress locally. I think this is resolved in `v0.8.0-beta` that just went live. I went over some details about the offline support [here](https://github.com/advplyr/audiobookshelf/issues/14#issuecomment-917744526).

> When a connection with the server is established all of your local audiobook progress will be synced with the server based on the last update timestamp.

**Closed** 2021-09-18 18:36 UTC

**Comment by advplyr** [comment] 2021-09-20 19:55
I had this issue also on the old version, but I can't reproduce it on the newest version.

Can you make sure you are running `v0.9.0-beta` and provide a few steps on how I can reproduce it?

While testing it I noticed a bug when listening offline, then connecting to the server, it does not sync your currently playing audiobook correctly.
