### ISSUE TITLE
Add ability to download & view EPISODE image for Podcasts

### ISSUE THREAD

**Issue by rxbrad** [advplyr/audiobookshelf-app#1087] opened 2024-02-16 18:31 UTC
Currently, a given podcast displays the same ```<channel> // <image>``` podcast art for all episodes.

Would be nice if ABS also downloaded each individual episode's ```<channel> //  <item> // <image>``` art (if it exists), and made this available to display in clients.

**Comment by advplyr** [comment] 2024-02-16 20:22
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1573

**Closed by advplyr** 2024-02-16 20:22 UTC
Labels: enhancement
