### ISSUE TITLE
Controls Disappear When Re-Opening App

### ISSUE THREAD

**Issue by dathbe** [advplyr/audiobookshelf-app#995] opened 2023-12-20 16:00 UTC
### Steps to reproduce
I have not tried to recreate the issue yet, but it happened this morning when:

1. Was listening to App
2. Exited (did not completely close) App
3. Let it sit for a while
4. Open app again
5. Last listened to book started playing automatically, but there were no controls at the bottom of the screen to pause it.  The only way I could pause was to slide down from the top to get the controls on the widgets screen.  Or, I suppose I could have killed the app.

### Expected behaviour
I can't say whether the book is supposed to immediately pick up and start playing (that might be useful in the car or in other situations where hands and eye contact are at a premium).  But the controls should be visible any time a book is playing.  

### Actual behaviour
As I said above, the controls were not visible anywhere.  Maybe this is user error (I was just able to get into the Beta yesterday), but I would expect the controls to be available at the bottom of the window.  
![2023-12-20 06-53-55 Darin_Phone 1342](https://github.com/advplyr/audiobookshelf-app/assets/14321825/85205867-af5f-422b-8e17-29cc03216c25)
It's not exactly visible in this photo, but the book is playing at the time I took this screenshot.  Am I missing something, or should there be some controls at the bottom of the screen (that when clicked pull up the full-screen controls).

Some notes on possibly recreating this to help recreating the issue:

I was listening to a book on my iPhone in the car via Bluetooth.
I then switched the car to play a different audio source (though I don't think I explicitly paused Audiobookshelf)
I then was listening on my phone to the same book via headphones.
I then paused the book in my phone.
I then listened to the book on my iPad via headphones.
I paused the iPad.
Both devices were put down for several hours, but the app was not killed on either device.
When I picked up the phone several hours later, this issue popped up.

### Environment data

Audiobookshelf Version: 2.6.0

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 17.1.2

iPhone model: 13 mini

**Comment by advplyr** [comment] 2023-12-20 16:06
The book is not supposed to start playing automatically. I haven't been able to reproduce it yet but it was brought up already here #973

**Comment by advplyr** [comment] 2023-12-20 16:06
Duplicate of #973

**Closed by advplyr** 2023-12-20 16:06 UTC
Labels: bug
