### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by beasthouse-au** [advplyr/audiobookshelf-app#426] opened 2022-10-28 04:39 UTC
Is it possible to change the location of the progress bar in the iOS app? Currently it sits at the bottom of the screen and functionality is almost non-existent.  Suggest moving it up a bit. I have provided two screen shots of the ABS iOS app and one of a different app (Prologue) to show better placement of the bar.

![1](https://user-images.githubusercontent.com/78465928/198503925-1c159c40-9dd0-43e0-93a7-bca77637ede3.png)
![2](https://user-images.githubusercontent.com/78465928/198503937-fa1fce48-61bb-4591-a85c-45eee51e9e3f.png)
![3](https://user-images.githubusercontent.com/78465928/198503945-898c7c70-bf65-4b71-939c-7844f02a35a1.png)

**Comment by B0rax** [comment] 2022-11-01 12:08
This seems to be a duplicate of #408

**Comment by beasthouse-au** [comment] 2022-11-01 12:42
> This seems to be a duplicate of #408

Yep looks like it, happy to close this off.

**Closed** 2022-11-01 12:42 UTC
