### ISSUE TITLE
Would be helpful to be able to add a local and remote server address

### ISSUE THREAD

**Issue by c-hri-s** [advplyr/audiobookshelf-app#923] opened 2023-10-26 08:17 UTC
I have my audiobookshelf server hosted at audiobookshelf.domain.com which I've added to the iOS mobile app.
When I'm downloading books to the phone, or when I'm streaming at home, the connection is going out via the internet and back, meaning it's slower.

I wondered if it would be possible to add a local server address for use when on home wifi (192.168..x.x:13378 for example), but use an alternative when that isn't reachable (audiobookshelf.domain.com for example)

I'd considered adding a local DNS entry to my router to redirect audiobookshelf.domain.com to 192.168.x.x, but because the local address uses port :13378 (running the server on docker) and the remote address just uses standard 443, this isn't possible.

**Comment by nichwall** [comment] 2023-10-26 13:41
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/209

**Comment by advplyr** [comment] 2023-10-26 14:03
Duplicate of #209

**Closed by advplyr** 2023-10-26 14:03 UTC
Labels: enhancement
