### ISSUE TITLE
Add Local Books Browsing Tab as a top menue Icon

### ISSUE THREAD

**Issue by Chriss78** [advplyr/audiobookshelf-app#1185] opened 2024-04-19 17:56 UTC
### Is your feature request related to a problem? Please describe.
I consider deploying access to my ADB server to my Kids. Typically the do not have yet flatrate dataplans and likely store more than 50 books local on their phone. Typically Kids Audiobooks have shorter playlengt what also incereases how many they will store for eg a 2 Week Holiday.  At the moment as I see only the Homesceen will display localy stored/donwloaded books. Which you can browse only horizontally which is OK for like 5 but not for 50. That would be cumbersome. I have not yet tested this but I will do. We all own Android and me using also one iPad only for viewing and testing. 

### Describe the solution you'd like
On the top menue one Icon indicates local books wich you can browse then like the library one. Including searching  and sorting.

### Describe alternatives you've considered
Probably using a 3rd party App for local books.

### Additional context
I will using a VPN to access the Server. When not connected ADB searching a while trying to connect when open. It would be good to have like a offline mode for only listen to for local books.

Thanks

**Comment by nichwall** [comment] 2024-04-19 19:03
You can disconnect from the server to use offline mode using the side menu.

For shorting shelves: https://github.com/advplyr/audiobookshelf-app/issues/743

For offline library: https://github.com/advplyr/audiobookshelf-app/issues/542

**Comment by advplyr** [comment] 2024-04-19 19:30
Duplicate of #542

**Closed by advplyr** 2024-04-19 19:30 UTC
Labels: enhancement
