### ISSUE TITLE
Listen Log/History

### ISSUE THREAD

**Issue by Mdh1229** [advplyr/audiobookshelf-app#888] opened 2023-09-28 04:55 UTC
### Is your feature request related to a problem? Please describe.
This is not related to a problem - just a suggestion for a feature that I feel many would find useful. Full disclosure - I have used 'Prologue' for Plex, and have for years. I would like to pivot to this app full time - but one of the missing features that keeps me from doing that is the lack of Listen History/Log. 

I will listen to a book in the car, or when I am headed to bed - and the book will run even if I was not consciously aware of what was being said. The 'Listen Log' feature allows me to see when I started listening (Time-of-day timestamp) as well as where in the book you are (Book play-time timestamp)  - then it is simple to jump back and find where **exactly** I had left off; it also shows the duration listened, but that is more of a 'nice-to-have'. 

### Describe the solution you'd like
A Listen History Log that shows each listening session by time of day, timestamp of the book, and duration listened during that session - pressing on any of the 'start' or 'end' book duration stamps would jump the user to that specific spot of the book.

### Describe alternatives you've considered
I hadn't really considered any others - but if you can think of a better way to accomplish this, I would 100% be open to seeing/hearing it - this just seems pretty straightforward and serves a specific purpose. 

### Additional context
I use IOS, so would love this feature in the testflight version :)

**Comment by nichwall** [comment] 2023-09-28 05:04
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/466

Already implemented on Android

**Comment by advplyr** [comment] 2023-10-07 18:50
Duplicate of #466

**Closed by advplyr** 2023-10-07 18:50 UTC
Labels: enhancement
