### ISSUE TITLE
Separate Speed Controls 

### ISSUE THREAD

**Issue by darthrater78** [advplyr/audiobookshelf-app#1138] opened 2024-03-16 11:40 UTC
It would be great to have separate speed settings for podcasts versus audiobooks. I tend to listen to audiobooks at a slower rate, and having to adjust back and forth is a bit tedious.

**Comment by nichwall** [comment] 2024-03-16 13:45
Duplicate of: https://github.com/advplyr/audiobookshelf/issues/1785

Related to:
https://github.com/advplyr/audiobookshelf/issues/1173
https://github.com/advplyr/audiobookshelf-app/issues/1039

**Comment by advplyr** [comment] 2024-03-16 17:10
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1785

**Closed by advplyr** 2024-03-16 17:10 UTC
Labels: enhancement
