### ISSUE TITLE
[Feature Request] Streamline Podcast Management

### ISSUE THREAD

**Issue by MattBlackOnly** [advplyr/audiobookshelf-app#1080] opened 2024-02-12 12:48 UTC
- Automatically mark podcasts as Finished when progress exceeds 95%.
- Automatically remove local copies of podcasts when they are marked as Finished.
- Remove "Listen Again" shelf for podcasts (or an option to remove it)

ABS has become my primary podcast app, and I'm truly grateful for the effort put into its development!

**Comment by nichwall** [comment] 2024-02-12 13:43
Duplicates of:

Making complete https://github.com/advplyr/audiobookshelf/issues/837
Deleting local https://github.com/advplyr/audiobookshelf-app/issues/293
Custom shelves https://github.com/advplyr/audiobookshelf-app/issues/743

You can show support for existing feature requests by leaving a thumbs up reaction to the top comment. Please don't just comment "+1" or "I also want this".
Thanks for taking the time to make the suggestions.

**Comment by advplyr** [comment] 2024-02-12 15:23
Duplicate of https://github.com/advplyr/audiobookshelf/issues/837

**Closed by advplyr** 2024-02-12 15:23 UTC
Labels: enhancement
