### ISSUE TITLE
Cannot turn off haptic feedback

### ISSUE THREAD

**Issue by bcmross** [advplyr/audiobookshelf-app#603] opened 2023-02-25 09:12 UTC
### Steps to reproduce

1. Turn the haptic feedback setting to "off."
2. Press any button that is supposed to provide haptic feedback when the setting is on.

### Expected behaviour
- Changing the haptic feedback setting to "off" should disable it entirely. 

### Actual behaviour
- Phone still vibrates when a button is pressed when it is set to "off."

### Environment data

Audiobookshelf Version: 0.9.62-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Pixel 3

Stock or customized system: Stock

Kernel version: 4.9.270-g862f51bac900-ab7613625
#0 Thu Aug 5 07:04:42 UTC 2021 (unsure if this is helpful info; included because I know my phone doesn't get security updates anymore)

**Comment by advplyr** [comment] 2023-02-25 09:49
I'm not able to reproduce this. Can you specify exactly which buttons you pressed?

If you had the sleep timer set then the play/pause button will reset the sleep timer and provide haptic feedback if you haven't disabled that.

**Comment by bcmross** [comment] 2023-02-25 22:31
The setting for the sleep timer feedback is off too. It happens with most
buttons really. Within the audio player (all with sleep timer off):
- Play / pause
- Skip forward, skip backward
- Selecting a different chapter
- Selecting a new sleep timer or canceling it
- Selecting a different speed
- Pressing "Create" for a new bookmark
- Selecting a created bookmark
- Seeking to a different time

When on an audiobooks page:
- Discard progress
- Download (next to stream)
- Stream / Play
- The plus button to add to a new playlist

In library:
- Selecting a different sort option
- Changing the view from tile to list and vice versa

There are likely more but you get the idea. If it's some freak thing with
only my phone, I think a good solution would be to have the option to
disable haptic feedback from my phone's settings, but I don't know if
that's possible since it doesn't require permissions.

**Comment by advplyr** [comment] 2023-02-25 22:40
Can you try going to the google play store and searching for "Android System WebView" then updating it

Then restart device

When you open the app check if the setting for haptic feed is still set to "off". That would verify whether the setting is getting saved properly.

**Comment by bcmross** [comment] 2023-02-25 23:18
Android System WebView seems to be the current version. When I launch the app and go to my settings, it says "off" but has the issue. However, I just tried selecting "off" again and that turned it off. Exiting the app and relaunching it starts the issue again.

**Comment by advplyr** [comment] 2023-02-26 18:54
Thanks, I fixed it for next release. The issue had to do with setting it on app launch.

**Comment by advplyr** [comment] 2023-03-09 23:32
Fixed in [v0.9.63-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.63-beta)

**Closed by advplyr** 2023-03-09 23:32 UTC
Labels: bug, awaiting release
