### ISSUE TITLE
[Enhancement]: Ability to pause/play audiobooks with the pause/play button on earphone for the iOS app

### ISSUE THREAD

**Issue by lwobniar** [advplyr/audiobookshelf-app#830] opened 2023-08-03 01:42 UTC
### Is your feature request related to a problem? Please describe.
Unable to pause or play audiobook using the pause/play button on the Apple Earphone. 

Nothing happens when press the pause/play button once.

To resume or pause, right now I need to press the pause/play button on the lock screen or within the iOS app instead.

### Describe the solution you'd like
Ability to pause/play audiobooks with the pause/play button on earphone for the iOS app

**Comment by XerxesDGreat** [comment] 2023-08-15 16:33
I second this. On iOS 16.6, I notice that when I push the play/pause button the behavior is a bit different:
- when the app is playing, hitting play/pause on the earphones acts the same as pressing "back 10 seconds"
- when the app is paused, hitting play/pause on the earphones resumes the playback as expected

**Comment by benonymity** [comment] 2023-11-12 18:20
Duplicate of #622

**Comment by advplyr** [comment] 2023-11-12 20:05
Duplicate of #622

**Closed by advplyr** 2023-11-12 20:05 UTC
Labels: enhancement
