### ISSUE TITLE
iOS Notifications For New Podcasts

### ISSUE THREAD

**Issue by eximo84** [advplyr/audiobookshelf-app#332] opened 2022-08-25 16:59 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

When a new episode is downloaded or available a notification is sent.

### Describe alternatives you've considered

Nothing

**Comment by advplyr** [comment] 2022-08-25 21:46
Duplicate of #197

**Closed by advplyr** 2022-08-25 21:46 UTC
Labels: enhancement
