### ISSUE TITLE
Android Auto - Add cover picture to interface

### ISSUE THREAD

**Issue by gamendorf** [advplyr/audiobookshelf-app#1057] opened 2024-01-24 20:13 UTC
ABS in Android Auto currently shows a blank page instead of the cover photo that is displayed in the ABS android app. Adding the cover art to Android Auto is not at all necessary, but would be a nice bit of flair. Shown below are the screenshots of ABS and Smart Audiobook Player both using the same book that was downloaded from ABS server via the ABS app.
(sorry for the reflections)

**ABS**
![20240124_140443](https://github.com/advplyr/audiobookshelf-app/assets/22079829/4571f22b-d2ab-4266-addc-c1a001d07e85)
![20240124_140423](https://github.com/advplyr/audiobookshelf-app/assets/22079829/798f4599-bdc3-42bd-9b16-663ad5eafc3a)

Smart Audiobook Player
![20240124_140620](https://github.com/advplyr/audiobookshelf-app/assets/22079829/beba3d69-3ed2-47d7-952b-eb86464f37a5)
![20240124_140549](https://github.com/advplyr/audiobookshelf-app/assets/22079829/051fc936-a480-49ee-8c44-585dbae0f279)

**Comment by advplyr** [comment] 2024-01-24 20:16
Duplicate of #141

**Closed by advplyr** 2024-01-24 20:16 UTC
Labels: enhancement
