### ISSUE TITLE
Seek/scrub bar cursor too small to grab

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf-app#713] opened 2023-05-26 10:55 UTC
### Steps to reproduce

1. Immediately after starting the playback of a podcast, try to use the scrubbing "dot" to fastforward in a podcast
2.
3.

### Expected behaviour
- I expect to be able to "grab" the dot and move it to an arbitrary position in the podcast

### Actual behaviour
- I can't grab the dot at all. The only thing that happens is that the podcast jumps back to timestamp 0:00

### Environment data

Audiobookshelf Version: 2.2.20

- [ ] Android App?
- [X] iOS App?

#### iOS Issue
iOS Version: 16.3.1

iPhone model:
14 Plus

**Comment by advplyr** [comment] 2023-06-04 21:09
I'm not able to reproduce this on an iphone 10. Grabbing the cursor shouldn't matter whether it is a podcast or an audiobook. Are you able to grab it on an audiobook?
Do you think it has something to do with how close it is to the edge of the screen?

**Comment by ScuttleSE** [comment] 2023-06-05 05:35
After some testing I get the same thing with audiobooks. It's like the dot is very very small and "grabbing" it for scrubbing requires you to hit it in a very specific place. Other apps seems to be a lot more forgiving.

**Comment by advplyr** [comment] 2023-06-11 20:47
I doubled the cursor selection size for the next release

**Comment by advplyr** [comment] 2023-06-25 19:42
Updated in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)

I'm still not sure if this is sensitive enough. I may need to take another approach to this but let me know

**Closed by advplyr** 2023-06-25 19:42 UTC
Labels: bug, awaiting release

**Comment by watsonbox** [comment] 2023-11-08 11:05
This is still a problem for me on an iPhone SE 2020 with the latest beta. Usually the only way I can seek forward in the track is to tap forward 10s many times, then grab the cursor from there when it's no longer too close to the side of the display.

Here is the behavior when attempting to grab it at the start of a track:

https://github.com/advplyr/audiobookshelf-app/assets/17737/2453b7da-9213-4fe2-a5f1-47818f4056d6

**Comment by nichwall** [comment] 2023-11-08 12:48
@watsonbox this is already tracked in another issue. https://github.com/advplyr/audiobookshelf-app/issues/818
