### ISSUE TITLE
add "collapse series" to the mobile app (same like already on the web ui)

### ISSUE THREAD

**Issue by Manantra** [advplyr/audiobookshelf-app#421] opened 2022-10-23 19:17 UTC
### Is your feature request related to a problem? Please describe.
There is a missing collapse series on the library view, so its hard to find single items which are not added to any series.

### Describe the solution you'd like
add collapse series in library view, same like on the web ui

### Describe alternatives you've considered
I dont have any alternatives for now. Please add this option also to the mobile apps.

### Additional context
![grafik](https://user-images.githubusercontent.com/113709296/197411708-399adaf4-bdf8-4359-92a9-8ab4b3cc91d7.png)

**Comment by advplyr** [comment] 2022-10-23 20:18
Duplicate of #99

**Closed by advplyr** 2022-10-23 20:18 UTC
Labels: enhancement
