### ISSUE TITLE
Downloading multiple books at the same time leads to undesired behavior

### ISSUE THREAD

**Issue by cassava** [advplyr/audiobookshelf-app#360] opened 2022-09-03 14:10 UTC
On the mobile app, I pressed the "download" button for several audiobooks, one after another, before any single one was finished, and the end result was:

- All (as far as I can tell) audiobooks were downloaded
- Only some audiobooks were visible in the app
- Some audiobooks had the wrong cover, at filesystem level

I didn't try to listen to them yet at this point, so I can't tell you if other things got switched around as well.

After deleting the audiobooks, I was able to reproduce at least the "not-recognized" part of the issue.

### Steps to reproduce

1. In the android app
2. Download at least 3 books at once (with in total > 100 files)
3. Wait till no more notifications

### Expected behaviour
- All audiobooks available and recognized locally

### Actual behaviour
- 5 audiobooks downloaded to file
- 3 audiobooks visible in app as "locally available"
- 1 audiobook had wrong cover - from an alternative audiobook that was downloaded

### Environment data

Audiobookshelf Version: 0.9.57-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12
Device model: Samsung S10+
Stock or customized system: stock

**Comment by advplyr** [comment] 2023-01-28 18:03
There were a lot of issues with the downloader but it has been rewritten for the next release. This is similar #515 so that will be the main thread going forward.

This should hopefully be resolved in the next release. See my comment https://github.com/advplyr/audiobookshelf-app/issues/515#issuecomment-1407453075

Duplicate of #515

**Closed by advplyr** 2023-01-28 18:03 UTC
Labels: bug
