### ISSUE TITLE
Stream Volume

### ISSUE THREAD

**Issue by dreaming-sparrow** [advplyr/audiobookshelf-app#446] opened 2022-11-21 08:23 UTC
Hello,

it seems to be not possible to change the volume for steamed music from within the android application.
Currently i have to change it via the google home application.
Volume up and down buttons are mapped to the inbuild volume not the streaming volume while streaming.

**Comment by advplyr** [comment] 2022-12-04 18:35
What is your Android version?

**Comment by dreaming-sparrow** [comment] 2022-12-06 20:23
> What is your Android version?

10

**Comment by jamesbrindle** [comment] 2023-02-15 12:15
I have the same issue. Android 12... Unable to change volume from phone when casting.

**Comment by advplyr** [comment] 2023-02-15 12:37
Duplicate of #584

That issue is more specific

**Closed by advplyr** 2023-02-15 12:37 UTC
