### ISSUE TITLE
Apple Watch app (!)

### ISSUE THREAD

**Issue by jphastings** [advplyr/audiobookshelf-app#693] opened 2023-04-30 09:09 UTC
(Very much a nice-to-have pipedream of a request; I recognise that an AppleWatch app would be enormous effort on a totally new stack, as I don't believe CapacitorJS or its ilk will ever run on any resource-light devices, like watches)

### The Problem
I love going for walks without my phone; my apple watch lets me listen to pre-downloaded media on my bluetooth headphones without my phone nearby. Audiobookshelf doesn't have an Apple Watch app, so I can't listen to self-hosted audiobooks while I'm away from my phone.

### Describe the solution you'd like
A very minimal apple watch app that:
- Lets me link with my account on my Audiobookshelf server
- Lets me choose one (or more?) audiobooks to download to my watch
- Lets me listen to a downloaded audiobook
  - Perhaps only from in progress audiobooks, to make the UI simpler?
  - Perhaps lets me stream an audiobook, if not downloaded?
- Synchronises progress with the Audiobookshelf server
  - A visual indication as to whether progress has been sync'd

### Describe alternatives you've considered
Using Audible, with its Apple Watch app:
- 😊 It works reasonably well
- 😩 Occasionally doesn't sync and isn't clear as to when it's sync'd
- 😩 Means my audiobookshelf progress/statuses aren't kept up to date 😔
- 😊 I buy tend to my audiobooks from Audible (before ripping to Audiobookshelf), so this is viable
- 😩 If Audible removes a title I've purchased from its library, I won't be able to listen to it on my watch.

Use BookPlayer, with its Apple Watch app:
- 😊 It works well
- 😩 Currently no server-syncing, so manual management of audiobook files is needed
- 😩 Means my audiobookshelf progress/statuses aren't kept up to date 😔
- 😊 Open-source and usable with DRM-free audiobooks

### Additional context

I recognise this is a _tonne_ of work, and in a totally new stack — so very unlikely to be selected for development!

However [BookPlayer](https://github.com/TortugaPower/BookPlayer) already provides these features, and is both open source and available under GPL 3.0 (compatible with Audiobookshelf!) so there may be _some_ shortcuts.

(They have [looked at using Audiobookshelf as a backend](https://github.com/TortugaPower/BookPlayer/issues/4#issuecomment-1383046601), but apparently the lack of nested folders is a dealbreaker)

**Comment by advplyr** [comment] 2023-04-30 15:13
Is this the same as #676?

I have looked at developing an app for Garmin watches because that is what I have. This is completely different though because it would be a separate app uploaded to their app store.

I think developing for apple watch would be similar to developing for car play. It is the same app and you set up a separate  interface.
CapacitorJS is only used for the UI/UX, all the logic is native Swift. Capacitor shouldn't hinder development for this just going off my very limited understanding of iOS. It would be useful if I had an apple watch though.

**Comment by advplyr** [comment] 2023-05-19 22:29
Duplicate of #676

**Closed by advplyr** 2023-05-19 22:29 UTC
Labels: enhancement
