### ISSUE TITLE
[Enhancement]: Download all books by author or series

### ISSUE THREAD

**Issue by MadBobUK** [advplyr/audiobookshelf-app#1226] opened 2024-06-09 11:47 UTC
### Describe the Feature/Enhancement

a bit faffy downloading 1 book at a time, Download all books by author or series

### Why would this be helpful?

android app for booksonic has this and i use all the time

### Future Implementation (Screenshot)

under ellipsis menu

### Audiobookshelf App Version

Android App - 0.9.74

**Comment by nichwall** [comment] 2024-06-09 14:43
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/188

**Closed** 2024-06-09 16:01 UTC
Labels: enhancement
