### ISSUE TITLE
"Sticky" Playback Speed (Android app)

### ISSUE THREAD

**Issue by darthrater78** [advplyr/audiobookshelf-app#732] opened 2023-06-04 22:49 UTC
Option to set an overall playback speed or per podcast. 

Playback defaults to 1x on re-open of app.

**Comment by darthrater78** [comment] 2023-06-04 22:57
Should have searched first, bug already exists.

https://github.com/advplyr/audiobookshelf-app/issues/532

**Comment by advplyr** [comment] 2023-06-05 00:05
Duplicate of #532

**Closed by advplyr** 2023-06-05 00:05 UTC
Labels: enhancement
