### ISSUE TITLE
Position not remembered for locally downloaded audiobooks

### ISSUE THREAD

**Issue by elementalest** [advplyr/audiobookshelf-app#290] opened 2022-07-17 13:35 UTC
### Steps to reproduce

1. Download audiobook locally
2. Start playing for a few minutes (or seek to any position)
3. Pause for serveral minutes (there's some timeout, maybe android puts the app to sleep?)
4. Unpause/Play

### Expected behaviour
- The audiobook plays where left off

### Actual behaviour
- The audiobook has reset to the begining

### Additional information
- Issue does not occur when streaming, only on locally downloaded coppies.

### Environment data

Audiobookshelf Version: v2.0.24 (Worked fine on v2.0.23)
Audiobookshelf App Version: v0.9.51-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Samsung

Stock or customized system: Stock

**Comment by advplyr** [comment] 2022-07-17 14:52
Please specify which version of the mobile app you are using

**Comment by advplyr** [comment] 2022-07-17 15:33
I just tested this and was not able to reproduce on the mobile app version 0.9.52-beta.

There are a few important things you didn't mention in your reproduction steps.

1. I stayed connected to the server I downloaded the book from. After playing a few minutes I went on the web app and checked the progress was updated for that book.
2. After pausing the audiobook I waited a few minutes and let my phone go to sleep. I woke it up and pressed play from inside the app (as opposed to pressing play on the home screen notification player)

My guess as to what is happening is you are staying connected to the server while listening but the progress is not being updated on the server. When you press play again the mobile app is going to reach out to the server and get the progress again in case it changed since it was last played.
Please check that while you listen to the downloaded audiobook it is updating the progress on the server.

**Comment by dweomer21** [comment] 2022-07-17 19:21
I was about to file an bug for this exact issue, so I will add my info here. If it turns out to be a different cause, I'll create a new issue.

My Environment:
- Pixel 6 Android 12
- ABS app v0.9.51-beta
- ABS server v2.0.24

This happens for every book I download locally, and am trying to listen to, and it is driving me absolutely batty (I regularly listen to 5 or 6 books throughout the day, and at this point, I've had to stop using the app.  Still trying to pinpoint this timeout length, and to get more info, but for now, all I have is this debug log entries on the server (I assume it is related):
`ERROR:  [MeController] syncLocalMediaProgress invalid local media progress object no library item [object Object]`

This only started happening recently, but I can't say for certain what version of the server or app. I can say that is was also happening in server v2.0.23 - I remember seeing the sync API notes and thinking "maybe that will solve this issue!".  This may have been occurring in the previous version to that as well, but I can't say for certain. I'll be keeping a more careful eye on versions from here on out.

I will post more info when I can (or let me know if you prefer I start a new issue instead).

**Comment by advplyr** [comment] 2022-07-17 21:03
@dweomer21 Is there a reason you haven't updated to the latest mobile app version? When I was fixing the local progress sync I had to make updates on both the server and the mobile app. You only updated the server.

**Comment by dweomer21** [comment] 2022-07-18 00:54
> @dweomer21 Is there a reason you haven't updated to the latest mobile app version? When I was fixing the local progress sync I had to make updates on both the server and the mobile app. You only updated the server.

Ok, that would explain why the mobile app has been so erratic since upgrading the server two days ago! When I updated the server to 2.0.24, I checked the Play Store on my phone, like I always do, but it didn't show an available update, so I assumed this wasn't a "paired" fix.  What I should have done, but didn't, was to double check the release tags on GitHub, which I now see shows that a new release came out 2 days ago, just as with the server.
Apologies for missing this - I just upgraded my home network to an OpnSense router, and Google (and some other services) are having strange delayed behavior at times. Wonder if that was the case here.
In any case, I will test this thoroughly now that I have 0.9.52-beta, and will report back if I can reproduce it.
Thank you!

**Comment by dweomer21** [comment] 2022-07-18 01:59
Ugh, as unlikely as it sounds, the problem actually seems worse than before the upgrade ☹️. I will do some quick maintenance and sanity checks tonight so I  can confirm if there's any other factors.

**Comment by elementalest** [comment] 2022-07-18 10:46
> I just tested this and was not able to reproduce on the mobile app version 0.9.52-beta.
> 
> There are a few important things you didn't mention in your reproduction steps.
> 
>     1. I stayed connected to the server I downloaded the book from. After playing a few minutes I went on the web app and checked the progress was updated for that book.
> 
>     2. After pausing the audiobook I waited a few minutes and let my phone go to sleep. I woke it up and pressed play from inside the app (as opposed to pressing play on the home screen notification player)
> 
> 
> My guess as to what is happening is you are staying connected to the server while listening but the progress is not being updated on the server. When you press play again the mobile app is going to reach out to the server and get the progress again in case it changed since it was last played. Please check that while you listen to the downloaded audiobook it is updating the progress on the server.

So the issue is that I was using v0.9.51-beta. Like dweomer21 I thought I was on the latest as google play wasn't presenting a newer version for some reason (even after refreshing things in google play). v0.9.52-beta only just became available for me now, not sure why. With v0.9.52-beta I no longer have the issue reported and everything seems to work as expected.

**Comment by dweomer21** [comment] 2022-07-18 17:27
FYI I will open a new issue for my problem over the next day or two, as the latest mobile app version seems to have fixed it for @elementalest, but has not fixed the issue for me.

**Comment by advplyr** [comment] 2022-07-22 16:47
This is fixed in [0.9.54-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.54-beta)

**Closed by advplyr** 2022-07-22 16:47 UTC
Labels: bug, waiting
