### ISSUE TITLE
[Bug]: Loosing listen position

### ISSUE THREAD

**Issue by woolmonkey** [advplyr/audiobookshelf-app#409] opened 2022-10-09 14:18 UTC
### Describe the issue

So using the android version sometimes I well loose my position and have to find it again because it starts at a previous saved spot usually where I started that listening session.  My latest time this happened was when in offline mode with a synced book.  Listened on a plane and when started again it was at a previous spot hours before.  I honestly can't remember if I took it out of airplane mode and it synced with the server during a layover but the likely hood is good.  I have had the same thing happen well listening on Android Auto but can't remember circumstances behind that.]

Just opened up app and the two time remaining are different.  The percentage says there is 4.5 hours left but the play par says 3 hours.  

### Steps to reproduce the issue

1. Listen to book
2. stop
3. listen again and back to previous saved spot.
4. The books are all downloaded.

### Audiobookshelf version

0.9.57-beta on 2.2.1 server

### How are you running audiobookshelf?

Docker

**Comment by alephtaph** [comment] 2022-11-21 07:10
Same here. I tested with the book downloaded or streamed, same behaviour.
Also, If I choose manually i.e. chapter 4, the play starts in chapter 3, if I choose chapter 5 it starts at chapter 4 and so on. This is very annoying in special with books that have long chapters.
The issue is not on every audiobook. I have not figured out what the trigger is.

**Comment by alephtaph** [comment] 2022-11-21 14:34
@advplyr Thank you for looking at this. The chapters are alright, and this only happens to books where I have the position issue too. I'm happy to share the audiobook with you, if you need one for investigation.

**Comment by advplyr** [comment] 2022-11-21 14:41
@alephtaph Can you check that the duration of the full audiobook matches what it actually is. The duration is pulled from the audio file metadata and if it is encoded incorrectly then Abs will have the wrong duration.

**Comment by mikehoyle** [comment] 2022-11-29 05:26
I have been experiencing this as well and working on a consistent repro.

Where I see it most is when I listen with a Bluetooth device. If I press play on the app, then at a later time pause via a button on the Bluetooth device and disconnect the device (as one would typically do at the end of a listening session), sometimes the progress won't be synced when I later come back to the app.

That's the most consistent pattern I've seen so far.

**Comment by Presjar** [comment] 2022-12-23 07:19
Using the latest android app and server versions today I lost my progress. The position went back several hours, so maybe a few days worth of listening sessing.

The book is downloaded to the device via the in app option so it is linked to the server item.

I had made several 10min or so listening sessions between stops in my car. On returning to the car after I'm thinking the fourth stop within 30min the playback started as normal upon Bluetooth connection to the car but this is when the position went way back. I let the playback automatically stop when I turn off the car. I don't usually have to interact with the app at all apart from the initial start playback at the start of the trip. 

I don't notice a log file available for the android client, is there something i can do to export a log or enable logs for future? I will post my connection log from the server from today in case that is useful.

**Comment by 77boaz** [comment] 2023-01-22 14:43
For what it's worth it also seems like the server takes precedence over the app... when I have a book fully downloaded to local.  If it loses connection, the server says I last had a signal a half hour ago so you are here!  For local books should the client/app have precedence over the server?  Maybe an offline mode?  Just wondering.. I'm no expert on how syncing works outside of kinda/sorta rsync :) Thanks for the support and this great app!

**Comment by Bostrolicious** [comment] 2023-01-24 22:17
I've encountered this problem many times as well. I always lose entire listening sessions, never just part of one. I've looked at the server logs, and there's no record of any progress synchronisation at the time progress was lost, not even the entries where it checks if synchronisation is necessary and determines everything is in sync. I think it's still somehow related to a connection to the server though, as I once tried shutting down the Abs container while listening to a book, and then didn't lose any progress for the remaining 10 hours of the book. Could just be a fluke, of course, but it normally happens more often than that.

Relating to what others have mentioned, I always download my books from the server, and almost always use bluetooth headphones. I don't use Android Auto (I do have a WearOS watch though, in case it's something related to playback control devices, but that seems dubious).

Happy to share logs from the latest session with lost progress if that's of any help. If so, do they need to be anonymised?

**Comment by advplyr** [comment] 2023-02-23 22:55
Since we are now syncing completely offline listening sessions in Android as of 0.9.62-beta can you test this again?

**Comment by Bostrolicious** [comment] 2023-02-24 21:15
> Since we are now syncing completely offline listening sessions in Android as of 0.9.62-beta can you test this again?

I'll try it out and report back if I either lose progress or get through an entire book without any issues. My listening time is a bit limited at the moment though, so it may take a while.

**Comment by mikehoyle** [comment] 2023-02-24 22:00
I've had zero issues for the past week or so after updating the server (not
sure when the app updated). So signs are good that the fix is working!

**Comment by 77boaz** [comment] 2023-02-25 01:13
It's working for me now and has been for about a week or so.  Although I just updated the app yesterday, it seemed to have been working a bit longer than that.  @mikehoyle could be right that it was actually fixed with the server.  I did notice the most recent app version just keeps local going under playing.  Maybe it was a combo of both.. Anyways it's working fine now.  I drove through the usual complete dead spots and it didn't lose position on the app.  Thanks!!

**Comment by advplyr** [comment] 2023-02-25 10:20
Great! Thanks for testing

**Closed by advplyr** 2023-02-25 10:20 UTC
Labels: bug, waiting

**Comment by pssandhu** [comment] 2024-09-16 21:47
I'm seeing this issue with android app version 0.9.76-beta and server version 2.13.3 (docker and nginx).

I have an audiobook that I have downloaded onto my phone and mainly listen offline (over bluetooth if that's relevant). When I connect back to the server later on, the listening position in the app is sometimes overwritten with the old listening position from the server.

The book is a single mp3 file that is 22.5 hrs long.

I'm trying to find exact reproduction steps and will post them if I find them.
