### ISSUE TITLE
Ability to disable Lock Screen progress bar seek

### ISSUE THREAD

**Issue by njakes** [advplyr/audiobookshelf-app#691] opened 2023-04-29 14:57 UTC
### Is your feature request related to a problem? Please describe.

While an audiobook is playing and the Lock Screen widget is visible you can accidentally skip hours of your book by accidentally touching the seek bar. This is problematic if your screen accidentally turns on while your phone is in hand or pocket. I can see how this would be useful for chapter separated into different files. However with chapterized m4b files it allows you to seek though the entire book from the Lock Screen. 

### Describe the solution you'd like

It would be nice to have the ability to just disable the touch seek function of the Lock Screen progress bar. 

### Describe alternatives you've considered

An alternative would be to make the Lock Screen widget show the current chapter progress instead of the whole book/file. I'm not sure if this would work for those with chapters separated into files though.

**Comment by advplyr** [comment] 2023-04-29 15:02
Duplicate of #526

**Comment by advplyr** [comment] 2023-04-29 15:02
If you are on Android we can update that issue to be for both iOS and Android

**Closed by advplyr** 2023-04-29 15:02 UTC
Labels: enhancement

**Comment by advplyr** [comment] 2023-04-29 15:03
Also related to #239 for showing chapter tracks with single file audiobooks
