### ISSUE TITLE
[iOS] External connection over HTTP Failure to Connect

### ISSUE THREAD

**Issue by skylarrudolph** [advplyr/audiobookshelf-app#538] opened 2023-02-01 00:37 UTC
### Steps to reproduce
1. Add server (my-custom-domain).lan:13378
2. Failed to ping server

### Expected behaviour
- Should be prompted with Username/Password for Audiobookshelf application 

### Actual behaviour
- Failed to ping server

### Environment data

Audiobookshelf Version:0.9.61

- [ ] Android App?
- [X] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version: 16.2

iPhone model: 12

**Comment by gh0sti** [comment] 2023-02-01 14:45
So either your firewall is blocking it or you don't have the correct port forwarding if your phone can't ping your server.

**Comment by Hexaphim** [comment] 2023-02-02 05:43
I have the same issue after upgrading to the latest version of the iOS app. It worked fine before the upgrade, after I can't connect to the server with a "Failed to ping server" error. The server is accessible in a browser on my phone using the same port.

**Comment by emmertex** [comment] 2023-02-02 07:33
This issue also appeared on 2 iOS devices which previously worked.
Have downgraded both to last version to allow connectivity. 

If you point it directly to an IP, it works, but we can't do this normally as we access through reverse proxy.
It is not a firewall issue as suggested by @gh0sti

**Comment by gh0sti** [comment] 2023-02-02 14:39
Does it still happen on iOS 16.3?

**Comment by Hexaphim** [comment] 2023-02-02 15:15
I upgraded to iOS 16.3 just to test this out, and it does not work on iOS 16.3 either.

**Comment by emmertex** [comment] 2023-02-03 08:39
I can now confirm the issue is also present on Android

**Comment by emmertex** [comment] 2023-02-08 04:05
[log] - [Axios] Making request to http://audiobook.url.com/ping
⚡️  [error] - Axios error code {"message":"Network Error","name":"Error","stack":"@capacitor://localhost/_nuxt/22a3f3e.js:2:190849\n@capacitor://localhost/_nuxt/22a3f3e.js:2:189807","config":{"url":"http://audiobook.url.com/ping","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"baseURL":"http://localhost:3000/","transformRequest":[null],"transformResponse":[null],"timeout":3000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}}}
⚡️  [error] - Server check failed {"message":"Network Error","name":"Error","stack":"@capacitor://localhost/_nuxt/22a3f3e.js:2:190849\n@capacitor://localhost/_nuxt/22a3f3e.js:2:189807","config":{"url":"http://audiobook.url.com/ping","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"baseURL":"http://localhost:3000/","transformRequest":[null],"transformResponse":[null],"timeout":3000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}}}

**Comment by advplyr** [comment] 2023-02-08 23:06
We're discussing this in Discord and trying to figure out how we should handle it.
At the moment the latest iOS app is restricted to using HTTPS for external connections.

This was the result of updating the deployment version to iOS 14.

**Comment by dalto12593** [comment] 2023-02-12 19:59
I’m having the same exact issue, fyi. iOS 16.3, app 0.9.60-beta. I can connect by manually putting in my IP rather than DDNS name ex. 90.677.68.1 vs audiobookshelf.ddnsname.com/13378

I keep getting ping error with DDNS name, all ports open on server side.

**Comment by advplyr** [comment] 2023-02-12 20:00
This will be fixed in the next release

**Comment by CunningSquirrel** [comment] 2023-02-15 18:39
Bump, I’m having the exact same issue. ios16.3 cannot connect using custom domain after update. I’m in I.T so can assure you that my firewall and port forwarding rules are correct.

**Comment by dalto12593** [comment] 2023-02-15 21:13
While waiting for the next release I’m just using the full IP address of my
hosted server.

**Comment by advplyr** [comment] 2023-02-19 23:28
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)

**Closed by advplyr** 2023-02-19 23:28 UTC
Labels: bug, awaiting release
