### ISSUE TITLE
[Enhancement]: AutoRewind on Pause

### ISSUE THREAD

**Issue by officialJCReyes** [advplyr/audiobookshelf-app#1380] opened 2024-11-14 20:30 UTC
### Describe the Feature/Enhancement

When I hit pause and then resume, I would like for playback to automatically rewind 10-30 seconds, user adjustable if possible.

Plex has this feature currently and it is very useful. 

### Why would this be helpful?

While on a road trip recently I had to pause several times because my son was crying. When I resumed I found myself manually rewinding to catch up. 

### Future Implementation (Screenshot)

There wouldn’t necessarily be any UI changes, just a client side option to enable it and ask how many seconds to rewind. 

### Audiobookshelf App Version

iOS App - 0.9.77

### Current Implementation (Screenshot)

I was driving when this thought came to mind.

**Comment by advplyr** [comment] 2024-11-14 20:43
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/205

**Closed by advplyr** 2024-11-14 20:43 UTC
Labels: enhancement
