### ISSUE TITLE
Auto play next podcast episode

### ISSUE THREAD

**Issue by calgara12** [advplyr/audiobookshelf-app#323] opened 2022-08-19 05:12 UTC
### Is your feature request related to a problem? Please describe.
Is it possible to autoplay the next podcast episode?
Most of the time I'm listening while riding my bike and its frustrating to stop, click the next episode and the go on.

### Describe the solution you'd like
I would like an option to enable that it automatically plays the next episode. The next episode should be determined by the sort order.

**Comment by advplyr** [comment] 2022-08-19 19:08
It is not possible now but so far the plan is we will adding queue functionality to the audio player similar to other media servers.

**Comment by thorinmesser** [comment] 2023-05-02 20:50
Could you elaborate on what you mean when you say "queue"? Please don't make us add podcast episodes to a queue or playlist to get them to play in order, at least serial podcast should automatically play from oldest to newest and should behave basically the same as the web app does now.

**Comment by advplyr** [comment] 2023-05-02 21:08
A queue would be a list of episodes the media player plays. Currently it is only set to play one at a time. Once a queue is setup then we would auto-populate the queue for podcasts. It would also be used for playlists and book collections.

**Comment by advplyr** [comment] 2023-05-21 16:58
Duplicate of #416

I'm merging the queue-related issues into one issue

**Closed by advplyr** 2023-05-21 16:58 UTC
Labels: enhancement
