### ISSUE TITLE
[Enhancement]: Merge Books with multiple CDs

### ISSUE THREAD

**Issue by FrenchGithubUser** [advplyr/audiobookshelf-app#1377] opened 2024-11-13 11:03 UTC
### Describe the Feature/Enhancement

Some books are composed of multiple CDs in subfolders, instead of displaying them as different books, it would be nice to be able to manually or automatically merge them into a single book

### Why would this be helpful?

To avoid what would look like book duplication

### Future Implementation (Screenshot)

N/A

### Audiobookshelf App Version

Android App - 0.9.77

**Comment by nichwall** [comment] 2024-11-13 13:36
The app is designed for consuming media, not managing the server.

Duplicate of https://github.com/advplyr/audiobookshelf/issues/1480

**Closed** 2024-11-13 13:52 UTC
Labels: enhancement
