### ISSUE TITLE
Playback problems with downloaded books and speed > 1x

### ISSUE THREAD

**Issue by vchatela** [advplyr/audiobookshelf-app#792] opened 2023-07-19 07:11 UTC
### Steps to reproduce

1. Download audiobook
2. Switch off network (to use local storage book)
3. Start listenning at higher speed (like x1.5)
4. Problem appears here

### Expected behaviour
- Overall duration (sum of each track) is correct

### Actual behaviour
- The evaluation of the overall duration of the book is incorrect, the sum of all tracks is wrong (probably because of the speed)

See hereunder the lenght of each track (sum is about 4h30min) 
![Screenshot_20230712_222243_com audiobookshelf app](https://github.com/advplyr/audiobookshelf-app/assets/6717940/5cbf2da0-4577-4a29-a36a-934bf7e667b9)

And see hereunder the incorrect sum
![Screenshot_20230712_222239_com audiobookshelf app](https://github.com/advplyr/audiobookshelf-app/assets/6717940/94a18ce9-7526-455e-b00c-0d603e765ebf)

And as correct lenght is 4h30 but app calculates 8h18min I can't listen second half of audio because considered as out of range.

You can also see the incorrect order of track btw ( https://github.com/advplyr/audiobookshelf-app/issues/759 ) 

### Environment data

Audiobookshelf Version: 2.3.2

- [x] Android App? v0.9.65-beta

#### Android Issue
Android version: 

Device model: Huawei P30 Pro

Stock or customized system: EMUI 12.0.0.149

**Comment by vchatela** [comment] 2023-07-19 18:44
My problem isn't the #759 , my problem is that book is about 4h, so in x2 it should be 2h but it is display 8h ! 
So last track is at 8h10min which doesn't exists because it is a 4h book.

So to me the problem is that calculation of total duration is wrong when using local media + speed > 1x

**Comment by advplyr** [comment] 2023-07-19 20:24
I just tested this and am unable to reproduce.

Are the chapters showing correctly on the web client? The chapters should come directly from the web

**Comment by vchatela** [comment] 2023-07-19 20:44
Yeap see it all good
![image](https://github.com/advplyr/audiobookshelf-app/assets/6717940/b130e562-b5de-4be3-b151-5032779f84e9)

I do not experience it every time, so I wonder if it is not while changing a lot speed or switching app off and back again.. Could not identify exactly how it comes but it comes very often.

The only fix I've found is to remove local book registry, then re-add it but it means I have to know where I was because it wasn't sync as I was offline.

**Comment by advplyr** [comment] 2023-07-19 21:27
The chapters table in the mobile app from the screenshot you shared above doesn't update at all with the speed. Only the timestamps in the audio player get changed with the playback speed, so I don't think playback speed has to do with it.

I think the issue is the audio files downloading out of order. If you can go the manage local media page and see what is in there that can be helpful. That is the page where you can change the order of the audio tracks.

Also, it would be useful to know if you are saving this in internal storage or you are selecting a shared folder to download to. If you are using internal storage you can test downloading to a shared folder.

**Comment by vchatela** [comment] 2023-07-24 08:23
Hi @advplyr ,
Ok so I'll reorder all locally and see if I see again the issue (as I finished old books where I've got problems).

I am above android 10 so I used only shared folder (in the sense I created a folder and set to download in that specific folder).

**Comment by advplyr** [comment] 2023-09-17 14:36
Closing this since I think the issue was the same as #759

**Closed by advplyr** 2023-09-17 14:36 UTC
Labels: bug
