### ISSUE TITLE
Use chapter instead of book on media card (Android)

### ISSUE THREAD

**Issue by kevingatera** [advplyr/audiobookshelf-app#700] opened 2023-05-10 03:54 UTC
I realize that this might be a big ask in terms of usability and how people are accustomed to using the app. I'm always frustrated when I look at the media card in the notification shade/on the car's infotainment and can't figure out whether the bar being shown is the progress I've made in the entire book (not very useful) or in the chapter (useful). 

### Describe the solution you'd like
Would it be possible to use the chapter track (if available) in the media card as opposed to the entire book track (by default) if present. 
![Screenshot_20230509-234354_audiobookshelf.png](https://github.com/advplyr/audiobookshelf-app/assets/22301610/bbe88d30-6d4c-4ee7-9c4f-cfc0a04e0dd7)

### Describe alternatives you've considered
An alternative would be to have the option to choose which gets chosen. 

### Additional context
Current state is to show the book track. See below. 
![Screenshot_20230509-234332_audiobookshelf.png](https://github.com/advplyr/audiobookshelf-app/assets/22301610/ec657b72-0348-4121-a41a-19f643b02f3d)

**Comment by advplyr** [comment] 2023-05-19 22:27
Duplicate of #239

**Closed by advplyr** 2023-05-19 22:27 UTC
Labels: enhancement
