### ISSUE TITLE
Elapsed time does not scale to listen speed

### ISSUE THREAD

**Issue by GeorgeHahn** [advplyr/audiobookshelf-app#261] opened 2022-06-26 20:41 UTC
### Steps to reproduce

1. Set playback speed above 1x
2. Skip partway into the book
3. Observe that the 'elapsed time' counter is still scaled to 1x time

### Expected behaviour
- I can see an argument for this behavior, but every other player I've used scales both the elapsed and remaining times.

### Actual behaviour
- Elapsed time remains scaled to 1x playback time

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.49-beta

Device model: Pixel 4a

Stock or customized system: Stock

**Comment by advplyr** [comment] 2022-07-04 19:20
This is not the case for me. I'm not sure if I understand what you mean though. See the elapsed time when I change speeds.

![elapsed-time](https://user-images.githubusercontent.com/67830747/177208221-d3ad219e-7b61-4f8d-b583-a69f0e5d53a3.gif)
.

**Comment by GeorgeHahn** [comment] 2022-07-04 19:27
Check out the time that has passed on the left side - it doesn't change after adjusting the playback speed

**Comment by advplyr** [comment] 2022-07-04 19:53
Oh I see, that was intentional. That is your actual position in the audiobook. I could see it go both ways though

**Comment by advplyr** [comment] 2023-02-04 19:49
Duplicate of #549

**Closed by advplyr** 2023-02-04 19:49 UTC
Labels: bug
