### ISSUE TITLE
Volume Booster / Loudness Booster

### ISSUE THREAD

**Issue by Dr-Blank** [advplyr/audiobookshelf-app#593] opened 2023-02-20 07:59 UTC
A QoL feature which is sometimes handy for books which sound low even at full volume or when you are in a noisy transit like me and can barely make out the words :P.

Solution:
A player setting just like the playback speed, which can set the playback sound. 

Screenshot from the app mAbook implementing this feature.

<img src=https://user-images.githubusercontent.com/64108942/220046006-b823d676-b5d5-4f0b-b8cc-e92192ebd095.jpg width=250 />

**Comment by advplyr** [comment] 2023-02-21 15:34
Duplicate of #195

**Closed by advplyr** 2023-02-21 15:34 UTC
Labels: enhancement
