### ISSUE TITLE
miss shelf "continue listening" on app-start when disconnected

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf-app#1033] opened 2024-01-05 11:26 UTC
### Steps to reproduce

1. start App 
2. disconnect from Server
3. close app
4. Start app
5. goto "Home"

### Expected behaviour
- the shelf "continue listening" is visible
- 
![Screenshot_20240105_121446_com audiobookshelf app](https://github.com/advplyr/audiobookshelf-app/assets/72630160/a3827956-2d8f-4a10-b767-c9f1fb7f0d61)

### Actual behaviour
- under "Home" the shelf "continue listening" is not visible, only "local books"
- 
![Screenshot_20240105_121425_com audiobookshelf app](https://github.com/advplyr/audiobookshelf-app/assets/72630160/ffd990c6-b8dc-4563-91ff-10838675728e)
If you start playing  a item from shelf "local books"  the shelf "continue listening" is visible till you close the app

### Environment data

Audiobookshelf Version: App 09.71 / MediaServer 2.7.0

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Huawei P30

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment] 2024-01-11 23:15
Duplicate of #1038

**Closed by advplyr** 2024-01-11 23:15 UTC
Labels: bug
