### ISSUE TITLE
position in chapter is kept when jumping backwards past the beginning of chapter

### ISSUE THREAD

**Issue by archwizardry** [advplyr/audiobookshelf-app#950] opened 2023-11-21 21:53 UTC
### Steps to reproduce

1. have an audiobook which is split into chapter files
2. start chapter 2 and listen 10 seconds
2. jump back 30 seconds. 
3. listen to the end of chapter 1
4. see error when chapter 2 starts

### Expected behaviour
I think that chapter 2 should start at the beginning.

### Actual behaviour
Chapter 2 starts where I left it when I jumped back

### Environment data
Audiobookshelf Version: 0.9.67

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: iOS 17.1.1

iPhone model: 12

#### Android Issue
Could not reproduce on Android

**Comment by nichwall** [comment] 2023-11-21 22:34
Looks like a duplicate of https://github.com/advplyr/audiobookshelf-app/issues/686

**Comment by advplyr** [comment] 2023-11-22 13:36
It's the same issue as #686. It is explained in this post best https://github.com/advplyr/audiobookshelf-app/issues/686#issuecomment-1650810197

**Comment by advplyr** [comment] 2023-11-22 13:36
Duplicate of #686

**Closed by advplyr** 2023-11-22 13:36 UTC
Labels: bug
